import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter5Meta: GitaChapterDetail = {
  n: 5,
  title: {en: 'Chapter 5 · Karma Sannyasa Yoga', hi: 'अध्याय 5 · कर्म संन्यास योग'},
  summary: {
    en: 'Renunciation and action reconciled — the lotus-leaf spirit. 29 verses.',
    hi: 'संन्यास और कर्म का समन्वय — कमलपत्र भाव। 29 श्लोक।'
  }
};

export const chapter5Verses: GitaVerse[] = [
  {n: 1, speaker: 'arjuna', sa: 'अर्जुन उवाच संन्यासं कर्मणां कृष्ण पुनर्योगं च शंससि। यच्छ्रेय एतयोरेकं तन्मे ब्रूहि सुनिश्चितम्॥', tr: 'Sannyasam karmanam Krishna punaryogam cha shamsasi, yachhreya etayorekam tanme bruhi sunishchitam.', en: 'You praise both quitting works and doing them in yoga, Krishna — tell me firmly which one is better.', hi: 'हे कृष्ण! आप कर्मों के संन्यास और योग दोनों की प्रशंसा करते हैं — निश्चय करके बताइए, दोनों में श्रेयस्कर क्या है?'},
  {n: 2, speaker: 'krishna', sa: 'श्रीभगवानुवाच संन्यासः कर्मयोगश्च निःश्रेयसकरावुभौ। तयोस्तु कर्मसंन्यासात्कर्मयोगो विशिष्यते॥', tr: 'Sannyasah karmayogashcha nihshreyasakaravubhau, tayostu karmasannyasatkarmayogo vishishyate.', en: 'Both quitting and working in yoga lead upward — but of the two, working in yoga outshines mere quitting.', hi: 'संन्यास और कर्मयोग दोनों कल्याणकारी हैं — पर दोनों में कर्म-संन्यास से कर्मयोग श्रेष्ठ है।'},
  {n: 3, speaker: 'krishna', sa: 'ज्ञेयः स नित्यसंन्यासी यो न द्वेष्टि न काङ्क्षति। निर्द्वन्द्वो हि महाबाहो सुखं बन्धात्प्रमुच्यते॥', tr: 'Jneyah sa nityasannyasi yo na dveshti na kankshati, nirdvandvo hi mahabaho sukham bandhatpramuchyate.', en: 'Know him as ever-renounced who neither hates nor craves — beyond opposites, mighty-armed, he slips free of bonds with ease.', hi: 'जो न द्वेष करता है न इच्छा करता है, उसे नित्य-संन्यासी जानो — द्वंद्वों से मुक्त होकर, महाबाहो, वह सहज बंधन से छूटता है।'},
  {n: 4, speaker: 'krishna', sa: 'साङ्ख्ययोगौ पृथग्बालाः प्रवदन्ति न पण्डिताः। एकमप्यास्थितः सम्यगुभयोर्विन्दते फलम्॥', tr: 'Sankhyayogau prithagbalah pravadanti na panditah, ekamapyasthitah samyagubhayorvindate phalam.', en: 'Only the childish call wisdom and working apart — the wise do not — for one path rightly held yields both fruits.', hi: 'सांख्य और योग को अलग-अलग अज्ञानी कहते हैं, पंडित नहीं — एक में भी ठीक से स्थित दोनों का फल पाता है।'},
  {n: 5, speaker: 'krishna', sa: 'यत्साङ्ख्यैः प्राप्यते स्थानं तद्योगैरपि गम्यते। एकं साङ्ख्यं च योगं च यः पश्यति स पश्यति॥', tr: 'Yatsankhyaih prapyate sthanam tadyogairapi gamyate, ekam sankhyam cha yogam cha yah pashyati sa pashyati.', en: 'The goal reached by wisdom is reached by working too — whoever sees the two as one truly sees.', hi: 'सांख्यों का जो स्थान है, वही योगियों को भी मिलता है — जो सांख्य और योग को एक देखता है, वही देखता है।'},
  {n: 6, speaker: 'krishna', sa: 'संन्यासस्तु महाबाहो दुःखमाप्तुमयोगतः। योगयुक्तो मुनिर्ब्रह्म नचिरेणाधिगच्छति॥', tr: 'Sannyasastu mahabaho duhkhamaptumayogatah, yogayukto munirBrahma nachirenadhigachchhati.', en: 'Quitting without working is hard to win, mighty-armed — the sage teamed with practice reaches the Whole swiftly.', hi: 'हे महाबाहो! योग के बिना संन्यास पाना कठिन है — योगयुक्त मुनि शीघ्र ब्रह्म को पाता है।'},
  {n: 7, speaker: 'krishna', sa: 'योगयुक्तो विशुद्धात्मा विजितात्मा जितेन्द्रियः। सर्वभूतात्मभूतात्मा कुर्वन्नपि न लिप्यते॥', tr: 'Yogayukto vishuddhatma vijitatma jitendriyah, sarvabhutatmabhutatma kurvannapi na lipyate.', en: 'Teamed with practice, pure in self, mastered in self and senses, one with the self of all beings — acting, he is unstained.', hi: 'योगयुक्त, विशुद्धात्मा, विजितात्मा, जितेंद्रिय, सब भूतों का आत्मा ही जिसका आत्मा है — कर्म करते हुए भी लिप्त नहीं होता।'},
  {n: 8, speaker: 'krishna', sa: 'नैव किञ्चित्करोमीति युक्तो मन्येत तत्त्ववित्। पश्यञ्शृण्वन्स्पृशञ्जिघ्रन्नश्नन्गच्छन्स्वपञ्श्वसन्॥', tr: 'Naiva kinchitkaromiti yukto manyeta tattvavit, pashyanshrinvan sprishanjighrannashnangachchhansvapanshvasan.', en: 'Seeing, hearing, touching, smelling, eating, walking, sleeping, breathing — the knower of truth thinks, I do nothing at all.', hi: 'देखते, सुनते, छूते, सूँघते, खाते, चलते, सोते, साँस लेते — तत्त्ववेत्ता योगी मानता है कि मैं कुछ नहीं करता।'},
  {n: 9, speaker: 'krishna', sa: 'प्रलपन्विसृजन्गृह्णन्नुन्मिषन्निमिषन्नपि। इन्द्रियाणीन्द्रियार्थेषु वर्तन्त इति धारयन्॥', tr: 'Pralapanvisrijangrihnannunmishannimishannapi, indriyanindriyartheshu vartanta iti dharayan.', en: 'Speaking, releasing, grasping, opening and closing the eyes — he holds that senses merely move among sense-things.', hi: 'बोलते, त्यागते, ग्रहण करते, आँख खोलते-मूँदते भी — वह जानता है कि इंद्रियाँ विषयों में बरत रही हैं।'},
  {n: 10, speaker: 'krishna', sa: 'ब्रह्मण्याधाय कर्माणि सङ्गं त्यक्त्वा करोति यः। लिप्यते न स पापेन पद्मपत्रमिवाम्भसा॥', tr: 'Brahmanyadhaya karmani sangam tyaktva karoti yah, lipyate na sa papena padmapatramivambhasa.', en: 'Whoever lays his deeds on the Whole and acts with clinging dropped stays unstained by wrong, like a lotus leaf by water.', hi: 'जो कर्मों को ब्रह्म में अर्पित कर आसक्ति छोड़ कर्म करता है, वह पाप से लिप्त नहीं होता — जैसे कमलपत्र जल से।'},
  {n: 11, speaker: 'krishna', sa: 'कायेन मनसा बुद्ध्या केवलैरिन्द्रियैरपि। योगिनः कर्म कुर्वन्ति सङ्गं त्यक्त्वात्मशुद्धये॥', tr: 'Kayena manasa buddhya kevalairindriyair api, yoginah karma kurvanti sangam tyaktvatmashuddhaye.', en: 'With body, mind, thought, and senses alone, seekers act with clinging dropped, purely to cleanse the self.', hi: 'योगी शरीर, मन, बुद्धि और इंद्रियों से आसक्ति छोड़ केवल आत्मशुद्धि हेतु कर्म करते हैं।'},
  {n: 12, speaker: 'krishna', sa: 'युक्तः कर्मफलं त्यक्त्वा शान्तिमाप्नोति नैष्ठिकीम्। अयुक्तः कामकारेण फले सक्तो निबध्यते॥', tr: 'Yuktah karmaphalam tyaktva shantimapnoti naishthikim, ayuktah kamakarena phale sakto nibadhyate.', en: 'The steady one drops the fruit and gains lasting peace — the unsteady, led by craving, clings to fruit and is bound.', hi: 'युक्त पुरुष फल छोड़कर स्थायी शांति पाता है — अयुक्त कामना से फल में आसक्त हो बँधता है।'},
  {n: 13, speaker: 'krishna', sa: 'सर्वकर्माणि मनसा संन्यस्यास्ते सुखं वशी। नवद्वारे पुरे देही नैव कुर्वन्न कारयन्॥', tr: 'Sarvakarmani manasa sannyasyaste sukham vashi, navadvare pure dehi naiva kurvanna karayan.', en: 'Mentally laying down all deeds, the mastered dweller rests at ease in the nine-gated city, neither doing nor causing.', hi: 'मन से सब कर्मों का संन्यास कर जितेंद्रिय देही नौ द्वारों वाले पुर में सुख से रहता है — न करता, न कराता।'},
  {n: 14, speaker: 'krishna', sa: 'न कर्तृत्वं न कर्माणि लोकस्य सृजति प्रभुः। न कर्मफलसंयोगं स्वभावस्तु प्रवर्तते॥', tr: 'Na kartritvam na karmani lokasya srijati prabhuh, na karmaphalasamyogam svabhavastu pravartate.', en: 'The Lord fashions neither doership nor deeds for the world, nor joins fruits to deeds — nature alone turns.', hi: 'प्रभु न कर्तापन रचता है, न कर्म, न फल का संयोग — स्वभाव ही बरतता है।'},
  {n: 15, speaker: 'krishna', sa: 'नादत्ते कस्यचित्पापं न चैव सुकृतं विभुः। अज्ञानेनावृतं ज्ञानं तेन मुह्यन्ति जन्तवः॥', tr: 'Nadatte kasyachitpapam na chaiva sukritam vibhuh, ajnanenavritam jnanam tena muhyanti jantavah.', en: 'The all-pervading takes on no one’s wrong or merit — wisdom lies veiled by ignorance, and beings are deluded.', hi: 'विभु किसी के पाप-पुण्य को ग्रहण नहीं करता — ज्ञान अज्ञान से ढका है, इससे जीव मोहित होते हैं।'},
  {n: 16, speaker: 'krishna', sa: 'ज्ञानेन तु तदज्ञानं येषां नाशितमात्मनः। तेषामादित्यवज्ज्ञानं प्रकाशयति तत्परम्॥', tr: 'Jnanena tu tadajnanam yesham nashitamatmanah, teshamadityavajjnanam prakashayati tatparam.', en: 'But for those whose ignorance wisdom of the self has destroyed, that wisdom shines like the sun on the Highest.', hi: 'पर जिनका अज्ञान आत्मज्ञान से नष्ट हुआ, उनका ज्ञान सूर्य की भाँति परम को प्रकाशित करता है।'},
  {n: 17, speaker: 'krishna', sa: 'तद्बुद्धयस्तदात्मानस्तन्निष्ठास्तत्परायणाः। गच्छन्त्यपुनरावृत्तिं ज्ञाननिर्धूतकल्मषाः॥', tr: 'Tadbuddhayastadatmanastannishthastatparayanah, gachchhantyapunaravrittim jnananirdhutakalmashah.', en: 'Mind set on That, self one with That, rooted and devoted to That — stain washed by wisdom, they reach the no-return.', hi: 'तत्पर बुद्धि, तन्मय आत्मा, तन्निष्ठ, तत्परायण — ज्ञान से पाप धोकर अपुनरावृत्ति को पाते हैं।'},
  {n: 18, speaker: 'krishna', sa: 'विद्याविनयसम्पन्ने ब्राह्मणे गवि हस्तिनि। शुनि चैव श्वपाके च पण्डिताः समदर्शिनः॥', tr: 'Vidyavinayasampanne brahmane gavi hastini, shuni chaiva shvapake cha panditah samadarshinah.', en: 'On a learned gentle priest, a cow, an elephant, a dog, even an outcaste — the wise look with equal eye.', hi: 'विद्या-विनय वाले ब्राह्मण, गाय, हाथी, कुत्ते और चांडाल में पंडित समदर्शी होते हैं।'},
  {n: 19, speaker: 'krishna', sa: 'इहैव तैर्जितः सर्गो येषां साम्ये स्थितं मनः। निर्दोषं हि समं ब्रह्म तस्माद्ब्रह्मणि ते स्थिताः॥', tr: 'Ihaiva tairjitah sargo yesham samye sthitam manah, nirdosham hi samam Brahma tasmad Brahmani te sthitah.', en: 'Even here they have mastered birth whose minds rest in evenness — flawless and even is the Whole, so they stand in the Whole.', hi: 'जिनका मन समता में स्थित है, उन्होंने यहीं संसार जीत लिया — ब्रह्म निर्दोष और सम है, अतः वे ब्रह्म में स्थित हैं।'},
  {n: 20, speaker: 'krishna', sa: 'न प्रहृष्येत्प्रियं प्राप्य नोद्विजेत्प्राप्य चाप्रियम्। स्थिरबुद्धिरसम्मूढो ब्रह्मविद्ब्रह्मणि स्थितः॥', tr: 'Na prahrishyetpriyam prapya nodvijetprapya chapriyam, sthirabuddhirasammudho Brahmavid Brahmani sthitah.', en: 'Unthrilled by the pleasant, untroubled by the unpleasant — steady-minded, undeluded, the Whole-knower stands in the Whole.', hi: 'प्रिय पाकर हर्षित नहीं, अप्रिय पाकर उद्विग्न नहीं — स्थिरबुद्धि, मोहरहित ब्रह्मज्ञानी ब्रह्म में स्थित रहता है।'},
  {n: 21, speaker: 'krishna', sa: 'बाह्यस्पर्शेष्वसक्तात्मा विन्दत्यात्मनि यत्सुखम्। स ब्रह्मयोगयुक्तात्मा सुखमक्षयमश्नुते॥', tr: 'Bahyasparsheshvasaktatma vindatyatmani yatsukham, sa Brahmayogayuktatma sukhamakshayamashnute.', en: 'Unstuck from outer touches, he finds the joy within the self — teamed with the Whole, he tastes unending joy.', hi: 'बाहरी स्पर्शों में अनासक्त आत्मा भीतर का सुख पाता है — ब्रह्मयोग में जुड़ा वह अक्षय सुख भोगता है।'},
  {n: 22, speaker: 'krishna', sa: 'ये हि संस्पर्शजा भोगा दुःखयोनय एव ते। आद्यन्तवन्तः कौन्तेय न तेषु रमते बुधः॥', tr: 'Ye hi samsparshaja bhoga duhkhayonaya eva te, adyantavantah Kaunteya na teshu ramate budhah.', en: 'Pleasures born of contact are wombs of pain, Kaunteya, with beginning and end — the wise take no delight in them.', hi: 'स्पर्श से उपजे भोग दुःख के ही कारण हैं, आदि-अंत वाले हैं, कौंतेय — ज्ञानी उनमें नहीं रमता।'},
  {n: 23, speaker: 'krishna', sa: 'शक्नोतीहैव यः सोढुं प्राक्शरीरविमोक्षणात्। कामक्रोधोद्भवं वेगं स युक्तः स सुखी नरः॥', tr: 'Shaknotihaiva yah sodhum prakshar iravimokshanat, kamakrodhodbhavam vegam sa yuktah sa sukhi narah.', en: 'Whoever can bear, even here before leaving the body, the rush of craving and anger — he is steady, he is a happy man.', hi: 'जो शरीर छूटने से पहले ही काम-क्रोध के वेग को सह लेता है — वही युक्त है, वही सुखी नर है।'},
  {n: 24, speaker: 'krishna', sa: 'योऽन्तःसुखोऽन्तरारामस्तथान्तर्ज्योतिरेव यः। स योगी ब्रह्मनिर्वाणं ब्रह्मभूतोऽधिगच्छति॥', tr: 'Yoantahsukhoantararamastathantarjyotireva yah, sa yogi Brahmanirvanam Brahmabhuto adhigachchhati.', en: 'Happy within, at play within, lit from within — that seeker, grown one with the Whole, reaches the Whole’s release.', hi: 'जो भीतर सुखी, भीतर रमण करने वाला, भीतर ज्योति वाला है — वह योगी ब्रह्मभूत हो ब्रह्मनिर्वाण पाता है।'},
  {n: 25, speaker: 'krishna', sa: 'लभन्ते ब्रह्मनिर्वाणमृषयः क्षीणकल्मषाः। छिन्नद्वैधा यतात्मानः सर्वभूतहिते रताः॥', tr: 'Labhante Brahmanirvanamrishayah kshin akalmashah, chhinnadvaidha yatatmanah sarvabhutahite ratah.', en: 'Seers worn free of stain, doubts cut, selves mastered, delighting in the good of all beings — they win the Whole’s release.', hi: 'क्षीण पाप वाले ऋषि, द्वैत काटे, संयमी, सब भूतों के हित में रत — ब्रह्मनिर्वाण पाते हैं।'},
  {n: 26, speaker: 'krishna', sa: 'कामक्रोधवियुक्तानां यतीनां यतचेतसाम्। अभितो ब्रह्मनिर्वाणं वर्तते विदितात्मनाम्॥', tr: 'Kam akrodhaviyuktanam yatinam yatachetasam, abhito Brahmanirvanam vartate viditatmanam.', en: 'For strivers freed of craving and anger, mastered in mind, knowers of the self — release in the Whole lies close on every side.', hi: 'काम-क्रोध से मुक्त, संयत चित्त, आत्मज्ञानी यतियों हेतु ब्रह्मनिर्वाण सब ओर विद्यमान है।'},
  {n: 27, speaker: 'krishna', sa: 'स्पर्शान्कृत्वा बहिर्बाह्यांश्चक्षुश्चैवान्तरे भ्रुवोः। प्राणापानौ समौ कृत्वा नासाभ्यन्तरचारिणौ॥', tr: 'Sparshankritva bahirbahyanshchakshushchaivantare bhruvoh, pranapanau samau kritva nasabhyantaracharinau.', en: 'Setting outer touches outside, fixing the gaze between the brows, evening the inward and outward breaths moving in the nostrils —', hi: 'बाहरी विषयों को बाहर कर, दृष्टि भौंहों के बीच स्थिर कर, नासिका में विचरते प्राण-अपान को सम करके —'},
  {n: 28, speaker: 'krishna', sa: 'यतेन्द्रियमनोबुद्धिर्मुनिर्मोक्षपरायणः। विगतेच्छाभयक्रोधो यः सदा मुक्त एव सः॥', tr: 'Yatendriyamanobuddhirmunirmokshaparayanah, vigatechchhabhayakrodho yah sada mukta eva sah.', en: '…the sage with senses, mind and thought restrained, set on freedom, rid of wish, fear and anger — he is ever free.', hi: '…इंद्रिय-मन-बुद्धि संयमित कर मोक्षपरायण मुनि, इच्छा-भय-क्रोध से मुक्त — वह सदा मुक्त ही है।'},
  {n: 29, speaker: 'krishna', sa: 'भोक्तारं यज्ञतपसां सर्वलोकमहेश्वरम्। सुहृदं सर्वभूतानां ज्ञात्वा मां शान्तिमृच्छति॥', tr: 'Bhoktaram yajnatapasam sarvalokamaheshvaram, suhridam sarvabhutanam jnatva mam shantimrichchhati.', en: 'Knowing me as enjoyer of offerings and austerities, great lord of all worlds, friend of all beings — he finds peace.', hi: 'मुझे यज्ञ-तप का भोक्ता, समस्त लोकों का महेश्वर, सब भूतों का सुहृद जानकर वह शांति पाता है।'}
];
