import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter7Meta: GitaChapterDetail = {
  n: 7,
  title: {en: 'Chapter 7 · Jnana Vijnana Yoga', hi: 'अध्याय 7 · ज्ञान विज्ञान योग'},
  summary: {
    en: 'Knowledge and realisation — the Lord as the thread holding all existence. 30 verses.',
    hi: 'ज्ञान और विज्ञान — समस्त सत्ता को धारण करने वाला सूत्र। 30 श्लोक।'
  }
};

export const chapter7Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'मय्यासक्तमनाः पार्थ योगं युञ्जन्मदाश्रयः। असंशयं समग्रं मां यथा ज्ञास्यसि तच्छृणु॥', tr: 'Mayyasaktamanah Partha yogam yunjanmadashrayah, asamshayam samagram mam yatha jnasyasi tachchhrinu.', en: 'Fix your mind on me, take refuge in me, and listen — you will know me fully, beyond all doubt.', hi: 'मुझमें मन लगाकर, मेरा आश्रय लेकर सुनो — तुम मुझे पूर्णतः निस्संदेह जान लोगे।'},
  {n: 2, speaker: 'krishna', sa: 'ज्ञानं तेऽहं सविज्ञानमिदं वक्ष्याम्यशेषतः। यज्ज्ञात्वा नेह भूयोऽन्यज्ज्ञातव्यमवशिष्यते॥', tr: 'Jnanam teaham savijnanamidam vakshyamyasheshatah, yajjnatva neha bhuyoanyajjnatavayamavashishyate.', en: 'I will teach you knowledge joined with living realisation, after which nothing more remains to be known.', hi: 'मैं तुम्हें विज्ञानसहित ज्ञान पूर्णतः बताऊँगा, जिसे जानकर और कुछ जानना शेष नहीं रहेगा।'},
  {n: 3, speaker: 'krishna', sa: 'मनुष्याणां सहस्रेषु कश्चिद्यतति सिद्धये। यततामपि सिद्धानां कश्चिन्मां वेत्ति तत्त्वतः॥', tr: 'Manushyanam sahasreshu kashchidyatati siddhaye, yatatamapi siddhanam kashchinmam vetti tattvatah.', en: 'Among thousands, hardly one strives for perfection, and among strivers, hardly one knows me truly.', hi: 'हजारों मनुष्यों में कोई एक सिद्धि हेतु यत्न करता है, और यत्न करने वालों में कोई एक मुझे तत्त्व से जानता है।'},
  {n: 4, speaker: 'krishna', sa: 'भूमिरापोऽनलो वायुः खं मनो बुद्धिरेव च। अहङ्कार इतीयं मे भिन्ना प्रकृतिरष्टधा॥', tr: 'Bhumirapoanalo vayuh kham mano buddhireva cha, ahankara itiyam me bhinna prakritirashtadha.', en: 'Earth, water, fire, air, ether, mind, intellect and ego — this is my eightfold lower nature.', hi: 'पृथ्वी, जल, अग्नि, वायु, आकाश, मन, बुद्धि और अहंकार — यह मेरी आठ भागों वाली अपरा प्रकृति है।'},
  {n: 5, speaker: 'krishna', sa: 'अपरेयमितस्त्वन्यां प्रकृतिं विद्धि मे पराम्। जीवभूतां महाबाहो ययेदं धार्यते जगत्॥', tr: 'Apareyamitastvanyam prakritim viddhi me param, jivabhutam mahabaho yayedam dharyate jagat.', en: 'Beyond this lies my higher nature — the living Self by which this world is upheld, O mighty-armed.', hi: 'इससे भिन्न मेरी परा प्रकृति को जानो — वह जीव रूप है, हे महाबाहो, जिससे यह जगत धारण किया जाता है।'},
  {n: 6, speaker: 'krishna', sa: 'एतद्योनीनि भूतानि सर्वाणीत्युपधारय। अहं कृत्स्नस्य जगतः प्रभवः प्रलयस्तथा॥', tr: 'Etadyonini bhutani sarvanityupadharaya, aham kritsnasya jagatah prabhavah pralayastatha.', en: 'All beings spring from these two natures — I am the birth and the dissolution of the whole world.', hi: 'समस्त भूत इन्हीं दोनों से उत्पन्न जानो — मैं ही संपूर्ण जगत की उत्पत्ति और प्रलय हूँ।'},
  {n: 7, speaker: 'krishna', sa: 'मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय। मयि सर्वमिदं प्रोक्तं सूत्रे मणिगणा इव॥', tr: 'Mattah parataram nanyatkinchidasti Dhananjaya, mayi sarvamidam proktam sutre manigana iva.', en: 'Nothing is higher than me, Dhananjaya — all this hangs on me like pearls strung on a thread.', hi: 'हे धनंजय! मुझसे परे कुछ भी नहीं — यह सब मुझमें वैसे पिरोया है जैसे सूत्र में मणियाँ।'},
  {n: 8, speaker: 'krishna', sa: 'रसोऽहमप्सु कौन्तेय प्रभास्मि शशिसूर्ययोः। प्रणवः सर्ववेदेषु शब्दः खे पौरुषं नृषु॥', tr: 'Rasoahampsu Kaunteya prabhasmi shashisuryayoh, pranavah sarvavedeshu shabdah khe paurusham nrishu.', en: 'I am the taste in water, the light in sun and moon, the syllable Om in the Vedas, and manliness in men.', hi: 'हे कौन्तेय! जल में रस मैं हूँ, सूर्य-चंद्र में प्रभा मैं हूँ, वेदों में प्रणव और मनुष्यों में पौरुष मैं हूँ।'},
  {n: 9, speaker: 'krishna', sa: 'पुण्यो गन्धः पृथिव्यां च तेजश्चास्मि विभावसौ। जीवनं सर्वभूतेषु तपश्चास्मि तपस्विषु॥', tr: 'Punyo gandhah prithivyang cha tejashchasmi vibhavasau, jivanam sarvabhuteshu tapashchasmi tapasvishu.', en: 'I am the pure fragrance of earth, the radiance of fire, the life in all beings, and the austerity of ascetics.', hi: 'पृथ्वी में पवित्र गंध और अग्नि में तेज मैं हूँ, समस्त भूतों में जीवन और तपस्वियों में तप मैं हूँ।'},
  {n: 10, speaker: 'krishna', sa: 'बीजं मां सर्वभूतानां विद्धि पार्थ सनातनम्। बुद्धिर्बुद्धिमतामस्मि तेजस्तेजस्विनामहम्॥', tr: 'Bijam mam sarvabhutanam viddhi Partha sanatanam, buddhirbuddhimatamasmi tejastejasvinamaham.', en: 'Know me as the eternal seed of all beings, Partha — the intellect of the wise and the splendour of the splendid.', hi: 'हे पार्थ! समस्त भूतों का सनातन बीज मुझे जानो — बुद्धिमानों की बुद्धि और तेजस्वियों का तेज मैं हूँ।'},
  {n: 11, speaker: 'krishna', sa: 'बलं बलवतां चाहं कामरागविवर्जितम्। धर्माविरुद्धो भूतेषु कामोऽस्मि भरतर्षभ॥', tr: 'Balam balavatam chaham kamaragavivarjitam, dharmaviruddho bhuteshu kamoasmi Bharatarshabha.', en: 'I am the strength of the strong, free from craving — and the lawful desire in beings, O best of Bharatas.', hi: 'हे भरतश्रेष्ठ! काम-राग से रहित बलवानों का बल मैं हूँ, और प्राणियों में धर्म के अनुकूल काम मैं हूँ।'},
  {n: 12, speaker: 'krishna', sa: 'ये चैव सात्त्विका भावा राजसास्तामसाश्च ये। मत्त एवेति तान्विद्धि न त्वहं तेषु ते मयि॥', tr: 'Ye chaiva sattvika bhava rajasastamasashcha ye, matta eveti tanviddhi na tvaham teshu te mayi.', en: 'All states — calm, restless, or dull — come from me, yet I am not in them; they rest in me.', hi: 'सात्त्विक, राजस और तामस जो भी भाव हैं, सब मुझसे ही जानो — पर मैं उनमें नहीं, वे मुझमें हैं।'},
  {n: 13, speaker: 'krishna', sa: 'त्रिभिर्गुणमयैर्भावैरेभिः सर्वमिदं जगत्। मोहितं नाभिजानाति मामेभ्यः परमव्ययम्॥', tr: 'Tribhirgunamayairbhavairebhih sarvamidam jagat, mohitam nabhijanati mamebhyah paramavyayam.', en: 'Beguiled by these three veils of nature, the world fails to see me — changeless and beyond them.', hi: 'इन तीन गुणमय भावों से मोहित यह जगत मुझ अव्यय और परे को नहीं जानता।'},
  {n: 14, speaker: 'krishna', sa: 'दैवी ह्येषा गुणमयी मम माया दुरत्यया। मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते॥', tr: 'Daivi hyesha gunamayi mama maya duratyaya, mameva ye prapadyante mayametam taranti te.', en: 'Hard indeed to cross is my wondrous veil of nature — but those who surrender to me pass beyond it.', hi: 'मेरी यह गुणमयी दैवी माया दुस्तर है — जो मेरी शरण लेते हैं, वे इसे पार कर जाते हैं।'},
  {n: 15, speaker: 'krishna', sa: 'न मां दुष्कृतिनो मूढाः प्रपद्यन्ते नराधमाः। माययापहृतज्ञाना आसुरं भावमाश्रिताः॥', tr: 'Na mam dushkritino mudhah prapadyante naradhamah, mayayapahritajnana asuram bhavamashritah.', en: 'Wrongdoers, the deluded and the base never turn to me, their judgment stolen by illusion.', hi: 'मूढ दुष्कर्मी और अधम मनुष्य मेरी शरण नहीं लेते — माया से उनका ज्ञान हर लिया गया है।'},
  {n: 16, speaker: 'krishna', sa: 'चतुर्विधा भजन्ते मां जनाः सुकृतिनोऽर्जुन। आर्तो जिज्ञासुरर्थार्थी ज्ञानी च भरतर्षभ॥', tr: 'Chaturvidha bhajante mam janah sukritinoarjuna, arto jijnasurartharthi jnani cha Bharatarshabha.', en: 'Four kinds of good souls worship me, Arjuna — the distressed, the seeker, the desirer of gain, and the knower.', hi: 'हे अर्जुन! चार प्रकार के पुण्यात्मा मुझे भजते हैं — आर्त, जिज्ञासु, अर्थार्थी और ज्ञानी।'},
  {n: 17, speaker: 'krishna', sa: 'तेषां ज्ञानी नित्ययुक्त एकभक्तिर्विशिष्यते। प्रियो हि ज्ञानिनोऽत्यर्थमहं स च मम प्रियः॥', tr: 'Tesham jnani nityayukta ekabhaktirvishishyate, priyo hi jnaninoatyarthamaham sa cha mama priyah.', en: 'Noblest is the knower, ever steady in single devotion — dear indeed to me, and I dear to him.', hi: 'उनमें नित्ययुक्त अनन्यभक्त ज्ञानी श्रेष्ठ है — ज्ञानी को मैं अत्यंत प्रिय हूँ और वह मुझे प्रिय है।'},
  {n: 18, speaker: 'krishna', sa: 'उदाराः सर्व एवैते ज्ञानी त्वात्मैव मे मतम्। आस्थितः स हि युक्तात्मा मामेवानुत्तमां गतिम्॥', tr: 'Udarah sarva evaite jnani tvatmaiva me matam, asthitah sa hi yuktatma mamevanuttamam gatim.', en: 'All these are generous souls, yet the knower is my very Self — resting in me, the highest goal.', hi: 'ये सभी उदार हैं, पर ज्ञानी तो मेरा आत्मा ही है — वह मुझ उत्तम गति में स्थित है।'},
  {n: 19, speaker: 'krishna', sa: 'बहूनां जन्मनामन्ते ज्ञानवान्मां प्रपद्यते। वासुदेवः सर्वमिति स महात्मा सुदुर्लभः॥', tr: 'Bahunam janmanamante jnanavanmam prapadyate, Vasudevah sarvamiti sa mahatma sudurlabhah.', en: 'After many births the wise one surrenders to me, seeing all as one — such a soul is rare indeed.', hi: 'बहुत जन्मों के अंत में ज्ञानी मुझे प्राप्त होता है — ‘वासुदेव ही सब हैं’ — ऐसा महात्मा दुर्लभ है।'},
  {n: 20, speaker: 'krishna', sa: 'कामैस्तैस्तैर्हृतज्ञानाः प्रपद्यन्तेऽन्यदेवताः। तं तं नियममास्थाय प्रकृत्या नियताः स्वया॥', tr: 'Kamaistaistairhritajnanah prapadyanteanyadevatah, tam tam niyamamasthaya prakritya niyatah svaya.', en: 'Robbed of judgment by cravings, men turn to lesser gods, following rites shaped by their own nature.', hi: 'नाना कामनाओं से ज्ञान हरे जाने पर लोग अन्य देवताओं की शरण लेते हैं, अपनी प्रकृति के नियमों से बँधे।'},
  {n: 21, speaker: 'krishna', sa: 'यो यो यां यां तनुं भक्तः श्रद्धयार्चितुमिच्छति। तस्य तस्याचलां श्रद्धां तामेव विदधाम्यहम्॥', tr: 'Yo yo yam yam tanum bhaktah shraddhayarchitumichchhati, tasya tasyachalam shraddham tameva vidadhamyaham.', en: 'Whatever form a devotee longs to worship in faith, I steady his faith in that very form.', hi: 'जो भक्त जिस रूप को श्रद्धा से पूजना चाहता है, उसकी उसी श्रद्धा को मैं अचल करता हूँ।'},
  {n: 22, speaker: 'krishna', sa: 'स तया श्रद्धया युक्तस्तस्याराधनमीहते। लभते च ततः कामान्मयैव विहितान्हि तान्॥', tr: 'Sa taya shraddhaya yuktastasyaradhanamihate, labhate cha tatah kamanmayaiva vihitanhi tan.', en: 'Filled with that faith he worships, and from it gains his wishes — granted indeed by me.', hi: 'वह उसी श्रद्धा से पूजा करता है और अपनी कामनाएँ पाता है — वे मेरे ही विधान से मिलती हैं।'},
  {n: 23, speaker: 'krishna', sa: 'अन्तवत्तु फलं तेषां तद्भवत्यल्पमेधसाम्। देवान्देवयजो यान्ति मद्भक्ता यान्ति मामपि॥', tr: 'Antavattu phalam tesham tadbhavatyalpamedhasam, devandevayajo yanti madbhakta yanti mamapi.', en: 'Limited is the fruit gained by the small-minded — god-worshippers reach the gods, my devotees reach me.', hi: 'अल्पबुद्धियों को मिलने वाला फल नाशवान है — देवताओं के पूजक देवों को पाते हैं, मेरे भक्त मुझे पाते हैं।'},
  {n: 24, speaker: 'krishna', sa: 'अव्यक्तं व्यक्तिमापन्नं मन्यन्ते मामबुद्धयः। परं भावमजानन्तो ममाव्ययमनुत्तमम्॥', tr: 'Avyaktam vyaktimapannam manyante mamabuddhayah, param bhavamajananto mamavyayamanuttamam.', en: 'The unwise think the formless has merely taken form, blind to my supreme changeless being.', hi: 'अज्ञानी मुझे अव्यक्त से व्यक्त हुआ मानते हैं — मेरे अव्यय उत्तम परम भाव को नहीं जानते।'},
  {n: 25, speaker: 'krishna', sa: 'नाहं प्रकाशः सर्वस्य योगमायासमावृतः। मूढोऽयं नाभिजानाति लोको मामजमव्ययम्॥', tr: 'Naham prakashah sarvasya yogamayasamavritah, mudhoayam nabhijanati loko mamajamavyayam.', en: 'Veiled by my mystic power, I am not plain to all — this deluded world knows not my birthless being.', hi: 'योगमाया से ढका मैं सबके सामने प्रकट नहीं — यह मूढ जगत मुझे अज और अव्यय नहीं जानता।'},
  {n: 26, speaker: 'krishna', sa: 'वेदाहं समतीतानि वर्तमानानि चार्जुन। भविष्याणि च भूतानि मां तु वेद न कश्चन॥', tr: 'Vedaham samatitani vartamanani charjuna, bhavishyani cha bhutani mam tu veda na kashchana.', en: 'I know all beings — past, present, and to come — yet none truly knows me, Arjuna.', hi: 'हे अर्जुन! मैं भूत, वर्तमान और भविष्य के समस्त प्राणियों को जानता हूँ, पर मुझे कोई नहीं जानता।'},
  {n: 27, speaker: 'krishna', sa: 'इच्छाद्वेषसमुत्थेन द्वन्द्वमोहेन भारत। सर्वभूतानि सम्मोहं सर्गे यान्ति परन्तप॥', tr: 'Ichchhadveshasamutthena dvandvamohena Bharata, sarvabhutani sammoham sarge yanti parantapa.', en: 'By the delusion of liking and disliking, all beings fall into bewilderment from birth, O scorcher of foes.', hi: 'हे भारत! राग-द्वेष से उठे द्वंद्व-मोह से सभी प्राणी जन्म से ही मोह में पड़ते हैं।'},
  {n: 28, speaker: 'krishna', sa: 'येषां त्वन्तगतं पापं जनानां पुण्यकर्मणाम्। ते द्वन्द्वमोहनिर्मुक्ता भजन्ते मां दृढव्रताः॥', tr: 'Yesham tvantagatam papam jananam punyakarmanam, te dvandvamohanirmukta bhajante mam dridhavratah.', en: 'But those whose sins are spent through good deeds, freed from duality, worship me with firm resolve.', hi: 'जिन पुण्यकर्मियों का पाप समाप्त हो गया, वे द्वंद्व-मोह से मुक्त हो दृढ व्रत से मुझे भजते हैं।'},
  {n: 29, speaker: 'krishna', sa: 'जरामरणमोक्षाय मामाश्रित्य यतन्ति ये। ते ब्रह्म तद्विदुः कृत्स्नमध्यात्मं कर्म चाखिलम्॥', tr: 'Jaramaranamokshaya mamashritya yatanti ye, te brahma tadviduh kritsnamadhyatmam karma chakhilam.', en: 'Those who shelter in me, striving past age and death, know the Absolute, the Self, and all action.', hi: 'जरा-मरण से मुक्ति हेतु मेरा आश्रय लेकर यत्न करने वाले ब्रह्म, अध्यात्म और संपूर्ण कर्म को जानते हैं।'},
  {n: 30, speaker: 'krishna', sa: 'साधिभूताधिदैवं मां साधियज्ञं च ये विदुः। प्रयाणकालेऽपि च मां ते विदुर्युक्तचेतसः॥', tr: 'Sadhibhutadhidaivam mam sadhiyajnam cha ye viduh, prayanakaleapi cha mam te viduryuktachetasah.', en: 'Those who know me as the ground of beings, gods, and sacrifice remember me even at the final hour.', hi: 'जो मुझे अधिभूत, अधिदैव और अधियज्ञ सहित जानते हैं, वे युक्तचित्त प्रयाणकाल में भी मुझे जानते हैं।'}
];
