import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter14Meta: GitaChapterDetail = {
  n: 14,
  title: {en: 'Chapter 14 · Gunatraya Vibhaga Yoga', hi: 'अध्याय 14 · गुणत्रय विभाग योग'},
  summary: {
    en: 'The three gunas and rising beyond them. 27 verses.',
    hi: 'तीन गुण और उनसे ऊपर उठना। 27 श्लोक।'
  }
};

export const chapter14Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'परं भूयः प्रवक्ष्यामि ज्ञानानां ज्ञानमुत्तमम्। यज्ज्ञात्वा मुनयः सर्वे परां सिद्धिमितो गताः॥', tr: 'Param bhuyah pravakshyami jnananam jnanamuttamam, yajjnatva munayah sarve param siddhimito gatahan.', en: 'I will teach again the highest wisdom that freed the sages to perfection.', hi: 'जिस परम ज्ञान से मुनियों ने सिद्धि पाई, वही उत्तम ज्ञान फिर बताता हूँ।'},
  {n: 2, speaker: 'krishna', sa: 'इदं ज्ञानमुपाश्रित्य मम साधर्म्यमागताः। सर्गेऽपि नोपजायन्ते प्रलये न व्यथन्ति च॥', tr: 'Idam jnanamupashritya mama sadharmyamagatahan, sargeapi nopajayante pralaye na vyathanti cha.', en: 'Resting in this wisdom, souls share my nature and stay steady through creation and dissolution.', hi: 'इस ज्ञान से मेरी स्वरूपता पाकर जीव सृष्टि में जन्मते नहीं और प्रलय में व्यथित नहीं होते।'},
  {n: 3, speaker: 'krishna', sa: 'मम योनिर्महद्ब्रह्म तस्मिन्गर्भं दधाम्यहम्। सम्भवः सर्वभूतानां ततो भवति भारत॥', tr: 'Mama yonirmahadbrahma tasmingarbham dadhamyaham, sambhavah sarvabhutanam tato bhavati Bharata.', en: 'The great womb of nature receives my seed, and from it all beings are born, Bharata.', hi: 'प्रकृति रूपी योनि में मैं गर्भ रखता हूँ, जिससे सब प्राणियों की उत्पत्ति होती है, भरतवंशी।'},
  {n: 4, speaker: 'krishna', sa: 'सर्वयोनिषु कौन्तेय मूर्तयः सम्भवन्ति याः। तासां ब्रह्म महद्योनिरहं बीजप्रदः पिता॥', tr: 'Sarvayonishu Kaunteya murtayah sambhavanti yahan, tasam brahma mahadyoniraham bijapradah pita.', en: 'Whatever forms appear in any womb, nature is their mother and I am the seed-giving father.', hi: 'सभी योनियों में जो रूप जन्मते हैं, प्रकृति उनकी माता है और मैं बीज देने वाला पिता हूँ।'},
  {n: 5, speaker: 'krishna', sa: 'सत्त्वं रजस्तम इति गुणाः प्रकृतिसम्भवाः। निबध्नन्ति महाबाहो देहे देहिनमव्ययम्॥', tr: 'Sattvam rajastama iti gunahan prakritisambhavahan, nibadhnanti mahabaho dehe dehinamavyayam.', en: 'Sattva, rajas and tamas, born of nature, bind the deathless soul in the body, mighty-armed one.', hi: 'प्रकृति से उत्पन्न सत्त्व, रज और तम गुण देह में अविनाशी जीव को बाँधते हैं, महाबाहो।'},
  {n: 6, speaker: 'krishna', sa: 'तत्र सत्त्वं निर्मलत्वात्प्रकाशकमनामयम्। सुखसङ्गेन बध्नाति ज्ञानसङ्गेन चानघ॥', tr: 'Tatra sattvam nirmalatvatprakashakamanamayam, sukhasangena badhnati jnanasangena chanagha.', en: 'Sattva is pure and bright and healthy, yet it binds through love of joy and love of knowing, sinless one.', hi: 'उनमें सत्त्व निर्मल और प्रकाशक है, पर सुख और ज्ञान की आसक्ति से बाँधता है, निष्पाप।'},
  {n: 7, speaker: 'krishna', sa: 'रजो रागात्मकं विद्धि तृष्णासङ्गसमुद्भवम्। तन्निबध्नाति कौन्तेय कर्मसङ्गेन देहिनम्॥', tr: 'Rajo ragatmakam viddhi trishnasangasamudbhavam, tannibadhnati Kaunteya karmasangena dehinam.', en: 'Know rajas as craving and restless thirst, binding the soul through hunger for deeds, Kaunteya.', hi: 'रज को राग रूप, तृष्णा और आसक्ति से उत्पन्न जानो, जो कर्म की आसक्ति से बाँधता है।'},
  {n: 8, speaker: 'krishna', sa: 'तमस्त्वज्ञानजं विद्धि मोहनं सर्वदेहिनाम्। प्रमादालस्यनिद्राभिस्तन्निबध्नाति भारत॥', tr: 'Tamastvajnanajam viddhi mohanam sarvadehinam, pramadalasyanidrabhistannibadhnati Bharata.', en: 'Know tamas as born of ignorance, deluding all embodied beings through neglect, laziness and sleep, Bharata.', hi: 'तम को अज्ञान से जन्मा और सब देहधारियों को मोहित करने वाला जानो, जो प्रमाद, आलस्य और निद्रा से बाँधता है।'},
  {n: 9, speaker: 'krishna', sa: 'सत्त्वं सुखे सञ्जयति रजः कर्मणि भारत। ज्ञानमावृत्य तु तमः प्रमादे सञ्जयत्युत॥', tr: 'Sattvam sukhe sanjayati rajah karmani Bharata, jnanamavritya tu tamah pramade sanjayatyuta.', en: 'Sattva pulls toward joy, rajas toward action, while tamas clouds knowing and pulls toward carelessness, Bharata.', hi: 'सत्त्व सुख में लगाता है, रज कर्म में, और तम ज्ञान ढककर प्रमाद में लगाता है, भारत।'},
  {n: 10, speaker: 'krishna', sa: 'रजस्तमश्चाभिभूय सत्त्वं भवति भारत। रजः सत्त्वं तमश्चैव तमः सत्त्वं रजस्तथा॥', tr: 'Rajastamashchabhibhuya sattvam bhavati Bharata, rajah sattvam tamashchaiva tamah sattvam rajastatha.', en: 'Each guna rises by pushing down the other two, and each in turn takes the lead, Bharata.', hi: 'रज और तम को दबाकर सत्त्व बढ़ता है, वैसे ही रज और तम भी बढ़ते हैं, भारत।'},
  {n: 11, speaker: 'krishna', sa: 'सर्वद्वारेषु देहेऽस्मिन्प्रकाश उपजायते। ज्ञानं यदा तदा विद्याद्विवृद्धं सत्त्वमित्युत॥', tr: 'Sarvadvareshu deheasminprakasha upajayate, jnanam yada tada vidyadvivriddham sattvamityuta.', en: 'When clear light shines through every gate of the body, know that sattva is strong.', hi: 'जब इस देह के सभी द्वारों में ज्ञान का प्रकाश हो, तब सत्त्व बढ़ा हुआ जानो।'},
  {n: 12, speaker: 'krishna', sa: 'लोभः प्रवृत्तिरारम्भः कर्मणामशमः स्पृहा। रजस्येतानि जायन्ते विवृद्धे भरतर्षभ॥', tr: 'Lobhah pravrittirarambhah karmanamashamah spriha, rajasyetani jayante vivriddhe Bharatarshabha.', en: 'Greed, rushing into deeds, restlessness and craving appear when rajas grows, best of Bharatas.', hi: 'लोभ, प्रवृत्ति, कर्मों का आरंभ, अशांति और इच्छा — ये रज बढ़ने पर प्रकट होते हैं, भरतश्रेष्ठ।'},
  {n: 13, speaker: 'krishna', sa: 'अप्रकाशोऽप्रवृत्तिश्च प्रमादो मोह एव च। तमस्येतानि जायन्ते विवृद्धे कुरुनन्दन॥', tr: 'Aprakashoapravrittishcha pramado moha eva cha, tamasyetani jayante vivriddhe Kurunandana.', en: 'Darkness, dullness, neglect and delusion appear when tamas grows, delight of the Kurus.', hi: 'अप्रकाश, निष्क्रियता, प्रमाद और मोह — ये तम बढ़ने पर उत्पन्न होते हैं, कुरुनंदन।'},
  {n: 14, speaker: 'krishna', sa: 'यदा सत्त्वे प्रवृद्धे तु प्रलयं याति देहभृत्। तदोत्तमविदां लोकानमलान्प्रतिपद्यते॥', tr: 'Yada sattve pravriddhe tu pralayam yati dehabhrit, tadottamavidam lokanamalanpratipadyate.', en: 'One who leaves the body while sattva rules reaches the pure worlds of the wise.', hi: 'सत्त्व बढ़ा होने पर देह त्यागने वाला उत्तम ज्ञानियों के निर्मल लोकों को पाता है।'},
  {n: 15, speaker: 'krishna', sa: 'रजसि प्रलयं गत्वा कर्मसङ्गिषु जायते। तथा प्रलीनस्तमसि मूढयोनिषु जायते॥', tr: 'Rajasi pralayam gatva karmasangishu jayate, tatha pralinastamasi mudhayonishu jayate.', en: 'Dying in rajas, one is reborn among doers, and dying in tamas among the ignorant.', hi: 'रज में मरकर कर्मासक्तों में जन्मता है, और तम में मरकर मूढ़ योनियों में जन्मता है।'},
  {n: 16, speaker: 'krishna', sa: 'कर्मणः सुकृतस्याहुः सात्त्विकं निर्मलं फलम्। रजसस्तु फलं दुःखमज्ञानं तमसः फलम्॥', tr: 'Karmanah sukritasyahuh sattvikam nirmalam phalam, rajasastu phalam duhkhamajnanam tamasah phalam.', en: 'Good deeds ripen into pure sattvic fruit, rajasic deeds into pain, and tamasic deeds into ignorance.', hi: 'पुण्य कर्म का फल सात्त्विक और निर्मल कहा गया, राजस का दुःख और तामस का अज्ञान है।'},
  {n: 17, speaker: 'krishna', sa: 'सत्त्वात्सञ्जायते ज्ञानं रजसो लोभ एव च। प्रमादमोहौ तमसो भवतोऽज्ञानमेव च॥', tr: 'Sattvatsanjayate jnanam rajaso lobha eva cha, pramadamohau tamaso bhavatoajnanameva cha.', en: 'From sattva comes knowing, from rajas comes greed, and from tamas come neglect, delusion and ignorance.', hi: 'सत्त्व से ज्ञान, रज से लोभ, और तम से प्रमाद, मोह और अज्ञान उत्पन्न होते हैं।'},
  {n: 18, speaker: 'krishna', sa: 'ऊर्ध्वं गच्छन्ति सत्त्वस्था मध्ये तिष्ठन्ति राजसाः। जघन्यगुणवृत्तिस्था अधो गच्छन्ति तामसाः॥', tr: 'Urdhvam gachchhanti sattvastha madhye tishthanti rajasahan, jaghanyagunavrittistha adho gachchhanti tamasahan.', en: 'The sattvic rise upward, the rajasic stay in the middle, and the tamasic sink downward.', hi: 'सत्त्व में स्थित ऊपर जाते हैं, राजस बीच में रहते हैं, और तामस अधोगति पाते हैं।'},
  {n: 19, speaker: 'krishna', sa: 'नान्यं गुणेभ्यः कर्तारं यदा द्रष्टानुपश्यति। गुणेभ्यश्च परं वेत्ति मद्भावं सोऽधिगच्छति॥', tr: 'Nanyam gunebhyah kartaram yada drashtanupashyati, gunebhyashcha param vetti madbhavam soadhigachchhati.', en: 'Seeing no doer but the gunas, and knowing what lies beyond them, one reaches my being.', hi: 'गुणों के सिवा अन्य कर्ता न देखकर और उनसे परे जानकर साधक मेरे भाव को पाता है।'},
  {n: 20, speaker: 'krishna', sa: 'गुणानेतानतीत्य त्रीन्देही देहसमुद्भवान्। जन्ममृत्युजरादुःखैर्विमुक्तोऽमृतमश्नुते॥', tr: 'Gunanetanatitya trindehi dehasamudbhavan, janmamrityujaraduhkhairvimuktoamritamashnute.', en: 'Rising above these three gunas born of the body, one is freed from birth, death, age and pain into deathlessness.', hi: 'देह से उत्पन्न इन तीन गुणों से ऊपर उठकर जीव जन्म-मृत्यु-जरा-दुःख से मुक्त हो अमृत पाता है।'},
  {n: 21, speaker: 'arjuna', sa: 'कैर्लिङ्गैस्त्रीन्गुणानेतानतीतो भवति प्रभो। किमाचारः कथं चैतांस्त्रीन्गुणानतिवर्तते॥', tr: 'Kairlingaistringunanetanatito bhavati prabho, kimacharah katham chaitanstringunanativartate.', en: 'By what marks is one beyond the three gunas, Lord — how does he act, and how does he rise past them?', hi: 'हे प्रभो! तीन गुणों से अतीत व्यक्ति के क्या लक्षण हैं, उसका आचरण कैसा है, और वह इन्हें कैसे पार करता है?'},
  {n: 22, speaker: 'krishna', sa: 'प्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव। न द्वेष्टि सम्प्रवृत्तानि न निवृत्तानि काङ्क्षति॥', tr: 'Prakasham cha pravrittim cha mohameva cha Pandava, na dveshti sampravrittani na nivrittani kankshati.', en: 'He neither hates clarity, restlessness or delusion when they come, nor longs for them when they leave, Pandava.', hi: 'हे पांडव! प्रकाश, प्रवृत्ति और मोह आने पर वह द्वेष नहीं करता और जाने पर इच्छा नहीं करता।'},
  {n: 23, speaker: 'krishna', sa: 'उदासीनवदासीनो गुणैर्यो न विचाल्यते। गुणा वर्तन्त इत्येव योऽवतिष्ठति नेङ्गते॥', tr: 'Udasinavad asino gunairyo na vichalyate, guna vartanta ityeva yoavatishthati nengate.', en: 'Seated like a witness, unshaken by the gunas, he rests knowing it is only the gunas at play.', hi: 'उदासीन की भाँति स्थित वह गुणों से विचलित नहीं होता और गुण ही बरत रहे हैं जानकर स्थिर रहता है।'},
  {n: 24, speaker: 'krishna', sa: 'समदुःखसुखः स्वस्थः समलोष्टाश्मकाञ्चनः। तुल्यप्रियाप्रियो धीरस्तुल्यनिन्दात्मसंस्तुतिः॥', tr: 'Samaduhkhasukhah svasthah samaloshtashmakachanahan, tulyapriyapriyo dhirastulyanindatmasamstutih.', en: 'Steady in joy and sorrow, seeing clod, stone and gold alike, the wise one treats praise and blame the same.', hi: 'सुख-दुःख में सम, स्वस्थ, मिट्टी-पत्थर-सोने को समान देखने वाला धीर प्रिय-अप्रिय और निंदा-स्तुति में तुल्य रहता है।'},
  {n: 25, speaker: 'krishna', sa: 'मानापमानयोस्तुल्यस्तुल्यो मित्रारिपक्षयोः। सर्वारम्भपरित्यागी गुणातीतः स उच्यते॥', tr: 'Manapamanayostulyastulyo mitraripakshayoh, sarvarambhaparityagi gunatitah sa uchyate.', en: 'Equal in honour and insult, equal toward friend and foe, free of restless striving — such one is beyond the gunas.', hi: 'मान-अपमान में सम, मित्र-शत्रु में सम, सब आरंभों का त्यागी — वही गुणातीत कहा जाता है।'},
  {n: 26, speaker: 'krishna', sa: 'मां च योऽव्यभिचारेण भक्तियोगेन सेवते। स गुणान्समतीत्यैतान्ब्रह्मभूयाय कल्पते॥', tr: 'Mam cha yoavyabhicharena bhaktiyogena sevate, sa gunansamatityaitanbrahmabhuyaya kalpate.', en: 'One who serves me with steady, single-hearted devotion rises past the gunas into oneness with Brahman.', hi: 'जो अनन्य भक्तियोग से मेरी सेवा करता है, वह गुणों को पार कर ब्रह्मभाव के योग्य होता है।'},
  {n: 27, speaker: 'krishna', sa: 'ब्रह्मणो हि प्रतिष्ठाहममृतस्याव्ययस्य च। शाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च॥', tr: 'Brahmano hi pratishthahamamritasyavyayasya cha, shashvatasya cha dharmasya sukhasyaikantikasya cha.', en: 'For I am the ground of Brahman, of deathless eternity, of lasting dharma and of perfect bliss.', hi: 'मैं ही अविनाशी अमृत ब्रह्म, शाश्वत धर्म और एकांतिक सुख की प्रतिष्ठा हूँ।'}
];
