import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter8Meta: GitaChapterDetail = {
  n: 8,
  title: {en: 'Chapter 8 · Akshara Brahma Yoga', hi: 'अध्याय 8 · अक्षर ब्रह्म योग'},
  summary: {
    en: 'The imperishable Absolute, cosmic cycles, and remembrance at the final hour. 28 verses.',
    hi: 'अक्षर ब्रह्म, सृष्टि-चक्र और अंतिम क्षण में स्मरण। 28 श्लोक।'
  }
};

export const chapter8Verses: GitaVerse[] = [
  {n: 1, speaker: 'arjuna', sa: 'किं तद्ब्रह्म किमध्यात्मं किं कर्म पुरुषोत्तम। अधिभूतं च किं प्रोक्तमधिदैवं किमुच्यते॥', tr: 'Kim tadbrahma kimadhyatmam kim karma Purushottama, adhibhutam cha kim proktamadhidaivam kimuchyate.', en: 'What is the Absolute, what is the inner Self, what is action — and what are the earthly and divine orders, O supreme Person?', hi: 'हे पुरुषोत्तम! ब्रह्म क्या है, अध्यात्म क्या है, कर्म क्या है — और अधिभूत तथा अधिदैव किसे कहते हैं?'},
  {n: 2, speaker: 'arjuna', sa: 'अधियज्ञः कथं कोऽत्र देहेऽस्मिन्मधुसूदन। प्रयाणकाले च कथं ज्ञेयोऽसि नियतात्मभिः॥', tr: 'Adhiyajnah katham koatra deheasminmadhusudana, prayanakale cha katham jneyoasi niyatatmabhih.', en: 'Who is the lord of sacrifice in this body, Madhusudana, and how are you known at the final hour by the self-controlled?', hi: 'हे मधुसूदन! इस देह में अधियज्ञ कौन है, और संयमी जन प्रयाणकाल में आपको कैसे जानते हैं?'},
  {n: 3, speaker: 'krishna', sa: 'अक्षरं ब्रह्म परमं स्वभावोऽध्यात्ममुच्यते। भूतभावोद्भवकरो विसर्गः कर्मसंज्ञितः॥', tr: 'Aksharam brahma paramam svabhavoadhyatmamuchyate, bhutabhavodbhavakaro visargah karmasamjnitah.', en: 'The imperishable is the supreme Absolute; one’s own nature is the inner Self; the creative offering is called action.', hi: 'अक्षर ही परम ब्रह्म है, स्वभाव अध्यात्म कहलाता है, और भूतों की उत्पत्ति करने वाला विसर्ग कर्म है।'},
  {n: 4, speaker: 'krishna', sa: 'अधिभूतं क्षरो भावः पुरुषश्चाधिदैवतम्। अधियज्ञोऽहमेवात्र देहे देहभृतां वर॥', tr: 'Adhibhutam ksharo bhavah purushashchadhidaivatam, adhiyajnoahamevatra dehe dehabhritam vara.', en: 'The passing world is the earthly order, the cosmic person the divine — and I myself am sacrifice here in the body, O noblest.', hi: 'नाशवान भाव अधिभूत है, पुरुष अधिदैव है, और हे देहधारियों में श्रेष्ठ! इस देह में अधियज्ञ मैं ही हूँ।'},
  {n: 5, speaker: 'krishna', sa: 'अन्तकाले च मामेव स्मरन्मुक्त्वा कलेवरम्। यः प्रयाति स मद्भावं याति नास्त्यत्र संशयः॥', tr: 'Antakale cha mameva smaranmuktva kalevaram, yah prayati sa madbhavam yati nastyatra samshayah.', en: 'Whoever leaves the body remembering me at the final hour reaches my state — of this there is no doubt.', hi: 'अंतकाल में मेरा स्मरण करते हुए जो देह छोड़कर जाता है, वह मेरे भाव को पाता है — इसमें संशय नहीं।'},
  {n: 6, speaker: 'krishna', sa: 'यं यं वापि स्मरन्भावं त्यजत्यन्ते कलेवरम्। तं तमेवैति कौन्तेय सदा तद्भावभावितः॥', tr: 'Yam yam vapi smaranbhavam tyajatyante kalevaram, tam tamevaiti Kaunteya sada tadbhavabhavitah.', en: 'Whatever state one recalls at the end, that alone one attains, Kaunteya, steeped in its constant thought.', hi: 'हे कौन्तेय! अंत में जिस भाव का स्मरण करते हुए देह छोड़ी जाती है, उसी को प्राप्त होता है।'},
  {n: 7, speaker: 'krishna', sa: 'तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च। मय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयम्॥', tr: 'Tasmatsarveshu kaleshu mamanusmara yudhya cha, mayyarpitamanobuddhirmamevaishyasyasamshayam.', en: 'So remember me at all times, and fight — with mind and reason surrendered to me, you shall reach me.', hi: 'अतः सदा मेरा स्मरण करो और युद्ध करो — मन-बुद्धि मुझे अर्पित कर तुम निस्संदेह मुझे पाओगे।'},
  {n: 8, speaker: 'krishna', sa: 'अभ्यासयोगयुक्तेन चेतसा नान्यगामिना। परमं पुरुषं दिव्यं याति पार्थानुचिन्तयन्॥', tr: 'Abhyasayogayuktena chetasa nanyagamina, paramam purusham divyam yati parthanuchintayan.', en: 'With a mind trained by practice and wandering nowhere else, one reaches the supreme divine Person, Partha.', hi: 'हे पार्थ! अभ्यासयोग से युक्त, अन्यत्र न भटकने वाले चित्त से ध्यान करता हुआ परम दिव्य पुरुष को पाता है।'},
  {n: 9, speaker: 'krishna', sa: 'कविं पुराणमनुशासितारमणोरणीयांसमनुस्मरेद्यः। सर्वस्य धातारमचिन्त्यरूपमादित्यवर्णं तमसः परस्तात्॥', tr: 'Kavim puranamanushasitaramanoraniyamsamanusmaredyah, sarvasya dhataramachintyarupamadityavarnam tamasah parastat.', en: 'Meditate on the seer, ancient ruler, subtler than the subtle — sustainer of all, radiant as the sun beyond darkness.', hi: 'जो कवि, पुराण, नियंता, अणु से भी सूक्ष्म, सबके धाता, अचिंत्य रूप, सूर्यवर्ण, अंधकार से परे का स्मरण करे।'},
  {n: 10, speaker: 'krishna', sa: 'प्रयाणकाले मनसाचलेन भक्त्या युक्तो योगबलेन चैव। भ्रुवोर्मध्ये प्राणमावेश्य सम्यक् स तं परं पुरुषमुपैति दिव्यम्॥', tr: 'Prayanakale manasachalena bhaktya yukto yogabalena chaiva, bhruvormadhye pranmaveshya samyak sa tam param purushamupaiti divyam.', en: 'At departure, with steady mind, devotion, and yogic strength, gathering breath between the brows, one reaches that supreme Person.', hi: 'प्रयाणकाल में अचल मन, भक्ति और योगबल से भ्रूमध्य में प्राण स्थापित कर वह परम दिव्य पुरुष को पाता है।'},
  {n: 11, speaker: 'krishna', sa: 'यदक्षरं वेदविदो वदन्ति विशन्ति यद्यतयो वीतरागाः। यदिच्छन्तो ब्रह्मचर्यं चरन्ति तत्ते पदं सङ्ग्रहेण प्रवक्ष्ये॥', tr: 'Yadaksharam vedavido vadanti vishanti yadyatayo vitaragah, yadichchhanto brahmacharyam charanti tatte padam sangrahena pravakshye.', en: 'The imperishable the Veda-knowers proclaim, which the passion-free enter — I will tell you that goal in brief.', hi: 'जिस अक्षर को वेदज्ञ कहते हैं, जिसमें वीतराग यति प्रवेश करते हैं, उसकी इच्छा से ब्रह्मचर्य चरते हैं — वह पद संक्षेप में बताता हूँ।'},
  {n: 12, speaker: 'krishna', sa: 'सर्वद्वाराणि संयम्य मनो हृदि निरुध्य च। मूर्ध्न्याधायात्मनः प्राणमास्थितो योगधारणाम्॥', tr: 'Sarvadvarani samyamya mano hridi nirudhya cha, murdhnyadhayatmanah pranamasthito yogadharanam.', en: 'Closing all the gates, holding mind within the heart, fixing breath at the crown, firm in yogic poise.', hi: 'समस्त द्वारों को रोककर, मन को हृदय में निरुद्ध कर, प्राण को मस्तक में स्थापित कर योगधारणा में स्थित हो।'},
  {n: 13, speaker: 'krishna', sa: 'ओमित्येकाक्षरं ब्रह्म व्याहरन्मामनुस्मरन्। यः प्रयाति त्यजन्देहं स याति परमां गतिम्॥', tr: 'Omityekaksharam brahma vyaharanmamanusmaran, yah prayati tyajandeham sa yati paramam gatim.', en: 'Uttering the single syllable Om — the Absolute — remembering me as he departs, he reaches the highest goal.', hi: '‘ॐ’ इस एकाक्षर ब्रह्म का उच्चारण करते हुए मेरा स्मरण कर जो देह छोड़ता है, वह परम गति पाता है।'},
  {n: 14, speaker: 'krishna', sa: 'अनन्यचेताः सततं यो मां स्मरति नित्यशः। तस्याहं सुलभः पार्थ नित्ययुक्तस्य योगिनः॥', tr: 'Ananyachetah satatam yo mam smarati nityashah, tasyaham sulabhah Partha nityayuktasya yoginah.', en: 'To one who remembers me constantly with undivided heart, I am easily reached, Partha, ever-yoked yogi.', hi: 'हे पार्थ! अनन्यचित्त से नित्य मेरा स्मरण करने वाले युक्त योगी को मैं सुलभ हूँ।'},
  {n: 15, speaker: 'krishna', sa: 'मामुपेत्य पुनर्जन्म दुःखालयमशाश्वतम्। नाप्नुवन्ति महात्मानः संसिद्धिं परमां गताः॥', tr: 'Mamupetya punarjanma duhkhalayamashashvatam, napnuvanti mahatmanah samsiddhim paramam gatah.', en: 'Reaching me, great souls return no more to rebirth — that fleeting house of sorrow — attaining highest perfection.', hi: 'मुझे पाकर महात्मा दुःखालय अशाश्वत पुनर्जन्म को नहीं पाते — परम सिद्धि को प्राप्त होते हैं।'},
  {n: 16, speaker: 'krishna', sa: 'आब्रह्मभुवनाल्लोकाः पुनरावर्तिनोऽर्जुन। मामुपेत्य तु कौन्तेय पुनर्जन्म न विद्यते॥', tr: 'Abrahmabhuvanallokah punaravartinoarjuna, mamupetya tu Kaunteya punarjanma na vidyate.', en: 'All worlds up to Brahma’s realm return again, Arjuna — but reaching me, Kaunteya, there is no rebirth.', hi: 'हे अर्जुन! ब्रह्मलोक तक सभी लोक पुनरावर्ती हैं — पर मुझे पाकर, हे कौन्तेय, पुनर्जन्म नहीं होता।'},
  {n: 17, speaker: 'krishna', sa: 'सहस्रयुगपर्यन्तमहर्यद्ब्रह्मणो विदुः। रात्रिं युगसहस्रान्तां तेऽहोरात्रविदो जनाः॥', tr: 'Sahasrayugaparyantamaharyadbrahmano viduh, ratrim yugasahasrantam teahoratravido janah.', en: 'Those who know a day of Brahma spans a thousand ages, and so his night, know day and night indeed.', hi: 'जो ब्रह्मा का दिन हजार युगों का और रात्रि भी वैसी ही जानते हैं, वे ही अहोरात्र के ज्ञाता हैं।'},
  {n: 18, speaker: 'krishna', sa: 'अव्यक्ताद्व्यक्तयः सर्वाः प्रभवन्त्यहरागमे। रात्र्यागमे प्रलीयन्ते तत्रैवाव्यक्तसंज्ञके॥', tr: 'Avyaktadvyaktayah sarvah prabhavantyaharagame, ratryagame praliyante tatraivavyaktasamjnake.', en: 'From the unmanifest all forms emerge at daybreak, and at nightfall dissolve back into it.', hi: 'दिन के आगमन पर अव्यक्त से समस्त व्यक्त उत्पन्न होते हैं, रात्रि आने पर उसी अव्यक्त में लीन हो जाते हैं।'},
  {n: 19, speaker: 'krishna', sa: 'भूतग्रामः स एवायं भूत्वा भूत्वा प्रलीयते। रात्र्यागमेऽवशः पार्थ प्रभवत्यहरागमे॥', tr: 'Bhutagramah sa evayam bhutva bhutva praliyate, ratryagameavashah Partha prabhavatyaharagame.', en: 'This same host of beings, helpless, dissolves and rises again with night and day, Partha.', hi: 'हे पार्थ! यही भूतसमूह बार-बार उत्पन्न होकर लीन होता है — रात्रि में लय, दिन में उत्पत्ति, परवश होकर।'},
  {n: 20, speaker: 'krishna', sa: 'परस्तस्मात्तु भावोऽन्योऽव्यक्तोऽव्यक्तात्सनातनः। यः स सर्वेषु भूतेषु नश्यत्सु न विनश्यति॥', tr: 'Parastasmattu bhavoanyoavyaktoavyaktatsanatanah, yah sa sarveshu bhuteshu nashyatsu na vinashyati.', en: 'Beyond that unmanifest lies another, eternal — which perishes not when all beings perish.', hi: 'उस अव्यक्त से परे एक अन्य सनातन अव्यक्त भाव है — जो समस्त भूतों के नाश होने पर भी नष्ट नहीं होता।'},
  {n: 21, speaker: 'krishna', sa: 'अव्यक्तोऽक्षर इत्युक्तस्तमाहुः परमां गतिम्। यं प्राप्य न निवर्तन्ते तद्धाम परमं मम॥', tr: 'Avyaktoakshara ityuktastamahuh paramam gatim, yam prapya na nivartante taddhama paramam mama.', en: 'Called the unmanifest imperishable, the highest goal — reaching it none return; that is my supreme abode.', hi: 'उसे अव्यक्त अक्षर कहते हैं, वही परम गति है — जिसे पाकर लौटना नहीं होता; वही मेरा परम धाम है।'},
  {n: 22, speaker: 'krishna', sa: 'पुरुषः स परः पार्थ भक्त्या लभ्यस्त्वनन्यया। यस्यान्तःस्थानि भूतानि येन सर्वमिदं ततम्॥', tr: 'Purushah sa parah Partha bhaktya labhyastvananyaya, yasyantahsthani bhutani yena sarvamidam tatam.', en: 'That supreme Person, Partha, is reached by single devotion — within whom all beings dwell, by whom all is pervaded.', hi: 'हे पार्थ! वह परम पुरुष अनन्य भक्ति से प्राप्त होता है — जिसके भीतर समस्त भूत हैं, जिससे यह सब व्याप्त है।'},
  {n: 23, speaker: 'krishna', sa: 'यत्र काले त्वनावृत्तिमावृत्तिं चैव योगिनः। प्रयाता यान्ति तं कालं वक्ष्यामि भरतर्षभ॥', tr: 'Yatra kale tvanavrittimavrittim chaiva yoginah, prayata yanti tam kalam vakshyami Bharatarshabha.', en: 'Now I tell you, best of Bharatas, the times when departing yogis return — or return no more.', hi: 'हे भरतश्रेष्ठ! जिस काल में प्रयाण कर योगी अनावृत्ति या आवृत्ति पाते हैं, वह काल बताता हूँ।'},
  {n: 24, speaker: 'krishna', sa: 'अग्निर्ज्योतिरहः शुक्लः षण्मासा उत्तरायणम्। तत्र प्रयाता गच्छन्ति ब्रह्म ब्रह्मविदो जनाः॥', tr: 'Agnirjyotirahah shuklah shanmasa uttarayanam, tatra prayata gachchhanti brahma brahmavido janah.', en: 'Fire, light, day, the bright fortnight, the northern six months — departing then, knowers of Brahman reach Brahman.', hi: 'अग्नि, ज्योति, दिन, शुक्लपक्ष, उत्तरायण के छह मास — इनमें प्रयाण कर ब्रह्मज्ञानी ब्रह्म को पाते हैं।'},
  {n: 25, speaker: 'krishna', sa: 'धूमो रात्रिस्तथा कृष्णः षण्मासा दक्षिणायनम्। तत्र चान्द्रमसं ज्योतिर्योगी प्राप्य निवर्तते॥', tr: 'Dhumo ratristatha krishnah shanmasa dakshinayanam, tatra chandramasam jyotiryogi prapya nivartate.', en: 'Smoke, night, the dark fortnight, the southern six months — the yogi reaches lunar light and returns.', hi: 'धूम, रात्रि, कृष्णपक्ष, दक्षिणायन के छह मास — इनमें योगी चंद्रज्योति पाकर लौट आता है।'},
  {n: 26, speaker: 'krishna', sa: 'शुक्लकृष्णे गती ह्येते जगतः शाश्वते मते। एकया यात्यनावृत्तिमन्ययावर्तते पुनः॥', tr: 'Shuklakrishne gati hyete jagatah shashvate mate, ekaya yatyanavrittimanyayavartate punah.', en: 'Bright and dark — these two paths of the world are deemed eternal; by one none return, by the other they return.', hi: 'शुक्ल और कृष्ण — जगत की ये दो गतियाँ शाश्वत मानी गईं; एक से अनावृत्ति, दूसरी से पुनरावृत्ति होती है।'},
  {n: 27, speaker: 'krishna', sa: 'नैते सृती पार्थ जानन्योगी मुह्यति कश्चन। तस्मात्सर्वेषु कालेषु योगयुक्तो भवार्जुन॥', tr: 'Naite sriti Partha jananyogi muhyati kashchana, tasmatsarveshu kaleshu yogayukto bhavarjuna.', en: 'Knowing these two paths, no yogi is bewildered, Partha — so stay ever yoked in yoga, Arjuna.', hi: 'हे पार्थ! इन दोनों मार्गों को जानकर कोई योगी मोहित नहीं होता — अतः सदा योगयुक्त होओ, अर्जुन।'},
  {n: 28, speaker: 'krishna', sa: 'वेदेषु यज्ञेषु तपःसु चैव दानेषु यत्पुण्यफलं प्रदिष्टम्। अत्येति तत्सर्वमिदं विदित्वा योगी परं स्थानमुपैति चाद्यम्॥', tr: 'Vedeshu yajneshu tapahsu chaiva daneshu yatpunyaphalam pradishtam, atyeti tatsarvamidam viditva yogi param sthanamupaiti chadyam.', en: 'Whatever merit lies in Vedas, rites, austerities and gifts — the yogi who knows this passes beyond all and reaches the primal supreme seat.', hi: 'वेद, यज्ञ, तप और दान में जो पुण्यफल कहा गया है, उसे जानकर योगी सबसे आगे बढ़कर परम आद्य स्थान पाता है।'}
];
