import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter16Meta: GitaChapterDetail = {
  n: 16,
  title: {en: 'Chapter 16 · Daivasura Sampad Vibhaga Yoga', hi: 'अध्याय 16 · दैवासुर संपद् विभाग योग'},
  summary: {
    en: 'Divine and demonic qualities — the two paths a life can take. 24 verses.',
    hi: 'दैवी और आसुरी संपदा — जीवन के दो मार्ग। 24 श्लोक।'
  }
};

export const chapter16Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'अभयं सत्त्वसंशुद्धिर्ज्ञानयोगव्यवस्थितिः। दानं दमश्च यज्ञश्च स्वाध्यायस्तप आर्जवम्॥', tr: 'Abhayam sattvasamshuddhirjnanayogavyavasthitih, danam damashcha yajnashcha svadhyayastapa arjavam.', en: 'Fearlessness, a pure heart, steady wisdom, giving, restraint, worship, study, austerity and honesty.', hi: 'अभय, चित्तशुद्धि, ज्ञानयोग में स्थिति, दान, दम, यज्ञ, स्वाध्याय, तप और सरलता।'},
  {n: 2, speaker: 'krishna', sa: 'अहिंसा सत्यमक्रोधस्त्यागः शान्तिरपैशुनम्। दया भूतेष्वलोलुप्त्वं मार्दवं ह्रीरचापलम्॥', tr: 'Ahimsa satyamakrodhastyagah shantirapaishunam, daya bhuteshvaloluptvam mardavam hrirachapalam.', en: 'Non-harming, truth, freedom from anger, letting go, peace, no slander, kindness, no greed, gentleness, modesty and calm.', hi: 'अहिंसा, सत्य, अक्रोध, त्याग, शांति, चुगली न करना, दया, लोभहीनता, कोमलता, लज्जा और चंचलता का अभाव।'},
  {n: 3, speaker: 'krishna', sa: 'तेजः क्षमा धृतिः शौचमद्रोहो नातिमानिता। भवन्ति सम्पदं दैवीमभिजातस्य भारत॥', tr: 'Tejah kshama dhritih shauchamadroho natimanita, bhavanti sampadam daivimabhijatasya Bharata.', en: 'Glow, forgiveness, resolve, cleanliness, no malice and no vanity mark one born to the divine path, Bharata.', hi: 'तेज, क्षमा, धैर्य, पवित्रता, अद्रोह और निरभिमानता — ये दैवी संपदा लेकर जन्मे के लक्षण हैं, भारत।'},
  {n: 4, speaker: 'krishna', sa: 'दम्भो दर्पोऽभिमानश्च क्रोधः पारुष्यमेव च। अज्ञानं चाभिजातस्य पार्थ सम्पदमासुरीम्॥', tr: 'Dambho darpoabhimanashcha krodhah parushyameva cha, ajnanam chabhijatasya Partha sampadamasurim.', en: 'Show, arrogance, conceit, anger, harshness and ignorance mark one born to the demonic path, Partha.', hi: 'दम्भ, घमंड, अभिमान, क्रोध, कठोरता और अज्ञान — ये आसुरी संपदा लेकर जन्मे के लक्षण हैं, पार्थ।'},
  {n: 5, speaker: 'krishna', sa: 'दैवी सम्पद्विमोक्षाय निबन्धायासुरी मता। मा शुचः सम्पदं दैवीमभिजातोऽसि पाण्डव॥', tr: 'Daivi sampadvimokshaya nibandhayasuri mata, ma shuchah sampadam daivimabhijatoasi Pandava.', en: 'The divine path frees, the demonic binds — but grieve not, Pandava, for you are born to the divine.', hi: 'दैवी संपदा मोक्ष के लिए और आसुरी बंधन के लिए मानी गई — शोक न करो, पांडव, तुम दैवी संपदा वाले हो।'},
  {n: 6, speaker: 'krishna', sa: 'द्वौ भूतसर्गौ लोकेऽस्मिन्दैव आसुर एव च। दैवो विस्तरशः प्रोक्त आसुरं पार्थ मे शृणु॥', tr: 'Dvau bhutasargau lokeasmindaiva asura eva cha, daivo vistarashah prokta asuram Partha me shrinu.', en: 'Two kinds of beings fill this world — the divine and the demonic — and now hear of the demonic, Partha.', hi: 'इस लोक में दो प्रकार की सृष्टि है — दैवी और आसुरी; दैवी विस्तार से कही, अब आसुरी मुझसे सुनो, पार्थ।'},
  {n: 7, speaker: 'krishna', sa: 'प्रवृत्तिं च निवृत्तिं च जना न विदुरासुराः। न शौचं नापि चाचारो न सत्यं तेषु विद्यते॥', tr: 'Pravrittim cha nivrittim cha jana na vidurasurahan, na shaucham napi chacharo na satyam teshu vidyate.', en: 'The demonic know neither right action nor restraint, and have no purity, conduct or truth.', hi: 'आसुरी लोग न प्रवृत्ति जानते हैं न निवृत्ति; उनमें न पवित्रता, न आचरण, न सत्य होता है।'},
  {n: 8, speaker: 'krishna', sa: 'असत्यमप्रतिष्ठं ते जगदाहुरनीश्वरम्। अपरस्परसम्भूतं किमन्यत्कामहैतुकम्॥', tr: 'Asatyamapratishtham te jagadahuranishvaram, parasparasambhutam kimanyatkamahaitukam.', en: 'They call the world baseless, godless, born of chance — nothing but desire, they say.', hi: 'वे जगत को असत्य, आधारहीन और ईश्वररहित कहते हैं — केवल काम से उत्पन्न, इसके सिवा क्या है।'},
  {n: 9, speaker: 'krishna', sa: 'एतां दृष्टिमवष्टभ्य नष्टात्मानोऽल्पबुद्धयः। प्रभवन्त्युग्रकर्माणः क्षयाय जगतोऽहिताः॥', tr: 'Etam drishtimavashtabhya nashtatmanoalpabuddhayah, prabhavantyugrakarmanah kshayaya jagatoahitahan.', en: 'Clinging to this view, lost souls of narrow mind turn cruel and work toward the ruin of the world.', hi: 'इस दृष्टि को पकड़कर भ्रष्टचित्त अल्पबुद्धि उग्रकर्मी जगत के नाश हेतु उत्पन्न होते हैं।'},
  {n: 10, speaker: 'krishna', sa: 'काममाश्रित्य दुष्पूरं दम्भमानमदान्विताः। मोहाद्गृहीत्वासद्ग्राहान्प्रवर्तन्तेऽशुचिव्रताः॥', tr: 'Kamamashritya dushpuram dambhamanamadanvitahan, mohadgrihitvasadgrahanpravartanteashuchivratahan.', en: 'Driven by endless craving, puffed with show and pride, they chase foul vows born of delusion.', hi: 'कभी न पूरी होने वाली कामना के आश्रित, दम्भ-मान-मद से युक्त, मोहवश झूठे सिद्धांत पकड़कर अपवित्र व्रतों में लगते हैं।'},
  {n: 11, speaker: 'krishna', sa: 'चिन्तामपरिमेयां च प्रलयान्तामुपाश्रिताः। कामोपभोगपरमा एतावदिति निश्चिताः॥', tr: 'Chintamaparimeyam cha pralayantamupashritahan, kamopabhogaparama etavaditi nishchitahan.', en: 'Tormented by endless worry till death, they hold pleasure as the highest goal and nothing more.', hi: 'मृत्यु तक अपार चिंता में डूबे, कामभोग को ही परम मानकर वे इसी को सब कुछ निश्चय करते हैं।'},
  {n: 12, speaker: 'krishna', sa: 'आशापाशशतैर्बद्धाः कामक्रोधपरायणाः। ईहन्ते कामभोगार्थमन्यायेनार्थसञ्चयान्॥', tr: 'Ashapashashatairbaddhahan kamakrodhaparayanahan, ihante kamabhogarthamanyayenarthasanchayan.', en: 'Snared by a hundred cords of hope, ruled by lust and rage, they hoard wealth by foul means for pleasure.', hi: 'सैकड़ों आशा-पाशों से बँधे, काम-क्रोध में लीन, वे भोग हेतु अन्याय से धन जोड़ना चाहते हैं।'},
  {n: 13, speaker: 'krishna', sa: 'इदमद्य मया लब्धमिमं प्राप्स्ये मनोरथम्। इदमस्तीदमपि मे भविष्यति पुनर्धनम्॥', tr: 'Idamadya maya labdhamimam prapsye manoratham, idamastidamapi me bhavishyati punardhanam.', en: 'Today I gained this, tomorrow I will gain that wish — this wealth is mine, and more will soon be mine.', hi: 'आज यह पाया, कल वह मनोरथ पाऊँगा — यह धन मेरा है, फिर यह भी मेरा होगा।'},
  {n: 14, speaker: 'krishna', sa: 'असौ मया हतः शत्रुर्हनिष्ये चापरानपि। ईश्वरोऽहमहं भोगी सिद्धोऽहं बलवान्सुखी॥', tr: 'Asau maya hatah shatrurhanishye chaparanapi, ishvaroahamaham bhogi siddhoaham balavansukhi.', en: 'That foe I slew, and others I will slay — I am lord, enjoyer, perfect, strong and happy.', hi: 'वह शत्रु मैंने मारा, औरों को भी मारूँगा — मैं ईश्वर हूँ, भोगी हूँ, सिद्ध, बलवान और सुखी हूँ।'},
  {n: 15, speaker: 'krishna', sa: 'आढ्योऽभिजनवानस्मि कोऽन्योऽस्ति सदृशो मया। यक्ष्ये दास्यामि मोदिष्य इत्यज्ञानविमोहिताः॥', tr: 'Adhyoabhijanavanasmi koanyoasti sadrisho maya, yakshye dasyami modishya ityajnanavimohitahan.', en: 'Rich and high-born am I — who equals me? I will feast, give and rejoice — so think the deluded.', hi: 'धनी और कुलीन हूँ, मेरे समान कौन है? यज्ञ करूँगा, दूँगा, मौज करूँगा — ऐसा अज्ञान से मोहित होकर कहते हैं।'},
  {n: 16, speaker: 'krishna', sa: 'अनेकचित्तविभ्रान्ता मोहजालसमावृताः। प्रसक्ताः कामभोगेषु पतन्ति नरकेऽशुचौ॥', tr: 'Anekachittavibhranta mohajalasamavritahan, prasaktah kamabhogeshu patanti narakeashuchau.', en: 'Lost in scattered thoughts, tangled in delusion, chained to pleasure, they fall into foul hell.', hi: 'अनेक विचारों से भ्रमित, मोहजाल में फँसे, कामभोगों में आसक्त वे अपवित्र नरक में गिरते हैं।'},
  {n: 17, speaker: 'krishna', sa: 'आत्मसम्भाविताः स्तब्धा धनमानमदान्विताः। यजन्ते नामयज्ञैस्ते दम्भेनाविधिपूर्वकम्॥', tr: 'Atmasambhavitahan stabdha dhanamanamadanvitahan, yajante namayajnaiste dambhenavidhipurvakam.', en: 'Proud, stiff with wealth and honour, they perform mere show-sacrifices against all true rule.', hi: 'अपने को बड़ा मानने वाले, हठी, धन-मान-मद से युक्त वे दम्भ से विधिरहित नाममात्र के यज्ञ करते हैं।'},
  {n: 18, speaker: 'krishna', sa: 'अहङ्कारं बलं दर्पं कामं क्रोधं च संश्रिताः। मामात्मपरदेहेषु प्रद्विषन्तोऽभ्यसूयकाः॥', tr: 'Ahankaram balam darpam kamam krodham cha samshritahan, mamatmaparadeheshu pradvishtoabhyasuyakahan.', en: 'Clinging to ego, force, pride, lust and anger, they hate me dwelling in themselves and in others.', hi: 'अहंकार, बल, घमंड, काम और क्रोध के आश्रित वे अपने-पराए देहों में स्थित मुझसे द्वेष करते हैं।'},
  {n: 19, speaker: 'krishna', sa: 'तानहं द्विषतः क्रूरान्संसारेषु नराधमान्। क्षिपाम्यजस्रमशुभानासुरीष्वेव योनिषु॥', tr: 'Tanaham dvishtah kruransamsareshu naradhaman, kshipamyajasramashubhanasurishveva yonishu.', en: 'Those cruel haters, lowest of humans, I cast again and again into demonic wombs.', hi: 'उन द्वेषी, क्रूर, अशुभ नराधमों को मैं बार-बार संसार में आसुरी योनियों में डालता हूँ।'},
  {n: 20, speaker: 'krishna', sa: 'आसुरीं योनिमापन्ना मूढा जन्मनि जन्मनि। मामप्राप्यैव कौन्तेय ततो यान्त्यधमां गतिम्॥', tr: 'Asurim yonimapanna mudha janmani janmani, mamaprapyaiva Kaunteya tato yantyadhamam gatim.', en: 'Born birth after birth into deluded wombs, never reaching me, they sink to the lowest state, Kaunteya.', hi: 'आसुरी योनि पाकर मूढ़ जन्म-जन्म में मुझ तक न पहुँचकर अधम गति को पाते हैं, कौंतेय।'},
  {n: 21, speaker: 'krishna', sa: 'त्रिविधं नरकस्येदं द्वारं नाशनमात्मनः। कामः क्रोधस्तथा लोभस्तस्मादेतत्त्रयं त्यजेत्॥', tr: 'Trividham narakasyedam dvaram nashanamatmanah, kamah krodhastatha lobhastasmadetattrayam tyajet.', en: 'Three gates open into hell and ruin the soul — lust, anger and greed — so shun all three.', hi: 'नरक के तीन द्वार आत्मा का नाश करते हैं — काम, क्रोध और लोभ; अतः इन तीनों को त्यागे।'},
  {n: 22, speaker: 'krishna', sa: 'एतैर्विमुक्तः कौन्तेय तमोद्वारैस्त्रिभिर्नरः। आचरत्यात्मनः श्रेयस्ततो याति परां गतिम्॥', tr: 'Etairvimuktah Kaunteya tamodvaraistribhirnarah, acharatyatmanah shreyastato yati param gatim.', en: 'Freed from these three dark gates, Kaunteya, one walks toward the good and reaches the highest goal.', hi: 'इन तीन तम-द्वारों से मुक्त होकर मनुष्य अपना कल्याण करता है और परम गति पाता है, कौंतेय।'},
  {n: 23, speaker: 'krishna', sa: 'यः शास्त्रविधिमुत्सृज्य वर्तते कामकारतः। न स सिद्धिमवाप्नोति न सुखं न परां गतिम्॥', tr: 'Yah shastravidhimutsrijya vartate kamakaratah, na sa siddhimavapnoti na sukham na param gatim.', en: 'One who scorns the teaching and follows mere whim finds neither success, joy nor the highest goal.', hi: 'जो शास्त्रविधि छोड़कर मनमानी करता है, उसे न सिद्धि मिलती है, न सुख, न परम गति।'},
  {n: 24, speaker: 'krishna', sa: 'तस्माच्छास्त्रं प्रमाणं ते कार्याकार्यव्यवस्थितौ। ज्ञात्वा शास्त्रविधानोक्तं कर्म कर्तुमिहार्हसि॥', tr: 'Tasmachchhastram pramanam te karyakaryavyavasthitau, jnatva shastravidhanoktam karma kartumiharhasi.', en: 'So let the teaching guide your sense of right and wrong — know its word and act here accordingly.', hi: 'अतः कर्तव्य-अकर्तव्य में शास्त्र ही प्रमाण है — शास्त्रविधि जानकर यहाँ कर्म करने योग्य हो।'}
];
