import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter3Meta: GitaChapterDetail = {
  n: 3,
  title: {en: 'Chapter 3 · Karma Yoga', hi: 'अध्याय 3 · कर्म योग'},
  summary: {
    en: 'The yoga of selfless action — do your duty without selfish desire. 43 verses.',
    hi: 'निष्काम कर्म का योग — फलासक्ति छोड़ कर्तव्य पालन। 43 श्लोक।'
  }
};

export const chapter3Verses: GitaVerse[] = [
  {n: 1, speaker: 'arjuna', sa: 'ज्यायसी चेत्कर्मणस्ते मता बुद्धिर्जनार्दन। तत्किं कर्मणि घोरे मां नियोजयसि केशव॥', tr: 'Jyayasi chetkarmanaste mata buddhirJanardana, tatkim karmani ghore mam niyojayasi Keshava.', en: 'If you hold wisdom higher than action, Janardana, why do you urge me into this dreadful deed, Keshava?', hi: 'यदि कर्म से बुद्धि श्रेष्ठ मानते हो, जनार्दन, तो मुझे इस घोर कर्म में क्यों लगाते हो, केशव?'},
  {n: 2, speaker: 'arjuna', sa: 'व्यामिश्रेणेव वाक्येन बुद्धिं मोहयसीव मे। तदेकं वद निश्चित्य येन श्रेयोऽहमाप्नुयाम्॥', tr: 'Vyamishreneva vakyena buddhim mohayasiva me, tadekam vada nishchitya yena shreyoahamapnuyam.', en: 'Your tangled words confuse my mind — tell me one certain path by which I may reach the good.', hi: 'मिले-जुले वचनों से मेरी बुद्धि मोहित-सी हो रही है — एक निश्चय करके वह कहो जिससे मेरा कल्याण हो।'},
  {n: 3, speaker: 'krishna', sa: 'लोकेऽस्मिन् द्विविधा निष्ठा पुरा प्रोक्ता मयानघ। ज्ञानयोगेन साङ्ख्यानां कर्मयोगेन योगिनाम्॥', tr: 'Lokeasmin dvividha nishtha pura prokta mayanagha, jnanayogena sankhyanam karmayogena yoginam.', en: 'In this world I long ago taught two paths, sinless one — the path of knowledge for the contemplative, and the path of action for the active.', hi: 'हे निष्पाप! इस लोक में दो निष्ठाएँ पहले कही हैं — ज्ञानियों के लिए ज्ञानयोग से, योगियों के लिए कर्मयोग से।'},
  {n: 4, speaker: 'krishna', sa: 'न कर्मणामनारम्भान्नैष्कर्म्यं पुरुषोऽश्नुते। न च संन्यसनादेव सिद्धिं समधिगच्छति॥', tr: 'Na karmanamanarambhannaishkarmyam purushoashnute, na cha sannyasanadeva siddhim samadhigachchhati.', en: 'No one reaches freedom from action by merely avoiding deeds, nor perfection by mere renunciation.', hi: 'कर्मों का आरंभ न करने से नैष्कर्म्य नहीं मिलता, और केवल संन्यास से सिद्धि नहीं मिलती।'},
  {n: 5, speaker: 'krishna', sa: 'न हि कश्चित् क्षणमपि जातु तिष्ठत्यकर्मकृत्। कार्यते ह्यवशः कर्म सर्वैः प्रकृतिजैर्गुणैः॥', tr: 'Na hi kashchit kshanamapi jatu tishthatyakarmakrit, karyate hyavashah karma sarvaih prakritijairgunaih.', en: 'No one can remain actionless even for a moment — everyone is helplessly driven to act by the qualities born of nature.', hi: 'कोई क्षणभर भी कर्म किए बिना नहीं रह सकता — प्रकृति के गुणों से विवश होकर सब कर्म करते हैं।'},
  {n: 6, speaker: 'krishna', sa: 'कर्मेन्द्रियाणि संयम्य य आस्ते मनसा स्मरन्। इन्द्रियार्थान् विमूढात्मा मिथ्याचारः स उच्यते॥', tr: 'Karmendriyani samyamya ya aste manasa smaran, indriyarthan vimudhatma mithyacharah sa uchyate.', en: 'One who restrains the organs of action while mentally dwelling on sense-objects is deluded — a hypocrite.', hi: 'कर्मेंद्रियों को रोककर मन से विषयों का स्मरण करने वाला मूढ़ मिथ्याचारी कहलाता है।'},
  {n: 7, speaker: 'krishna', sa: 'यस्त्विन्द्रियाणि मनसा नियम्यारभतेऽर्जुन। कर्मेन्द्रियैः कर्मयोगमसक्तः स विशिष्यते॥', tr: 'Yastvindriyani manasa niyamyarabhatearjuna, karmendriyaih karmayogamasaktah sa vishishyate.', en: 'But one who controls the senses with the mind, Arjuna, and undertakes selfless action with the organs of action — that one excels.', hi: 'हे अर्जुन! जो मन से इंद्रियों को नियम में रखकर अनासक्त भाव से कर्मेंद्रियों द्वारा कर्मयोग करता है — वही श्रेष्ठ है।'},
  {n: 8, speaker: 'krishna', sa: 'नियतं कुरु कर्म त्वं कर्म ज्यायो ह्यकर्मणः। शरीरयात्रापि च ते न प्रसिद्ध्येदकर्मणः॥', tr: 'Niyatam kuru karma tvam karma jyayo hyakarmanah, sharirayatrapi cha te na prasiddhyedakarmanah.', en: 'Do your allotted duty, for action is better than inaction — without action even the body’s journey cannot go on.', hi: 'नियत कर्म करो, क्योंकि अकर्म से कर्म श्रेष्ठ है — कर्म बिना शरीरनिर्वाह भी सिद्ध नहीं होगा।'},
  {n: 9, speaker: 'krishna', sa: 'यज्ञार्थात् कर्मणोऽन्यत्र लोकोऽयं कर्मबन्धनः। तदर्थं कर्म कौन्तेय मुक्तसङ्गः समाचर॥', tr: 'Yajnarthat karmanoanyatra lokoayam karmabandhanah, tadartham karma Kaunteya muktasangah samachara.', en: 'The world is bound by actions done for selfish ends — so act for the sake of sacrifice, Kaunteya, free from attachment.', hi: 'यज्ञ हेतु कर्म के सिवा यह लोक कर्मबंधन वाला है — हे कौंतेय! आसक्ति छोड़कर यज्ञार्थ कर्म करो।'},
  {n: 10, speaker: 'krishna', sa: 'सहयज्ञाः प्रजाः सृष्ट्वा पुरोवाच प्रजापतिः। अनेन प्रसविष्यध्वमेष वोऽस्त्विष्टकामधुक्॥', tr: 'Sahayajnah prajah srishtva purovacha Prajapatih, anena prasavishyadhvamesha voastvishtakamadhuk.', en: 'Having created mankind together with sacrifice, the Creator said of old — through this you shall prosper; let it grant your cherished desires.', hi: 'यज्ञसहित प्रजा रचकर प्रजापति ने पहले कहा — इससे बढ़ो-फूलो; यह तुम्हारी इच्छित कामनाएँ देने वाली हो।'},
  {n: 11, speaker: 'krishna', sa: 'देवान् भावयतानेन ते देवा भावयन्तु वः। परस्परं भावयन्तः श्रेयः परमवाप्स्यथ॥', tr: 'Devan bhavayatanena te deva bhavayantu vah, parasparam bhavayantah shreyah paramavapsyatha.', en: 'Nourish the gods with sacrifice, and the gods will nourish you — thus cherishing one another, you will reach the highest good.', hi: 'इससे देवों को तृप्त करो, वे देव तुम्हें तृप्त करें — परस्पर पोषण करते हुए परम श्रेय पाओगे।'},
  {n: 12, speaker: 'krishna', sa: 'इष्टान् भोगान् हि वो देवा दास्यन्ते यज्ञभाविताः। तैर्दत्तानप्रदायैभ्यो यो भुङ्क्ते स्तेन एव सः॥', tr: 'Ishtan bhogan hi vo deva dasyante yajnabhavitah, tairdattanapradayaibhyo yo bhunkte stena eva sah.', en: 'The gods, pleased by sacrifice, will grant your desired enjoyments — but one who enjoys their gifts without offering back is a thief.', hi: 'यज्ञ से तृप्त देव तुम्हें इच्छित भोग देंगे — उनके दिए को बिना दिए जो भोगता है, वह चोर ही है।'},
  {n: 13, speaker: 'krishna', sa: 'यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः। भुञ्जते ते त्वघं पापा ये पचन्त्यात्मकारणात्॥', tr: 'Yajnashishtashinah santo muchyante sarvakilbishaih, bhunjate te tvagham papa ye pachantyatmakaranat.', en: 'The good who eat what remains after sacrifice are freed from all sin — but the wicked who cook only for themselves eat sin itself.', hi: 'यज्ञशेष खाने वाले संत सब पापों से छूटते हैं; पर जो केवल अपने लिए पकाते हैं, वे पापी पाप ही खाते हैं।'},
  {n: 14, speaker: 'krishna', sa: 'अन्नाद्भवन्ति भूतानि पर्जन्यादन्नसम्भवः। यज्ञाद्भवति पर्जन्यो यज्ञः कर्मसमुद्भवः॥', tr: 'Annadbhavanti bhutani parjanyadannasambhavah, yajnadbhavati parjanyo yajnah karmasamudbhavah.', en: 'Beings live by food, food grows by rain, rain comes by sacrifice, and sacrifice is born of action.', hi: 'अन्न से प्राणी होते हैं, वर्षा से अन्न; यज्ञ से वर्षा और यज्ञ कर्म से उत्पन्न होता है।'},
  {n: 15, speaker: 'krishna', sa: 'कर्म ब्रह्मोद्भवं विद्धि ब्रह्माक्षरसमुद्भवम्। तस्मात्सर्वगतं ब्रह्म नित्यं यज्ञे प्रतिष्ठितम्॥', tr: 'Karma brahmodbhavam viddhi brahmaksharasamudbhavam, tasmatsarvagatam brahma nityam yajne pratishthitam.', en: 'Know action springs from the Veda, and the Veda from the imperishable — hence the all-pervading Spirit ever rests in sacrifice.', hi: 'कर्म को वेद से और वेद को अक्षर ब्रह्म से उत्पन्न जानो — इसलिए सर्वव्यापी ब्रह्म सदा यज्ञ में स्थित है।'},
  {n: 16, speaker: 'krishna', sa: 'एवं प्रवर्तितं चक्रं नानुवर्तयतीह यः। अघायुरिन्द्रियारामो मोघं पार्थ स जीवति॥', tr: 'Evam pravartitam chakram nanuvartayatiha yah, aghayurindriyaramo mogham Partha sa jivati.', en: 'One who does not turn this wheel here, Partha — living in sin, delighting only in the senses — lives in vain.', hi: 'इस चलाए गए चक्र का जो अनुसरण नहीं करता — वह पापजीवी, इंद्रियाराम, हे पार्थ, व्यर्थ जीता है।'},
  {n: 17, speaker: 'krishna', sa: 'यस्त्वात्मरतिरेव स्यादात्मतृप्तश्च मानवः। आत्मन्येव च सन्तुष्टस्तस्य कार्यं न विद्यते॥', tr: 'Yastvatmaratireva syadatmatriptashcha manavah, atmanyeva cha santushtastasya karyam na vidyate.', en: 'But one who delights in the Self alone, content and satisfied in the Self — for such a person no duty remains.', hi: 'जो आत्मा में ही रत, आत्मा में तृप्त और आत्मा में संतुष्ट है — उसके लिए कोई कर्तव्य नहीं रहता।'},
  {n: 18, speaker: 'krishna', sa: 'नैव तस्य कृतेनार्थो नाकृतेनेह कश्चन। न चास्य सर्वभूतेषु कश्चिदर्थव्यपाश्रयः॥', tr: 'Naiva tasya kritenartho nakriteneha kashchana, na chasya sarvabhuteshu kashchidarthavyapashrayah.', en: 'For such a one there is nothing to gain by acting or by not acting — nor does such a one depend on any being for any need.', hi: 'उसे करने से कोई प्रयोजन नहीं, न करने से भी नहीं — और समस्त प्राणियों में उसका कोई स्वार्थ-आश्रय नहीं।'},
  {n: 19, speaker: 'krishna', sa: 'तस्मादसक्तः सततं कार्यं कर्म समाचर। असक्तो ह्याचरन् कर्म परमाप्नोति पूरुषः॥', tr: 'Tasmadasaktah satatam karyam karma samachara, asakto hyacharan karma paramapnoti purushah.', en: 'So always do your needful duty without attachment — for acting unattached, one reaches the Supreme.', hi: 'अतः अनासक्त होकर सदा कर्तव्य कर्म करो — अनासक्त होकर कर्म करता पुरुष परम को पाता है।'},
  {n: 20, speaker: 'krishna', sa: 'कर्मणैव हि संसिद्धिमास्थिता जनकादयः। लोकसंग्रहमेवापि सम्पश्यन् कर्तुमर्हसि॥', tr: 'Karmanaiva hi samsiddhimasthita Janakadayah, lokasangrahamevapi sampashyan kartumarhasi.', en: 'Janaka and others reached perfection through action alone — keeping the welfare of the world in view, you too should act.', hi: 'जनक आदि कर्म से ही सिद्धि पाए — लोकसंग्रह को देखते हुए भी तुम्हें कर्म करना चाहिए।'},
  {n: 21, speaker: 'krishna', sa: 'यद्यदाचरति श्रेष्ठस्तत्तदेवेतरो जनः। स यत्प्रमाणं कुरुते लोकस्तदनुवर्तते॥', tr: 'Yadyadacharati shreshthastattadevetaro janah, sa yatpramanam kurute lokastadanuvartate.', en: 'Whatever a great person does, ordinary folk follow — whatever standard such a one sets, the world pursues.', hi: 'श्रेष्ठ जो-जो आचरण करता है, अन्य जन वैसा ही करते हैं; वह जो प्रमाण बनाता है, लोक उसका अनुसरण करता है।'},
  {n: 22, speaker: 'krishna', sa: 'न मे पार्थास्ति कर्तव्यं त्रिषु लोकेषु किञ्चन। नानवाप्तमवाप्तव्यं वर्त एव च कर्मणि॥', tr: 'Na me Parthasti kartavyam trishu lokeshu kinchana, nanavaptamavaptavyam varta eva cha karmani.', en: 'I have no duty in the three worlds, Partha — nothing unwon left to win — yet I remain engaged in action.', hi: 'हे पार्थ! तीनों लोकों में मेरा कोई कर्तव्य नहीं — कुछ अप्राप्त पाने योग्य नहीं — फिर भी मैं कर्म में बरतता हूँ।'},
  {n: 23, speaker: 'krishna', sa: 'यदि ह्यहं न वर्तेयं जातु कर्मण्यतन्द्रितः। मम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः॥', tr: 'Yadi hyaham na varteyam jatu karmanyatandritah, mama vartmanuvartante manushyah Partha sarvashah.', en: 'For if I ever ceased tireless action, Partha, all people would follow my path in every way.', hi: 'यदि मैं कभी आलस्यरहित कर्म न करूँ, तो हे पार्थ, मनुष्य सब प्रकार से मेरे मार्ग का अनुसरण करेंगे।'},
  {n: 24, speaker: 'krishna', sa: 'उत्सीदेयुरिमे लोका न कुर्यां कर्म चेदहम्। सङ्करस्य च कर्ता स्यामुपहन्यामिमाः प्रजाः॥', tr: 'Utsideyurime loka na kuryam karma chedaham, sankarasya cha karta syamupahanyamimah prajah.', en: 'These worlds would perish if I did not act — I would cause confusion and destroy these peoples.', hi: 'यदि मैं कर्म न करूँ तो ये लोक नष्ट हो जाएँ — मैं संकर का कर्ता बनूँ और प्रजा का नाश करूँ।'},
  {n: 25, speaker: 'krishna', sa: 'सक्ताः कर्मण्यविद्वांसो यथा कुर्वन्ति भारत। कुर्याद्विद्वांस्तथासक्तश्चिकीर्षुर्लोकसंग्रहम्॥', tr: 'Saktah karmanyavidvamso yatha kurvanti Bharata, kuryadvidvamstathasaktashchikirshurlokasangraham.', en: 'As the ignorant act from attachment, Bharata, so should the wise act unattached — wishing the welfare of the world.', hi: 'अज्ञानी जैसे आसक्ति से कर्म करते हैं, हे भरतवंशी, वैसे ही ज्ञानी अनासक्त होकर लोकसंग्रह हेतु कर्म करे।'},
  {n: 26, speaker: 'krishna', sa: 'न बुद्धिभेदं जनयेदज्ञानां कर्मसङ्गिनाम्। जोषयेत् सर्वकर्माणि विद्वान् युक्तः समाचरन्॥', tr: 'Na buddhibhedam janayedajnanam karmasanginam, joshayet sarvakarmani vidvan yuktah samacharan.', en: 'The wise should not unsettle the minds of the ignorant attached to deeds — instead, performing all works with poise, inspire them to act.', hi: 'ज्ञानी कर्मासक्त अज्ञानियों की बुद्धि में भेद न डाले — युक्त होकर सब कर्म करता हुआ उनसे करवाए।'},
  {n: 27, speaker: 'krishna', sa: 'प्रकृतेः क्रियमाणानि गुणैः कर्माणि सर्वशः। अहङ्कारविमूढात्मा कर्ताहमिति मन्यते॥', tr: 'Prakriteh kriyamanani gunaih karmani sarvashah, ahankaravimudhatma kartahamiti manyate.', en: 'All actions are performed by nature’s qualities in every way — yet the ego-deluded soul thinks, I am the doer.', hi: 'समस्त कर्म प्रकृति के गुणों द्वारा किए जाते हैं — फिर भी अहंकार से मोहित आत्मा मानती है, मैं कर्ता हूँ।'},
  {n: 28, speaker: 'krishna', sa: 'तत्त्ववित्तु महाबाहो गुणकर्मविभागयोः। गुणा गुणेषु वर्तन्त इति मत्वा न सज्जते॥', tr: 'Tattvavittu mahabaho gunakarmavibhagayoh, guna guneshu vartanta iti matva na sajjate.', en: 'But one who knows the truth of the divisions of qualities and actions, mighty-armed one, sees the senses moving among sense-objects — and stays unattached.', hi: 'हे महाबाहो! गुण-कर्म के विभागों का ज्ञाता — गुण गुणों में बरत रहे हैं — ऐसा मानकर आसक्त नहीं होता।'},
  {n: 29, speaker: 'krishna', sa: 'प्रकृतेर्गुणसम्मूढाः सज्जन्ते गुणकर्मसु। तानकृत्स्नविदो मन्दान् कृत्स्नविन्न विचालयेत्॥', tr: 'Prakritergunasammudhah sajjante gunakarmasu, tanakritsnavido mandan kritsnavinna vichalayet.', en: 'Those deluded by nature’s qualities cling to the workings of those qualities — the knower of the whole should not shake these dull, partial knowers.', hi: 'प्रकृति के गुणों से मोहित गुण-कर्मों में आसक्त होते हैं — पूर्णज्ञानी उन मंद अल्पज्ञों को विचलित न करे।'},
  {n: 30, speaker: 'krishna', sa: 'मयि सर्वाणि कर्माणि संन्यस्याध्यात्मचेतसा। निराशीर्निर्ममो भूत्वा युध्यस्व विगतज्वरः॥', tr: 'Mayi sarvani karmani sannyasyadhyatmachetasa, nirashirnirmamo bhutva yudhyasva vigatajvarah.', en: 'Surrender all your actions to Me with a God-centred mind, free of hope and mine-ness — fight, with your fever gone.', hi: 'मुझमें सब कर्म अर्पित कर, अध्यात्मचित्त से, आशा-ममता छोड़कर, ज्वररहित होकर युद्ध करो।'},
  {n: 31, speaker: 'krishna', sa: 'ये मे मतमिदं नित्यमनुतिष्ठन्ति मानवाः। श्रद्धावन्तोऽनसूयन्तो मुच्यन्ते तेऽपि कर्मभिः॥', tr: 'Ye me matamidam nityamanutishthanti manavah, shraddhavantoanasuyanto muchyante teapi karmabhih.', en: 'Those who constantly follow this teaching of Mine with faith and without cavil — they too are freed from the bondage of deeds.', hi: 'जो मानव श्रद्धावान, दोषदृष्टिरहित होकर इस मेरे मत का सदा पालन करते हैं — वे भी कर्मों से छूटते हैं।'},
  {n: 32, speaker: 'krishna', sa: 'ये त्वेतदभ्यसूयन्तो नानुतिष्ठन्ति मे मतम्। सर्वज्ञानविमूढांस्तान् विद्धि नष्टानचेतसः॥', tr: 'Ye tvetadabhyasuyanto nanutishthanti me matam, sarvajnanavimudhamstan viddhi nashtanachetasah.', en: 'But those who cavil at this teaching and refuse to follow it — know them as lost, deluded in all knowledge, senseless.', hi: 'जो दोष देखकर मेरे इस मत का पालन नहीं करते — उन्हें समस्त ज्ञान में मोहित, नष्ट, अविवेकी जानो।'},
  {n: 33, speaker: 'krishna', sa: 'सदृशं चेष्टते स्वस्याः प्रकृतेर्ज्ञानवानपि। प्रकृतिं यान्ति भूतानि निग्रहः किं करिष्यति॥', tr: 'Sadrisham cheshtate svasyah prakriterjnanavanapi, prakritim yanti bhutani nigrahah kim karishyati.', en: 'Even the wise act according to their own nature — all beings follow their nature, so what can mere restraint achieve?', hi: 'ज्ञानी भी अपनी प्रकृति के अनुरूप चेष्टा करता है — प्राणी प्रकृति को पाते हैं, तो निग्रह क्या करेगा?'},
  {n: 34, speaker: 'krishna', sa: 'इन्द्रियस्येन्द्रियस्यार्थे रागद्वेषौ व्यवस्थितौ। तयोर्न वशमागच्छेत्तौ ह्यस्य परिपन्थिनौ॥', tr: 'Indriyasyendriyasyarthe ragadveshau vyavasthitau, tayorna vashamagachchhettau hyasya paripanthinau.', en: 'Attraction and aversion lurk in every sense facing its object — never come under their sway, for they are the soul’s highwaymen.', hi: 'प्रत्येक इंद्रिय के विषय में राग-द्वेष स्थित हैं — इनके वश में न आए, क्योंकि ये इसके शत्रु हैं।'},
  {n: 35, speaker: 'krishna', sa: 'श्रेयान् स्वधर्मो विगुणः परधर्मात् स्वनुष्ठितात्। स्वधर्मे निधनं श्रेयः परधर्मो भयावहः॥', tr: 'Shreyan svadharmo vigunah paradharmat svanushthitat, svadharme nidhanam shreyah paradharmo bhayavahah.', en: 'Better one’s own duty done imperfectly than another’s done well — death in one’s own duty is good, another’s path is perilous.', hi: 'अच्छी तरह किए परधर्म से गुणहीन स्वधर्म श्रेष्ठ है — स्वधर्म में मरण श्रेयस्कर, परधर्म भयावह है।'},
  {n: 36, speaker: 'arjuna', sa: 'अथ केन प्रयुक्तोऽयं पापं चरति पूरुषः। अनिच्छन्नपि वार्ष्णेय बलादिव नियोजितः॥', tr: 'Atha kena prayuktoayam papam charati purushah, anichchhannapi Varshneya baladiva niyojitah.', en: 'Then by what is one driven to sin, Varshneya — acting unwillingly, as if forced by power?', hi: 'तो यह पुरुष किससे प्रेरित होकर पाप करता है, हे वार्ष्णेय — न चाहता हुआ भी, जैसे बल से लगाया गया हो?'},
  {n: 37, speaker: 'krishna', sa: 'काम एष क्रोध एष रजोगुणसमुद्भवः। महाशनो महापाप्मा विद्ध्येनमिह वैरिणम्॥', tr: 'Kama esha krodha esha rajogunasamudbhavah, mahashano mahapapma viddhyenamiha vairinam.', en: 'It is craving, it is anger, born of restless passion — all-devouring, greatly harmful; know this as the foe here.', hi: 'यह काम है, यह क्रोध है, रजोगुण से उत्पन्न — महाभक्षी, महापापी; इसे यहाँ वैरी जानो।'},
  {n: 38, speaker: 'krishna', sa: 'धूमेनाव्रियते वह्निर्यथादर्शो मलेन च। यथोल्बेनावृतो गर्भस्तथा तेनेदमावृतम्॥', tr: 'Dhumenavriyate vahniryathadarsho malena cha, yatholbenavrito garbhastatha tenedamavritam.', en: 'As fire is veiled by smoke, a mirror by dust, and an unborn child by the womb — so is wisdom veiled by craving.', hi: 'जैसे धुएँ से अग्नि, मल से दर्पण और झिल्ली से गर्भ ढका है — वैसे ही इससे यह ज्ञान ढका है।'},
  {n: 39, speaker: 'krishna', sa: 'आवृतं ज्ञानमेतेन ज्ञानिनो नित्यवैरिणा। कामरूपेण कौन्तेय दुष्पूरेणानलेन च॥', tr: 'Avritam jnanametena jnanino nityavairina, kamarupena Kaunteya dushpurenanalena cha.', en: 'Wisdom is veiled by this constant foe of the wise, Kaunteya — craving in the form of insatiable fire.', hi: 'हे कौंतेय! ज्ञानी के नित्य वैरी, कामरूपी, कभी न भरने वाली अग्नि से ज्ञान ढका है।'},
  {n: 40, speaker: 'krishna', sa: 'इन्द्रियाणि मनो बुद्धिरस्याधिष्ठानमुच्यते। एतैर्विमोहयत्येष ज्ञानमावृत्य देहिनम्॥', tr: 'Indriyani mano buddhirasyadhishthanamuchyate, etairvimohayatyesha jnanamavritya dehinam.', en: 'The senses, mind and reason are called its seat — through these, craving veils wisdom and deludes the embodied soul.', hi: 'इंद्रियाँ, मन और बुद्धि इसके निवासस्थान कहे गए हैं — इनसे ज्ञान को ढककर यह देही को मोहित करता है।'},
  {n: 41, speaker: 'krishna', sa: 'तस्मात् त्वमिन्द्रियाण्यादौ नियम्य भरतर्षभ। पाप्मानं प्रजहि ह्येनं ज्ञानविज्ञाननाशनम्॥', tr: 'Tasmat tvamindriyanyadau niyamya Bharatarshabha, papmanam prajahy hyenam jnanavijnananashanam.', en: 'So first restrain the senses, noblest of Bharatas, and slay this evil destroyer of knowledge and discernment.', hi: 'अतः हे भरतश्रेष्ठ! पहले इंद्रियों को वश में कर इस ज्ञान-विज्ञाननाशी पापी का नाश करो।'},
  {n: 42, speaker: 'krishna', sa: 'इन्द्रियाणि पराण्याहुरिन्द्रियेभ्यः परं मनः। मनसस्तु परा बुद्धिर्यो बुद्धेः परतस्तु सः॥', tr: 'Indriyani paranyahurindriyebhyah param manah, manasastu para buddhiryo buddheh paratastu sah.', en: 'The senses are called high, higher than the senses is the mind, higher than the mind is reason — and higher than reason is the Self.', hi: 'इंद्रियाँ पर कही गईं, इंद्रियों से पर मन, मन से पर बुद्धि — और जो बुद्धि से पर है, वह आत्मा है।'},
  {n: 43, speaker: 'krishna', sa: 'एवं बुद्धेः परं बुद्ध्वा संस्तभ्यात्मानमात्मना। जहि शत्रुं महाबाहो कामरूपं दुरासदम्॥', tr: 'Evam buddheh param buddhva samstabhyatmanamatmana, jahi shatrum mahabaho kamarupam durasadam.', en: 'Thus knowing what lies beyond reason, steadying the self by the Self, slay the foe, mighty-armed one — craving, so hard to conquer.', hi: 'इस प्रकार बुद्धि से पर को जानकर, आत्मा से आत्मा को स्थिर कर, हे महाबाहो, दुर्जय कामरूपी शत्रु को मारो।'}
];
