import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter10Meta: GitaChapterDetail = {
  n: 10,
  title: {en: 'Chapter 10 · Vibhuti Yoga', hi: 'अध्याय 10 · विभूति योग'},
  summary: {
    en: 'The Lord’s glories shining through the finest of all things. 42 verses.',
    hi: 'श्रेष्ठतम वस्तुओं में दिव्य प्रकाश — भगवान की विभूतियाँ। 42 श्लोक।'
  }
};

export const chapter10Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'भूय एव महाबाहो शृणु मे परमं वचः। यत्तेऽहं प्रीयमाणाय वक्ष्यामि हितकाम्यया॥', tr: 'Bhuya eva mahabaho shrinu me paramam vachah, yatteaham priyamanaya vakshyami hitakamyaya.', en: 'Hear again my supreme word, mighty-armed — I speak for your welfare, delighting in you.', hi: 'हे महाबाहो! फिर मेरा परम वचन सुनो — तुम्हारे हित की कामना से, तुमसे प्रेम करके कहता हूँ।'},
  {n: 2, speaker: 'krishna', sa: 'न मे विदुः सुरगणाः प्रभवं न महर्षयः। अहमादिर्हि देवानां महर्षीणां च सर्वशः॥', tr: 'Na me viduh suraganah prabhavam na maharshayah, ahamadirhi devanam maharshinam cha sarvashah.', en: 'Neither gods nor great seers know my origin — I am the source of gods and seers alike.', hi: 'मेरे प्रभव को न देवगण जानते हैं, न महर्षि — मैं ही देवों और महर्षियों का आदि हूँ।'},
  {n: 3, speaker: 'krishna', sa: 'यो मामजमनादिं च वेत्ति लोकमहेश्वरम्। असम्मूढः स मर्त्येषु सर्वपापैः प्रमुच्यते॥', tr: 'Yo mamajamanadim cha vetti lokamaheshvaram, asammudhah sa martyeshu sarvapapaih pramuchyate.', en: 'Who knows me as birthless, beginningless, great lord of worlds — undeluded, he is freed from all sin.', hi: 'जो मुझे अज, अनादि और लोकमहेश्वर जानता है, वह मर्त्यों में मोहरहित हो समस्त पापों से मुक्त होता है।'},
  {n: 4, speaker: 'krishna', sa: 'बुद्धिर्ज्ञानमसम्मोहः क्षमा सत्यं दमः शमः। सुखं दुःखं भवोऽभावो भयं चाभयमेव च॥', tr: 'Buddhirjnanamasammohah kshama satyam damah shamah, sukham duhkham bhavoabhavo bhayam chabhayameva cha.', en: 'Discernment, wisdom, clarity, patience, truth, restraint, peace — joy and sorrow, birth and death, fear and fearlessness.', hi: 'बुद्धि, ज्ञान, असम्मोह, क्षमा, सत्य, दम, शम — सुख-दुःख, भव-अभाव, भय-अभय।'},
  {n: 5, speaker: 'krishna', sa: 'अहिंसा समता तुष्टिस्तपो दानं यशोऽयशः। भवन्ति भावा भूतानां मत्त एव पृथग्विधाः॥', tr: 'Ahimsa samata tushtistapo danam yashoayashah, bhavanti bhava bhutanam matta eva prithagvidhah.', en: 'Non-harming, evenness, contentment, austerity, charity, fame and infamy — these many states arise from me alone.', hi: 'अहिंसा, समता, तुष्टि, तप, दान, यश-अपयश — भूतों के ये नाना भाव मुझसे ही होते हैं।'},
  {n: 6, speaker: 'krishna', sa: 'महर्षयः सप्त पूर्वे चत्वारो मनवस्तथा। मद्भावा मानसा जाता येषां लोक इमाः प्रजाः॥', tr: 'Maharshayah sapta purve chatvaro manavastatha, madbhava manasa jata yesham loka imah prajah.', en: 'The seven ancient seers and the four Manus, born of my mind, share my being — from them come these creatures.', hi: 'सप्त पूर्व महर्षि और चार मनु — मेरे भाव वाले, मन से उत्पन्न — जिनसे लोक में ये प्रजाएँ हुईं।'},
  {n: 7, speaker: 'krishna', sa: 'एतां विभूतिं योगं च मम यो वेत्ति तत्त्वतः। सोऽविकम्पेन योगेन युज्यते नात्र संशयः॥', tr: 'Etam vibhutim yogam cha mama yo vetti tattvatah, soavikampena yogena yujyate natra samshayah.', en: 'Who truly knows this glory and power of mine is yoked by unshakable union — no doubt of it.', hi: 'जो मेरी इस विभूति और योग को तत्त्व से जानता है, वह अविचल योग से युक्त होता है — इसमें संशय नहीं।'},
  {n: 8, speaker: 'krishna', sa: 'अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते। इति मत्वा भजन्ते मां बुधा भावसमन्विताः॥', tr: 'Aham sarvasya prabhavo mattah sarvam pravartate, iti matva bhajante mam budha bhavasamanvitah.', en: 'I am the source of all; from me all moves forth — knowing this, the wise worship me with full hearts.', hi: 'मैं सबकी उत्पत्ति हूँ, मुझसे सब प्रवर्तित है — ऐसा मानकर ज्ञानी भावपूर्वक मुझे भजते हैं।'},
  {n: 9, speaker: 'krishna', sa: 'मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम्। कथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च॥', tr: 'Machchitta madgataprana bodhayantah parasparam, kathayantashcha mam nityam tushyanti cha ramanti cha.', en: 'Their minds on me, their lives given to me, they enlighten one another and ever speak of me in joy.', hi: 'मुझमें चित्त और प्राण लगाए, परस्पर बोध कराते, नित्य मेरी कथा कहते हुए वे संतुष्ट और आनंदित रहते हैं।'},
  {n: 10, speaker: 'krishna', sa: 'तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम्। ददामि बुद्धियोगं तं येन मामुपयान्ति ते॥', tr: 'Tesham satatayuktanam bhajatam pritipurvakam, dadami buddhiyogam tam yena mamupayanti te.', en: 'To those ever-yoked lovers who worship me, I grant the yoga of discernment by which they reach me.', hi: 'उन नित्ययुक्त प्रेमपूर्वक भजने वालों को मैं वह बुद्धियोग देता हूँ, जिससे वे मुझे प्राप्त होते हैं।'},
  {n: 11, speaker: 'krishna', sa: 'तेषामेवानुकम्पार्थमहमज्ञानजं तमः। नाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता॥', tr: 'Teshamevanukamparthamahamajnanajam tamah, nashayamyatmabhavastho jnanadipena bhasvata.', en: 'For love of them, dwelling within, I scatter their darkness born of ignorance with wisdom’s shining lamp.', hi: 'उन्हीं पर अनुग्रह हेतु, आत्मभाव में स्थित मैं अज्ञानजन्य अंधकार को ज्ञानदीप से नष्ट करता हूँ।'},
  {n: 12, speaker: 'arjuna', sa: 'परं ब्रह्म परं धाम पवित्रं परमं भवान्। पुरुषं शाश्वतं दिव्यमादिदेवमजं विभुम्॥', tr: 'Param brahma param dhama pavitram paramam bhavan, purusham shashvatam divyamadidevamajam vibhum.', en: 'You are the supreme Absolute, supreme abode, supreme purity — eternal divine Person, primal god, birthless, all-pervading.', hi: 'आप परम ब्रह्म, परम धाम, परम पवित्र हैं — शाश्वत दिव्य पुरुष, आदिदेव, अज और विभु।'},
  {n: 13, speaker: 'arjuna', sa: 'आहुस्त्वामृषयः सर्वे देवर्षिर्नारदस्तथा। असितो देवलो व्यासः स्वयं चैव ब्रवीषि मे॥', tr: 'Ahustvamrishayah sarve devarshirnaradastatha, asito devalo vyasah svayam chaiva bravis hi me.', en: 'All the seers proclaim you — Narada, Asita, Devala, Vyasa — and you yourself tell me so.', hi: 'समस्त ऋषि आपको ऐसा कहते हैं — देवर्षि नारद, असित, देवल, व्यास — और स्वयं आप भी मुझसे कहते हैं।'},
  {n: 14, speaker: 'arjuna', sa: 'सर्वमेतदृतं मन्ये यन्मां वदसि केशव। न हि ते भगवन्व्यक्तिं विदुर्देवा न दानवाः॥', tr: 'Sarvametadritam manye yanmam vadasi Keshava, na hi te bhagavanvyaktim vidurdeva na danavah.', en: 'All you tell me, Keshava, I hold true — for neither gods nor demons know your manifesting, Lord.', hi: 'हे केशव! आप जो कहते हैं, सब सत्य मानता हूँ — हे भगवन्! आपकी अभिव्यक्ति को न देव जानते हैं, न दानव।'},
  {n: 15, speaker: 'arjuna', sa: 'स्वयमेवात्मनात्मानं वेत्थ त्वं पुरुषोत्तम। भूतभावन भूतेश देवदेव जगत्पते॥', tr: 'Svayamevatmanatmanam vettha tvam Purushottama, bhutabhavana bhutesha devadeva jagatpate.', en: 'You alone know yourself by yourself, supreme Person — source of beings, lord of beings, god of gods, world-lord.', hi: 'हे पुरुषोत्तम! आप स्वयं ही अपने आत्मा से अपने को जानते हैं — हे भूतभावन, भूतेश, देवदेव, जगत्पते!'},
  {n: 16, speaker: 'arjuna', sa: 'वक्तुमर्हस्यशेषेण दिव्या ह्यात्मविभूतयः। याभिर्विभूतिभिर्लोकानिमांस्त्वं व्याप्य तिष्ठसि॥', tr: 'Vaktumarhasyasheshena divya hyatmavibhutayah, yabhirvibhutibhirlokanimamstvam vyapya tishthasi.', en: 'Tell me fully of your divine glories — the powers by which you stand pervading these worlds.', hi: 'जिन विभूतियों से आप इन लोकों को व्याप्त करके स्थित हैं, उन दिव्य आत्मविभूतियों को पूर्णतः कहने योग्य हैं।'},
  {n: 17, speaker: 'arjuna', sa: 'कथं विद्यामहं योगिंस्त्वां सदा परिचिन्तयन्। केषु केषु च भावेषु चिन्त्योऽसि भगवन्मया॥', tr: 'Katham vidyamaham yogimstvam sada parichintayan, keshu keshu cha bhaveshu chintyoasi bhagavanmaya.', en: 'How may I know you, O yogi, ever meditating — in what forms may I contemplate you, Lord?', hi: 'हे योगिन्! सदा चिंतन करता मैं आपको कैसे जानूँ — हे भगवन्! किन-किन भावों में मैं आपका चिंतन करूँ?'},
  {n: 18, speaker: 'arjuna', sa: 'विस्तरेणात्मनो योगं विभूतिं च जनार्दन। भूयः कथय तृप्तिर्हि शृण्वतो नास्ति मेऽमृतम्॥', tr: 'Vistarenatmano yogam vibhutim cha Janardana, bhuyah kathaya triptirhi shrinvato nasti meamritam.', en: 'Tell me again in full your power and glory, Janardana — I never tire of hearing your deathless words.', hi: 'हे जनार्दन! अपने योग और विभूति को विस्तार से फिर कहिए — आपका अमृत सुनते मुझे तृप्ति नहीं होती।'},
  {n: 19, speaker: 'krishna', sa: 'हन्त ते कथयिष्यामि दिव्या ह्यात्मविभूतयः। प्राधान्यतः कुरुश्रेष्ठ नास्त्यन्तो विस्तरस्य मे॥', tr: 'Hanta te kathayishyami divya hyatmavibhutayah, pradhanyatah Kurushreshtha nastyanto vistarasya me.', en: 'Then I will tell you my chief divine glories, noblest of Kurus — there is no end to my expanse.', hi: 'अच्छा, हे कुरुश्रेष्ठ! अपनी दिव्य विभूतियाँ प्रधानता से बताता हूँ — मेरे विस्तार का अंत नहीं है।'},
  {n: 20, speaker: 'krishna', sa: 'अहमात्मा गुडाकेश सर्वभूताशयस्थितः। अहमादिश्च मध्यं च भूतानामन्त एव च॥', tr: 'Ahamatma Gudakesha sarvabhutashayasthitah, ahamadishcha madhyam cha bhutanamanta eva cha.', en: 'I am the Self, Gudakesha, dwelling in every heart — the beginning, middle, and end of beings.', hi: 'हे गुडाकेश! समस्त भूतों के हृदय में स्थित आत्मा मैं हूँ — भूतों का आदि, मध्य और अंत भी मैं हूँ।'},
  {n: 21, speaker: 'krishna', sa: 'आदित्यानामहं विष्णुर्ज्योतिषां रविरंशुमान्। मरीचिर्मरुतामस्मि नक्षत्राणामहं शशी॥', tr: 'Adityanamaham Vishnurjyotisham raviramshuman, Marichirmarutamasmi nakshatranamaham shashi.', en: 'Of sun-gods I am Vishnu, of lights the radiant sun — of storm-gods Marichi, of stars the moon.', hi: 'आदित्यों में विष्णु मैं हूँ, ज्योतियों में अंशुमान सूर्य — मरुतों में मरीचि, नक्षत्रों में चंद्रमा मैं हूँ।'},
  {n: 22, speaker: 'krishna', sa: 'वेदानां सामवेदोऽस्मि देवानामस्मि वासवः। इन्द्रियाणां मनश्चास्मि भूतानामस्मि चेतना॥', tr: 'Vedanam Samavedoasmi devanamasmi Vasavah, indriyanam manashchasmi bhutanamasmi chetana.', en: 'Of Vedas I am the Sama, of gods Indra — of senses the mind, of beings consciousness.', hi: 'वेदों में सामवेद मैं हूँ, देवों में इंद्र — इंद्रियों में मन और भूतों में चेतना मैं हूँ।'},
  {n: 23, speaker: 'krishna', sa: 'रुद्राणां शङ्करश्चास्मि वित्तेशो यक्षरक्षसाम्। वसूनां पावकश्चास्मि मेरुः शिखरिणामहम्॥', tr: 'Rudranam Shankarashchasmi vittesho yaksharakshasam, Vasunam pavakashchasmi Meruh shikharinamaham.', en: 'Of Rudras I am Shankara, of gnomes and guardians Kubera — of Vasus fire, of peaks Mount Meru.', hi: 'रुद्रों में शंकर मैं हूँ, यक्ष-राक्षसों में कुबेर — वसुओं में अग्नि और शिखर वालों में मेरु मैं हूँ।'},
  {n: 24, speaker: 'krishna', sa: 'पुरोधसां च मुख्यं मां विद्धि पार्थ बृहस्पतिम्। सेनानीनामहं स्कन्दः सरसामस्मि सागरः॥', tr: 'Purodhasam cha mukhyam mam viddhi Partha Brihaspatim, senaninamaham Skandah sarasamasmi sagarah.', en: 'Know me, Partha, as Brihaspati, chief of priests — of generals Skanda, of waters the ocean.', hi: 'हे पार्थ! पुरोहितों में मुख्य बृहस्पति मुझे जानो — सेनापतियों में स्कंद और जलाशयों में सागर मैं हूँ।'},
  {n: 25, speaker: 'krishna', sa: 'महर्षीणां भृगुरहं गिरामस्म्येकमक्षरम्। यज्ञानां जपयज्ञोऽस्मि स्थावराणां हिमालयः॥', tr: 'Maharshinam Bhriguraham giramasmyekamaksharam, yajnanam japayajnoasmi sthavaranam Himalayah.', en: 'Of great seers I am Bhrigu, of words the single syllable Om — of rites the rite of whispered prayer, of mountains the Himalaya.', hi: 'महर्षियों में भृगु मैं हूँ, वाणी में एकाक्षर ॐ — यज्ञों में जपयज्ञ और स्थिर वस्तुओं में हिमालय मैं हूँ।'},
  {n: 26, speaker: 'krishna', sa: 'अश्वत्थः सर्ववृक्षाणां देवर्षीणां च नारदः। गन्धर्वाणां चित्ररथः सिद्धानां कपिलो मुनिः॥', tr: 'Ashvatthah sarvavrikshanam devarshinam cha Naradah, gandharvanam Chitrarathah siddhanam Kapilo munih.', en: 'Of trees the sacred fig, of divine seers Narada — of musicians Chitraratha, of adepts the sage Kapila.', hi: 'वृक्षों में अश्वत्थ मैं हूँ, देवर्षियों में नारद — गंधर्वों में चित्ररथ और सिद्धों में कपिल मुनि मैं हूँ।'},
  {n: 27, speaker: 'krishna', sa: 'उच्चैःश्रवसमश्वानां विद्धि माममृतोद्भवम्। ऐरावतं गजेन्द्राणां नराणां च नराधिपम्॥', tr: 'Uchchaihshravasamashvanam viddhi mamamritodbhavam, Airavatam gajendranam naranam cha naradhipam.', en: 'Of horses know me as Uccaihsravas, born of nectar — of elephants Airavata, of men the king.', hi: 'अश्वों में अमृत से उत्पन्न उच्चैःश्रवा मुझे जानो — गजराजों में ऐरावत और मनुष्यों में राजा मैं हूँ।'},
  {n: 28, speaker: 'krishna', sa: 'आयुधानामहं वज्रं धेनूनामस्मि कामधुक्। प्रजनश्चास्मि कन्दर्पः सर्पाणामस्मि वासुकिः॥', tr: 'Ayudhanamaham vajram dhenunamasmi kamadhuk, prajanashchasmi kandarpah sarpanamasmi Vasukih.', en: 'Of weapons I am the thunderbolt, of cows the wish-fulfilling — of fathers of children desire, of serpents Vasuki.', hi: 'आयुधों में वज्र मैं हूँ, धेनुओं में कामधेनु — संतानोत्पत्ति हेतु कामदेव और सर्पों में वासुकि मैं हूँ।'},
  {n: 29, speaker: 'krishna', sa: 'अनन्तश्चास्मि नागानां वरुणो यादसामहम्। पितॄणामर्यमा चास्मि यमः संयमतामहम्॥', tr: 'Anantashchasmi naganam Varuno yadasamaham, pitrinamaryama chasmi Yamah samyamatamaham.', en: 'Of many-hooded serpents Ananta, of water-dwellers Varuna — of ancestors Aryaman, of restrainers Yama.', hi: 'नागों में अनंत मैं हूँ, जलचरों में वरुण — पितरों में अर्यमा और संयमन करने वालों में यम मैं हूँ।'},
  {n: 30, speaker: 'krishna', sa: 'प्रह्लादश्चास्मि दैत्यानां कालः कलयतामहम्। मृगाणां च मृगेन्द्रोऽहं वैनतेयश्च पक्षिणाम्॥', tr: 'Prahladashchasmi daityanam kalah kalayatamaham, mriganam cha mrigendroaham Vainateyashcha pakshinam.', en: 'Of titans I am Prahlada, of reckoners time — of beasts the lion, of birds Garuda.', hi: 'दैत्यों में प्रह्लाद मैं हूँ, गणना करने वालों में काल — पशुओं में सिंह और पक्षियों में गरुड़ मैं हूँ।'},
  {n: 31, speaker: 'krishna', sa: 'पवनः पवतामस्मि रामः शस्त्रभृतामहम्। झषाणां मकरश्चास्मि स्रोतसामस्मि जाह्नवी॥', tr: 'Pavanah pavatamasmi Ramah shastrabhritamaham, jhashanam makarashchasmi srotasamasmi Jahnavi.', en: 'Of purifiers the wind, of weapon-bearers Rama — of fishes the crocodile, of rivers the Ganga.', hi: 'पवित्र करने वालों में पवन मैं हूँ, शस्त्रधारियों में राम — मत्स्यों में मकर और नदियों में गंगा मैं हूँ।'},
  {n: 32, speaker: 'krishna', sa: 'सर्गाणामादिरन्तश्च मध्यं चैवाहमर्जुन। अध्यात्मविद्या विद्यानां वादः प्रवदतामहम्॥', tr: 'Sarganamadirantashcha madhyam chaivahamarjuna, adhyatmavidya vidyanam vadah pravadatamaham.', en: 'Of creations I am beginning, end, and middle, Arjuna — of sciences the science of Self, of debaters the reasoned word.', hi: 'हे अर्जुन! सृष्टियों का आदि, अंत और मध्य मैं ही हूँ — विद्याओं में अध्यात्मविद्या और वादियों में वाद मैं हूँ।'},
  {n: 33, speaker: 'krishna', sa: 'अक्षराणामकारोऽस्मि द्वन्द्वः सामासिकस्य च। अहमेवाक्षयः कालो धाताहं विश्वतोमुखः॥', tr: 'Aksharanamakarosmi dvandvah samasikasya cha, ahamevakshayah kalo dhataham vishvatomukhah.', en: 'Of letters I am A, of compounds the pairing — I am imperishable time, the ordainer with faces everywhere.', hi: 'अक्षरों में अकार मैं हूँ, समासों में द्वंद्व — मैं ही अक्षय काल और विश्वतोमुख धाता हूँ।'},
  {n: 34, speaker: 'krishna', sa: 'मृत्युः सर्वहरश्चाहमुद्भवश्च भविष्यताम्। कीर्तिः श्रीर्वाक्च नारीणां स्मृतिर्मेधा धृतिः क्षमा॥', tr: 'Mrityuh sarvaharashchahamudbhavashcha bhavishyatam, kirtih shrirvakcha narinam smritirmedha dhritih kshama.', en: 'I am all-seizing death, and the birth of things to be — of women’s virtues fame, fortune, speech, memory, insight, resolve, patience.', hi: 'सर्वहारी मृत्यु मैं हूँ, और भविष्य का उद्भव भी — नारियों में कीर्ति, श्री, वाणी, स्मृति, मेधा, धृति और क्षमा मैं हूँ।'},
  {n: 35, speaker: 'krishna', sa: 'बृहत्साम तथा साम्नां गायत्री छन्दसामहम्। मासानां मार्गशीर्षोऽहमृतूनां कुसुमाकरः॥', tr: 'Brihatsama tatha samnam Gayatri chhandasamaham, masanam Margashirshoahamritunam kusumakarah.', en: 'Of hymns I am the Brihatsaman, of metres Gayatri — of months Margasirsha, of seasons spring.', hi: 'सामगानों में बृहत्साम मैं हूँ, छंदों में गायत्री — मासों में मार्गशीर्ष और ऋतुओं में वसंत मैं हूँ।'},
  {n: 36, speaker: 'krishna', sa: 'द्यूतं छलयतामस्मि तेजस्तेजस्विनामहम्। जयोऽस्मि व्यवसायोऽस्मि सत्त्वं सत्त्ववतामहम्॥', tr: 'Dyutam chhalayatamasmi tejastejasvinamaham, jayoasmi vyavasayoasmi sattvam sattvavatamaham.', en: 'Of cheats I am the dice-play, of the splendid their splendour — I am victory, resolve, and the goodness of the good.', hi: 'छलने वालों में द्यूत मैं हूँ, तेजस्वियों का तेज — जय मैं हूँ, निश्चय मैं हूँ, सात्त्विकों का सत्त्व मैं हूँ।'},
  {n: 37, speaker: 'krishna', sa: 'वृष्णीनां वासुदेवोऽस्मि पाण्डवानां धनञ्जयः। मुनीनामप्यहं व्यासः कवीनामुशना कविः॥', tr: 'Vrishninam Vasudevoasmi Pandavanam Dhananjayah, muninamapyaham Vyasah kavinamushana kavih.', en: 'Of Vrishnis I am Krishna, of Pandavas Arjuna — of sages Vyasa, of poets Usanas.', hi: 'वृष्णियों में वासुदेव मैं हूँ, पांडवों में धनंजय — मुनियों में व्यास और कवियों में शुक्राचार्य मैं हूँ।'},
  {n: 38, speaker: 'krishna', sa: 'दण्डो दमयतामस्मि नीतिरस्मि जिगीषताम्। मौनं चैवास्मि गुह्यानां ज्ञानं ज्ञानवतामहम्॥', tr: 'Dando damayatamasmi nitirasmi jigishatam, maunam chaivasmi guhyanam jnanam jnanavatamaham.', en: 'Of tamers I am the rod, of strivers wise policy — of secrets silence, of knowers knowledge.', hi: 'दमन करने वालों में दंड मैं हूँ, विजय चाहने वालों में नीति — गुह्यों में मौन और ज्ञानवानों में ज्ञान मैं हूँ।'},
  {n: 39, speaker: 'krishna', sa: 'यच्चापि सर्वभूतानां बीजं तदहमर्जुन। न तदस्ति विना यत्स्यान्मया भूतं चराचरम्॥', tr: 'Yachchapi sarvabhutanam bijam tadahamarjuna, na tadasti vina yatsyanmaya bhutam characharam.', en: 'Whatever is the seed of all beings, that am I, Arjuna — nothing moving or still can be without me.', hi: 'हे अर्जुन! समस्त भूतों का जो बीज है, वह मैं हूँ — चर-अचर कोई भूत मुझसे रहित नहीं।'},
  {n: 40, speaker: 'krishna', sa: 'नान्तोऽस्ति मम दिव्यानां विभूतीनां परन्तप। एष तूद्देशतः प्रोक्तो विभूतेर्विस्तरो मया॥', tr: 'Nantoasti mama divyanam vibhutinam parantapa, esha tuddeshatah prokto vibhutervistaro maya.', en: 'There is no end to my divine glories, scorcher of foes — this is but a hint of their expanse.', hi: 'हे परंतप! मेरी दिव्य विभूतियों का अंत नहीं — यह विस्तार मैंने संक्षेप से कहा है।'},
  {n: 41, speaker: 'krishna', sa: 'यद्यद्विभूतिमत्सत्त्वं श्रीमदूर्जितमेव वा। तत्तदेवावगच्छ त्वं मम तेजोंऽशसम्भवम्॥', tr: 'Yadyadvibhutimatsattvam shrimadurjitameva va, tattadevapagachchha tvam mama tejoamshasambhavam.', en: 'Whatever is glorious, lovely, or mighty — know it springs from a spark of my splendour.', hi: 'जो-जो विभूतिमान, श्रीमान या ऊर्जावान है, उसे मेरे तेज के अंश से उत्पन्न जानो।'},
  {n: 42, speaker: 'krishna', sa: 'अथवा बहुनैतेन किं ज्ञातेन तवार्जुन। विष्टभ्याहमिदं कृत्स्नमेकांशेन स्थितो जगत्॥', tr: 'Athava bahunaitena kim jnatena tavarjuna, vishtabhyahamdam kritsnamekamshena sthito jagat.', en: 'But what need of many words, Arjuna — I stand upholding this whole world with a single fragment of myself.', hi: 'अथवा हे अर्जुन! इतने विस्तार से तुम्हें क्या प्रयोजन — मैं इस संपूर्ण जगत को एक अंश से धारण करके स्थित हूँ।'}
];
