import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter13Meta: GitaChapterDetail = {
  n: 13,
  title: {en: 'Chapter 13 · Kshetra Kshetrajna Vibhaga Yoga', hi: 'अध्याय 13 · क्षेत्र क्षेत्रज्ञ विभाग योग'},
  summary: {
    en: 'The field and its knower — body, Self, and true discernment. 34 verses.',
    hi: 'क्षेत्र और क्षेत्रज्ञ — शरीर, आत्मा और सच्चा विवेक। 34 श्लोक।'
  }
};

export const chapter13Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'इदं शरीरं कौन्तेय क्षेत्रमित्यभिधीयते। एतद्यो वेत्ति तं प्राहुः क्षेत्रज्ञ इति तद्विदः॥', tr: 'Idam shariram Kaunteya kshetramityabhidhiyate, etadyo vetti tam prahuh kshetrajna iti tadvidah.', en: 'This body, Kaunteya, is called the field — who knows it is called the knower of the field by those who see.', hi: 'हे कौंतेय! यह शरीर क्षेत्र कहलाता है — इसे जो जानता है, ज्ञानी उसे क्षेत्रज्ञ कहते हैं।'},
  {n: 2, speaker: 'krishna', sa: 'क्षेत्रज्ञं चापि मां विद्धि सर्वक्षेत्रेषु भारत। क्षेत्रक्षेत्रज्ञयोर्ज्ञानं यत्तज्ज्ञानं मतं मम॥', tr: 'Kshetrajnam chapi mam viddhi sarvakshetreshu Bharata, kshetrakshetrajnayorjnanam yattajjnanam matam mama.', en: 'Know me as the knower in all fields, Bharata — to know field and knower, that I call true knowledge.', hi: 'हे भारत! समस्त क्षेत्रों में मुझे भी क्षेत्रज्ञ जानो — क्षेत्र और क्षेत्रज्ञ का ज्ञान ही मेरा माना हुआ ज्ञान है।'},
  {n: 3, speaker: 'krishna', sa: 'तत्क्षेत्रं यच्च यादृक्च यद्विकारि यतश्च यत्। स च यो यत्प्रभावश्च तत्समासेन मे शृणु॥', tr: 'Tatkshetram yachcha yadrikcha yadvikari yatashcha yat, sa cha yo yatprabhavashcha tatsamasena me shrinu.', en: 'What the field is, what it is like, its changes, whence it comes, who the knower is and what his power — hear in brief from me.', hi: 'वह क्षेत्र क्या है, कैसा है, उसके विकार क्या हैं, वह किससे बना है, ज्ञाता कौन है और उसका प्रभाव क्या है — संक्षेप में सुनो।'},
  {n: 4, speaker: 'krishna', sa: 'ऋषिभिर्बहुधा गीतं छन्दोभिर्विविधैः पृथक्। ब्रह्मसूत्रपदैश्चैव हेतुमद्भिर्विनिश्चितैः॥', tr: 'Rishibhirbahudha gitam chhandobhirvividhaih prithak, Brahmasutrapadaishchaiva hetumadbhirvinishchitaih.', en: 'Sung by seers in many ways, in varied hymns, and in firm reasoned Brahma-sutra sayings —', hi: 'ऋषियों ने विविध छंदों में बहुत प्रकार से गाया है, और युक्तियुक्त ब्रह्मसूत्र पदों में भी निश्चयपूर्वक कहा है —'},
  {n: 5, speaker: 'krishna', sa: 'महाभूतान्यहङ्कारो बुद्धिरव्यक्तमेव च। इन्द्रियाणि दशैकं च पञ्च चेन्द्रियगोचराः॥', tr: 'Mahabhutanyahankaro buddhiravyaktameva cha, indriyani dashaikam cha pancha chendriyagocharah.', en: 'The five great elements, ego, reason, the unseen source, eleven senses, and the five sense fields —', hi: 'पाँच महाभूत, अहंकार, बुद्धि, अव्यक्त, ग्यारह इंद्रियाँ और पाँच इंद्रिय विषय —'},
  {n: 6, speaker: 'krishna', sa: 'इच्छा द्वेषः सुखं दुःखं सङ्घातश्चेतना धृतिः। एतत्क्षेत्रं समासेन सविकारमुदाहृतम्॥', tr: 'Ichchha dveshah sukham duhkham sanghatashchetana dhritih, etatkshetram samasena savikaramudahritam.', en: 'Wanting, hating, joy, sorrow, the frame, awareness, resolve — this is the field with its changes, in brief.', hi: 'इच्छा, द्वेष, सुख, दुःख, संघात, चेतना, धृति — विकारों सहित यह संक्षेप में क्षेत्र कहा गया।'},
  {n: 7, speaker: 'krishna', sa: 'अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम्। आचार्योपासनं शौचं स्थैर्यमात्मविनिग्रहः॥', tr: 'Amanitvamadambhitvamahimsa kshantirarjavam, acharyopasanam shaucham sthairyamatmavinigrahah.', en: 'Humility, honesty, harmlessness, patience, candor, honoring the teacher, purity, steadiness, self-rule —', hi: 'मानहीनता, दंभहीनता, अहिंसा, क्षमा, सरलता, गुरुसेवा, पवित्रता, स्थिरता, आत्मसंयम —'},
  {n: 8, speaker: 'krishna', sa: 'इन्द्रियार्थेषु वैराग्यमनहङ्कार एव च। जन्ममृत्युजराव्याधिदुःखदोषानुदर्शनम्॥', tr: 'Indriyartheshu vairagyamanahankara eva cha, janmamrityujaravyadhiduhkhadoshanudarshanam.', en: 'Freedom from sense cravings and pride, and seeing the flaw of pain in birth, death, age and sickness —', hi: 'इंद्रिय विषयों से वैराग्य, अहंकारहीनता, जन्म-मृत्यु-जरा-व्याधि में दुःख-दोष का दर्शन —'},
  {n: 9, speaker: 'krishna', sa: 'असक्तिरनभिष्वङ्गः पुत्रदारगृहादिषु। नित्यं च समचित्तत्वमिष्टानिष्टोपपत्तिषु॥', tr: 'Asaktiranabhishvangah putradaragrihadishu, nityam cha samachittatvamishtanishtopapattishu.', en: 'Unclinging, no blind fondness for child, spouse or home, and steady poise in welcome and unwelcome turns —', hi: 'आसक्ति और पुत्र-पत्नी-घर में मोह का अभाव, प्रिय-अप्रिय प्राप्ति में सदा समचित्तता —'},
  {n: 10, speaker: 'krishna', sa: 'मयि चानन्ययोगेन भक्तिरव्यभिचारिणी। विविक्तदेशसेवित्वमरतिर्जनसंसदि॥', tr: 'Mayi chananyayogena bhaktiravyabhicharini, viviktadeshas evitvamaratirjanasamsadi.', en: 'Unswerving devotion to me through single yoga, love of quiet places, no relish for crowds —', hi: 'मुझमें अनन्य योग से अटल भक्ति, एकांत स्थान में रुचि, जनसमूह में अरुचि —'},
  {n: 11, speaker: 'krishna', sa: 'अध्यात्मज्ञाननित्यत्वं तत्त्वज्ञानार्थदर्शनम्। एतज्ज्ञानमिति प्रोक्तमज्ञानं यदतोऽन्यथा॥', tr: 'Adhyatmajnananityatvam tattvajnanaarthadarshanam, etajjnanamiti proktamajnanam yadatoanyatha.', en: 'Steadiness in Self wisdom and sight of the goal of truth — this is called knowledge, all else is ignorance.', hi: 'अध्यात्म ज्ञान में नित्यता और तत्त्वज्ञान के अर्थ का दर्शन — यही ज्ञान है, इससे विपरीत अज्ञान है।'},
  {n: 12, speaker: 'krishna', sa: 'ज्ञेयं यत्तत्प्रवक्ष्यामि यज्ज्ञात्वामृतमश्नुते। अनादिमत्परं ब्रह्म न सत्तन्नासदुच्यते॥', tr: 'Jneyam yattatpravakshyami yajjnatvamritamashnute, anadimatparam Brahma na sattannasaduchyate.', en: 'I shall tell what is worth knowing, knowing which one tastes the deathless — beginningless supreme Brahman, called neither being nor non-being.', hi: 'जिसे जानकर अमृत मिलता है, वह ज्ञेय बताता हूँ — अनादि परब्रह्म, जिसे न सत कहा जाता है न असत।'},
  {n: 13, speaker: 'krishna', sa: 'सर्वतः पाणिपादं तत्सर्वतोऽक्षिशिरोमुखम्। सर्वतः श्रुतिमल्लोके सर्वमावृत्य तिष्ठति॥', tr: 'Sarvatah panipadam tatsarvatoakshishiromukham, sarvatah shrutimalloke sarvamavritya tishthati.', en: 'With hands and feet everywhere, eyes, heads and mouths everywhere, ears everywhere — it stands covering all in the world.', hi: 'सब ओर हाथ-पैर वाला, सब ओर नेत्र-सिर-मुख वाला, सब ओर कान वाला — लोक में सबको घेरकर स्थित है।'},
  {n: 14, speaker: 'krishna', sa: 'सर्वेन्द्रियगुणाभासं सर्वेन्द्रियविवर्जितम्। असक्तं सर्वभृच्चैव निर्गुणं गुणभोक्तृ च॥', tr: 'Sarvendriyagunabhasam sarvendriyavivarjitam, asaktam sarvabhrichchaiva nirgunam gunabhoktri cha.', en: 'It shines through all sense powers yet lacks all senses, unclinging yet upholding all, beyond qualities yet tasting them.', hi: 'सभी इंद्रिय गुणों का आभासक होकर भी इंद्रिय रहित है, आसक्ति रहित होकर सबका भरण करता है, निर्गुण होकर गुणों का भोक्ता है।'},
  {n: 15, speaker: 'krishna', sa: 'बहिरन्तश्च भूतानामचरं चरमेव च। सूक्ष्मत्वात्तदविज्ञेयं दूरस्थं चान्तिके च तत्॥', tr: 'Bahirantashcha bhutanamacharam charameva cha, sukshmatvattadavijneyam durastham chantike cha tat.', en: 'Outside and inside beings, moving and unmoving — too subtle to grasp, far away yet very near.', hi: 'प्राणियों के बाहर-भीतर, चर-अचर — सूक्ष्म होने से अज्ञेय, दूर स्थित भी और समीप भी।'},
  {n: 16, speaker: 'krishna', sa: 'अविभक्तं च भूतेषु विभक्तमिव च स्थितम्। भूतभर्तृ च तज्ज्ञेयं ग्रसिष्णु प्रभविष्णु च॥', tr: 'Avibhaktam cha bhuteshu vibhaktamiva cha sthitam, bhutabhartri cha tajjneyam grasishnu prabhavishnu cha.', en: 'Undivided, it stands as if divided among beings — that knowable upholds beings, devours and brings them forth.', hi: 'अविभक्त होकर भी प्राणियों में विभक्त सा स्थित है — वह ज्ञेय भूतों का भर्ता, संहारक और उत्पत्तिकर्ता है।'},
  {n: 17, speaker: 'krishna', sa: 'ज्योतिषामपि तज्ज्योतिस्तमसः परमुच्यते। ज्ञानं ज्ञेयं ज्ञानगम्यं हृदि सर्वस्य विष्ठितम्॥', tr: 'Jyotishamapi tajjyotistamasah paramuchyate, jnanam jneyam jnanagamyam hridi sarvasya vishthitam.', en: 'Light of all lights, beyond darkness — wisdom, worth knowing, reached by wisdom, seated in every heart.', hi: 'ज्योतियों की भी ज्योति, अंधकार से परे कहा गया — ज्ञान, ज्ञेय, ज्ञानगम्य, सबके हृदय में स्थित।'},
  {n: 18, speaker: 'krishna', sa: 'इति क्षेत्रं तथा ज्ञानं ज्ञेयं चोक्तं समासतः। मद्भक्त एतद्विज्ञाय मद्भावायोपपद्यते॥', tr: 'Iti kshetram tatha jnanam jneyam choktam samasatah, madbhakta etadvijnaya madbhavayopapadyate.', en: 'Thus field, wisdom and the worth-knowing are told in brief — knowing this, my devotee grows fit for my being.', hi: 'इस प्रकार क्षेत्र, ज्ञान और ज्ञेय संक्षेप में कहे — इसे जानकर मेरा भक्त मेरे भाव को पाता है।'},
  {n: 19, speaker: 'krishna', sa: 'प्रकृतिं पुरुषं चैव विद्ध्यनादी उभावपि। विकारांश्च गुणांश्चैव विद्धि प्रकृतिसम्भवान्॥', tr: 'Prakritim purusham chaiva viddhyanadi ubhavapi, vikaranshcha gunanshchaiva viddhi prakritisambhavan.', en: 'Know nature and spirit both as beginningless — know changes and qualities as born of nature.', hi: 'प्रकृति और पुरुष दोनों को अनादि जानो — विकारों और गुणों को प्रकृति से उत्पन्न जानो।'},
  {n: 20, speaker: 'krishna', sa: 'कार्यकारणकर्तृत्वे हेतुः प्रकृतिरुच्यते। पुरुषः सुखदुःखानां भोक्तृत्वे हेतुरुच्यते॥', tr: 'Karyakaranakartritve hetuh prakritiruchyate, purushah sukhaduhkhanam bhoktritve heturuchyate.', en: 'Nature is called the cause of body, means and doing — spirit is called the cause of tasting joy and sorrow.', hi: 'कार्य-कारण-कर्तृत्व में प्रकृति हेतु कही जाती है — सुख-दुःख के भोक्तृत्व में पुरुष हेतु कहा जाता है।'},
  {n: 21, speaker: 'krishna', sa: 'पुरुषः प्रकृतिस्थो हि भुङ्क्ते प्रकृतिजान्गुणान्। कारणं गुणसङ्गोऽस्य सदसद्योनिजन्मसु॥', tr: 'Purushah prakritistho hi bhunkte prakritijangunan, karanam gunasangoasya sadasadyonijanmasu.', en: 'Spirit seated in nature tastes nature-born qualities — clinging to qualities causes birth in good or low wombs.', hi: 'प्रकृति में स्थित पुरुष प्रकृतिज गुणों को भोगता है — गुणों की आसक्ति ही शुभ-अशुभ योनियों में जन्म का कारण है।'},
  {n: 22, speaker: 'krishna', sa: 'उपद्रष्टानुमन्ता च भर्ता भोक्ता महेश्वरः। परमात्मेति चाप्युक्तो देहेऽस्मिन्पुरुषः परः॥', tr: 'Upadrashtanumanta cha bharta bhokta Maheshvarah, Paramatmeti chapyukto deheasminpurushah parah.', en: 'Watcher, approver, bearer, taster, great Lord — the highest spirit in this body is also called the supreme Self.', hi: 'उपद्रष्टा, अनुमंता, भर्ता, भोक्ता, महेश्वर — इस देह में स्थित पर पुरुष परमात्मा भी कहा गया है।'},
  {n: 23, speaker: 'krishna', sa: 'य एवं वेत्ति पुरुषं प्रकृतिं च गुणैः सह। सर्वथा वर्तमानोऽपि न स भूयोऽभिजायते॥', tr: 'Ya evam vetti purusham prakritim cha gunaih saha, sarvatha vartamanoapi na sa bhuyoabhijayate.', en: 'Who truly knows spirit and nature with its qualities — however placed, is not born again.', hi: 'जो पुरुष और गुणों सहित प्रकृति को इस प्रकार जानता है — वह कैसा भी बरते, पुनः जन्म नहीं लेता।'},
  {n: 24, speaker: 'krishna', sa: 'ध्यानेनात्मनि पश्यन्ति केचिदात्मानमात्मना। अन्ये साङ्ख्येन योगेन कर्मयोगेन चापरे॥', tr: 'Dhyanenatmani pashyanti kechidatmanamatmana, anye sankhyena yogena karmayogena chapare.', en: 'Some see the Self within by quiet focus, others by reasoned yoga, others by the yoga of deeds.', hi: 'कुछ ध्यान से आत्मा में आत्मा को आत्मा द्वारा देखते हैं, अन्य सांख्य योग से, अन्य कर्मयोग से।'},
  {n: 25, speaker: 'krishna', sa: 'अन्ये त्वेवमजानन्तः श्रुत्वान्येभ्य उपासते। तेऽपि चातितरन्त्येव मृत्युं श्रुतिपरायणाः॥', tr: 'Anye tvevamajanantah shrutvanyebhya upasate, teapi chatitarantyeva mrityum shrutiparayanah.', en: 'Others, not knowing this path, worship having heard from others — trusting the teaching, they too cross beyond death.', hi: 'अन्य जो इस प्रकार नहीं जानते, दूसरों से सुनकर उपासना करते हैं — श्रुति परायण वे भी मृत्यु को पार कर जाते हैं।'},
  {n: 26, speaker: 'krishna', sa: 'यावत्सञ्जायते किञ्चित्सत्त्वं स्थावरजङ्गमम्। क्षेत्रक्षेत्रज्ञसंयोगात्तद्विद्धि भरतर्षभ॥', tr: 'Yavatsanjayate kinchitsattvam sthavarajangamam, kshetrakshetrajnasamyogattadviddhi Bharatarshabha.', en: 'Whatever being is born, moving or still, know it as born of the meeting of field and knower, O chief of Bharatas.', hi: 'हे भरतश्रेष्ठ! स्थावर-जंगम जो भी सत्त्व उत्पन्न होता है, उसे क्षेत्र-क्षेत्रज्ञ के संयोग से जानो।'},
  {n: 27, speaker: 'krishna', sa: 'समं सर्वेषु भूतेषु तिष्ठन्तं परमेश्वरम्। विनश्यत्स्वविनश्यन्तं यः पश्यति स पश्यति॥', tr: 'Samam sarveshu bhuteshu tishthantam Parameshvaram, vinashyatsvavinashyantam yah pashyati sa pashyati.', en: 'Who sees the supreme Lord abiding alike in all beings, undying amid the dying — that one truly sees.', hi: 'जो समस्त प्राणियों में सम स्थित परमेश्वर को देखता है, नष्ट होते हुओं में अविनाशी को — वही देखता है।'},
  {n: 28, speaker: 'krishna', sa: 'समं पश्यन्हि सर्वत्र समवस्थितमीश्वरम्। न हिनस्त्यात्मनात्मानं ततो याति परां गतिम्॥', tr: 'Samam pashyanhi sarvatra samavasthitamishvaram, na hinastyatmanatmanam tato yati param gatim.', en: 'Seeing the Lord the same everywhere, one does not harm the Self by the self — then one reaches the highest goal.', hi: 'सर्वत्र सम स्थित ईश्वर को सम देखता हुआ आत्मा से आत्मा की हिंसा नहीं करता — तब परम गति पाता है।'},
  {n: 29, speaker: 'krishna', sa: 'प्रकृत्यैव च कर्माणि क्रियमाणानि सर्वशः। यः पश्यति तथात्मानमकर्तारं स पश्यति॥', tr: 'Prakrityaiva cha karmani kriyamanani sarvashah, yah pashyati tathatmanamakartaram sa pashyati.', en: 'Who sees all deeds done by nature alone everywhere, and the Self as no doer — that one truly sees.', hi: 'जो समस्त कर्मों को प्रकृति द्वारा ही होते देखता है, और आत्मा को अकर्ता — वही देखता है।'},
  {n: 30, speaker: 'krishna', sa: 'यदा भूतपृथग्भावमेकस्थमनुपश्यति। तत एव च विस्तारं ब्रह्म सम्पद्यते तदा॥', tr: 'Yada bhutaprithagbhavamekasthamanupashyati, tata eva cha vistaram Brahma sampadyate tada.', en: 'When one sees the separateness of beings resting in the One, spreading from that alone — then one grows one with Brahman.', hi: 'जब प्राणियों के पृथक भाव को एक में स्थित देखता है, और उसी से विस्तार — तब ब्रह्म को प्राप्त होता है।'},
  {n: 31, speaker: 'krishna', sa: 'अनादित्वान्निर्गुणत्वात्परमात्मायमव्ययः। शरीरस्थोऽपि कौन्तेय न करोति न लिप्यते॥', tr: 'Anaditvannirgunatvatparamatmayamavyayah, sharirasthoapi Kaunteya na karoti na lipyate.', en: 'Beginningless and beyond qualities, this changeless supreme Self — though housed in the body, Kaunteya, neither acts nor is stained.', hi: 'हे कौंतेय! अनादि और निर्गुण होने से यह अव्यय परमात्मा शरीर में रहकर भी न करता है न लिप्त होता है।'},
  {n: 32, speaker: 'krishna', sa: 'यथा सर्वगतं सौक्ष्म्यादाकाशं नोपलिप्यते। सर्वत्रावस्थितो देहे तथात्मा नोपलिप्यते॥', tr: 'Yatha sarvagatam saukshmyadakasham nopalipyate, sarvatravasthito dehe tathatma nopalipyate.', en: 'As space, all-pervading, is unstained by its fineness — so the Self, present everywhere in the body, is unstained.', hi: 'जैसे सर्वगत आकाश सूक्ष्म होने से लिप्त नहीं होता — वैसे देह में सर्वत्र स्थित आत्मा लिप्त नहीं होता।'},
  {n: 33, speaker: 'krishna', sa: 'यथा प्रकाशयत्येकः कृत्स्नं लोकमिमं रविः। क्षेत्रं क्षेत्री तथा कृत्स्नं प्रकाशयति भारत॥', tr: 'Yatha prakashayatyekah kritsnam lokamimam ravih, kshetram kshetri tatha kritsnam prakashayati Bharata.', en: 'As the one sun lights this whole world, so the knower lights the whole field, Bharata.', hi: 'हे भारत! जैसे एक सूर्य इस समस्त लोक को प्रकाशित करता है, वैसे क्षेत्री समस्त क्षेत्र को प्रकाशित करता है।'},
  {n: 34, speaker: 'krishna', sa: 'क्षेत्रक्षेत्रज्ञयोरेवमन्तरं ज्ञानचक्षुषा। भूतप्रकृतिमोक्षं च ये विदुर्यान्ति ते परम्॥', tr: 'Kshetrakshetrajnayorevamantaram jnanachakshusha, bhutaprakritimoksham cha ye viduryanti te param.', en: 'Who see with wisdom eyes the gap between field and knower, and release from the stuff of beings — they reach the highest.', hi: 'जो इस प्रकार क्षेत्र-क्षेत्रज्ञ का अंतर ज्ञानचक्षु से देखते हैं, और भूतप्रकृति से मोक्ष — वे परम को पाते हैं।'}
];
