import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter4Meta: GitaChapterDetail = {
  n: 4,
  title: {en: 'Chapter 4 · Jnana Karma Sannyasa Yoga', hi: 'अध्याय 4 · ज्ञान कर्म संन्यास योग'},
  summary: {
    en: 'Divine birth, the purpose of avataras, and action dissolving in knowledge. 42 verses.',
    hi: 'दिव्य जन्म, अवतार का प्रयोजन और ज्ञान में कर्म का विलय। 42 श्लोक।'
  }
};

export const chapter4Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'श्रीभगवानुवाच इमं विवस्वते योगं प्रोक्तवानहमव्ययम्। विवस्वान्मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत्॥', tr: 'Imam Vivasvate yogam proktavanahamavyayam, Vivasvanmanave praha Manurikshvakaveabravit.', en: 'I taught this timeless yoga to Vivasvan, who passed it to Manu, and Manu to Ikshvaku.', hi: 'मैंने यह अविनाशी योग विवस्वान को सुनाया, विवस्वान ने मनु को और मनु ने इक्ष्वाकु को सुनाया।'},
  {n: 2, speaker: 'krishna', sa: 'एवं परम्पराप्राप्तमिमं राजर्षयो विदुः। स कालेनेह महता योगो नष्टः परन्तप॥', tr: 'Evam paramparapraptamimam rajarshayo viduh, sa kaleneha mahata yogo nashtah Parantapa.', en: 'Handed down in succession, the royal sages knew it — but over long time, Arjuna, that yoga was lost.', hi: 'परंपरा से प्राप्त इस योग को राजर्षियों ने जाना, पर हे परंतप! लंबे काल में वह योग लुप्त हो गया।'},
  {n: 3, speaker: 'krishna', sa: 'स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः। भक्तोऽसि मे सखा चेति रहस्यं ह्येतदुत्तमम्॥', tr: 'Sa evayam maya teadya yogah proktah puratanah, bhaktoasi me sakha cheti rahasyam hyetaduttamam.', en: 'That same ancient yoga I tell you today, for you are my devotee and friend — and this is the highest secret.', hi: 'वही पुरातन योग आज मैंने तुम्हें सुनाया, क्योंकि तुम मेरे भक्त और सखा हो — यह उत्तम रहस्य है।'},
  {n: 4, speaker: 'arjuna', sa: 'अर्जुन उवाच अपरं भवतो जन्म परं जन्म विवस्वतः। कथमेतद्विजानीयां त्वमादौ प्रोक्तवानिति॥', tr: 'Aparam bhavato janma param janma Vivasvatah, kathametadvijaniyam tvamadau proktavaniti.', en: 'Your birth came later, Vivasvan’s much earlier — how am I to grasp that you taught it first?', hi: 'आपका जन्म तो बाद का है, विवस्वान का जन्म पहले का — यह कैसे समझूँ कि आपने पहले सुनाया था?'},
  {n: 5, speaker: 'krishna', sa: 'श्रीभगवानुवाच बहूनि मे व्यतीतानि जन्मानि तव चार्जुन। तान्यहं वेद सर्वाणि न त्वं वेत्थ परन्तप॥', tr: 'Bahuni me vyatitani janmani tava charjuna, tanyaham veda sarvani na tvam vettha Parantapa.', en: 'Many births of mine and yours have passed, Arjuna — I remember them all, you do not.', hi: 'हे अर्जुन! मेरे और तुम्हारे बहुत से जन्म बीत चुके हैं — मैं उन सबको जानता हूँ, तुम नहीं जानते।'},
  {n: 6, speaker: 'krishna', sa: 'अजोऽपि सन्नव्ययात्मा भूतानामीश्वरोऽपि सन्। प्रकृतिं स्वामधिष्ठाय सम्भवाम्यात्ममायया॥', tr: 'Ajoapi sannavyayatma bhutanamishvaroapi san, prakritim svamadhishthaya sambhavamyatmamayaya.', en: 'Though unborn, changeless, and lord of beings, I take birth through my own power, resting on my nature.', hi: 'अजन्मा और अविनाशी होकर भी, समस्त भूतों का ईश्वर होकर भी, अपनी प्रकृति में स्थित हो अपनी माया से प्रकट होता हूँ।'},
  {n: 7, speaker: 'krishna', sa: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥', tr: 'Yada yada hi dharmasya glanirbhavati Bharata, abhyutthanamadharmasya tadatmanam srijamyaham.', en: 'Whenever righteousness declines and wrong rises, Bharata, I bring myself forth.', hi: 'हे भारत! जब-जब धर्म की हानि और अधर्म की वृद्धि होती है, तब-तब मैं स्वयं को प्रकट करता हूँ।'},
  {n: 8, speaker: 'krishna', sa: 'परित्राणाय साधूनां विनाशाय च दुष्कृताम्। धर्मसंस्थापनार्थाय सम्भवामि युगे युगे॥', tr: 'Paritranaya sadhunam vinashaya cha dushkritam, dharmasamsthapanarthaya sambhavami yuge yuge.', en: 'To guard the good, to end the wicked, and to plant dharma firmly — I appear age after age.', hi: 'सज्जनों की रक्षा, दुष्टों के नाश और धर्म की स्थापना हेतु मैं युग-युग में प्रकट होता हूँ।'},
  {n: 9, speaker: 'krishna', sa: 'जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः। त्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन॥', tr: 'Janma karma cha me divyamevam yo vetti tattvatah, tyaktva deham punarjanma naiti mameti soarjuna.', en: 'Whoever truly knows my birth and work as divine leaves rebirth behind at death and reaches me.', hi: 'जो मेरे जन्म और कर्म को दिव्य जानता है, वह देह छोड़कर पुनर्जन्म नहीं पाता — मुझे प्राप्त होता है।'},
  {n: 10, speaker: 'krishna', sa: 'वीतरागभयक्रोधा मन्मया मामुपाश्रिताः। बहवो ज्ञानतपसा पूता मद्भावमागताः॥', tr: 'Vitaragabhayakrodha manmaya mamupashritah, bahavo jnanatapasa puta madbhavamagatah.', en: 'Freed from craving, fear and anger, absorbed in me, many were cleansed by wisdom’s fire and reached my state.', hi: 'राग, भय, क्रोध से मुक्त, मुझमें लीन बहुत से ज्ञानी तप से पवित्र हो मेरे भाव को प्राप्त हुए।'},
  {n: 11, speaker: 'krishna', sa: 'ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम्। मम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः॥', tr: 'Ye yatha mam prapadyante tamstathaiva bhajamyaham, mama vartmanuvartante manushyah Partha sarvashah.', en: 'As people turn to me, so I meet them — all mortals, Partha, walk my path in their own way.', hi: 'जो जैसे मेरी शरण आते हैं, मैं वैसे ही उनसे मिलता हूँ — सभी मनुष्य, पार्थ, मेरे ही मार्ग पर चलते हैं।'},
  {n: 12, speaker: 'krishna', sa: 'काङ्क्षन्तः कर्मणां सिद्धिं यजन्त इह देवताः। क्षिप्रं हि मानुषे लोके सिद्धिर्भवति कर्मजा॥', tr: 'Kankshantah karmanam siddhim yajanta iha devatah, kshipram hi manushe loke siddhirbhavati karmaja.', en: 'Craving quick fruits of work, people worship lesser gods here, for fruits come fast in the human world.', hi: 'कर्मों की सिद्धि चाहने वाले यहाँ देवताओं को पूजते हैं, क्योंकि मनुष्यलोक में कर्म से सिद्धि शीघ्र मिलती है।'},
  {n: 13, speaker: 'krishna', sa: 'चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः। तस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम्॥', tr: 'Chaturvarnyam maya srishtam gunakarmavibhagashah, tasya kartaramapi mam viddhyakartaramavyayam.', en: 'The four orders were shaped by me by nature and work — yet know me as their maker who acts not and changes never.', hi: 'चार वर्ण मैंने गुण-कर्म के विभाग से रचे — फिर भी मुझे उनका कर्ता होकर भी अकर्ता और अव्यय जानो।'},
  {n: 14, speaker: 'krishna', sa: 'न मां कर्माणि लिम्पन्ति न मे कर्मफले स्पृहा। इति मां योऽभिजानाति कर्मभिर्न स बध्यते॥', tr: 'Na mam karmani limpanti na me karmaphale spriha, iti mam yoabhijanati karmabhirna sa badhyate.', en: 'Deeds stain me not, and I crave no fruit — whoever knows me thus is not bound by deeds.', hi: 'मुझे कर्म लिप्त नहीं करते, फल की इच्छा नहीं है — जो मुझे ऐसा जानता है, वह कर्मों से नहीं बँधता।'},
  {n: 15, speaker: 'krishna', sa: 'एवं ज्ञात्वा कृतं कर्म पूर्वैरपि मुमुक्षुभिः। कुरु कर्मैव तस्मात्त्वं पूर्वैः पूर्वतरं कृतम्॥', tr: 'Evam jnatva kritam karma purvairapi mumukshubhih, kuru karmaiva tasmattvam purvaih purvataram kritam.', en: 'Knowing this, seekers of freedom in olden days still acted — so you too must act, as the ancients did.', hi: 'ऐसा जानकर प्राचीन मुमुक्षुओं ने भी कर्म किया — इसलिए तुम भी पूर्वजों जैसा कर्म करो।'},
  {n: 16, speaker: 'krishna', sa: 'किं कर्म किमकर्मेति कवयोऽप्यत्र मोहिताः। तत्ते कर्म प्रवक्ष्यामि यज्ज्ञात्वा मोक्ष्यसेऽशुभात्॥', tr: 'Kim karma kimakarmeti kavayoapyatra mohitah, tatte karma pravakshyami yajjnatva mokshyaseashubhat.', en: 'What is action, what is inaction — even poets are puzzled — I shall teach you the work that frees from evil.', hi: 'कर्म क्या, अकर्म क्या — ज्ञानी भी यहाँ मोहित हैं — वह कर्म तुम्हें बताता हूँ जिसे जानकर अशुभ से मुक्त होगे।'},
  {n: 17, speaker: 'krishna', sa: 'कर्मणो ह्यपि बोद्धव्यं बोद्धव्यं च विकर्मणः। अकर्मणश्च बोद्धव्यं गहना कर्मणो गतिः॥', tr: 'Karmano hyapi boddhavyam boddhavyam cha vikarmanah,akarmanashcha boddhavyam gahana karmano gatih.', en: 'One must grasp right action, wrong action, and stillness — for the way of action runs deep.', hi: 'कर्म, विकर्म और अकर्म — तीनों को जानना चाहिए, क्योंकि कर्म की गति गहन है।'},
  {n: 18, speaker: 'krishna', sa: 'कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः। स बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत्॥', tr: 'Karmanyakarma yah pashyedakarmani cha karma yah, sa buddhimanmanushyeshu sa yuktah kritsnakarmakrit.', en: 'Whoever sees stillness within action and action within stillness is wise among mortals, steady, a doer of all.', hi: 'जो कर्म में अकर्म और अकर्म में कर्म देखता है, वही मनुष्यों में बुद्धिमान है — वही योगी, पूर्ण कर्म करने वाला।'},
  {n: 19, speaker: 'krishna', sa: 'यस्य सर्वे समारम्भाः कामसङ्कल्पवर्जिताः। ज्ञानाग्निदग्धकर्माणं तमाहुः पण्डितं बुधाः॥', tr: 'Yasya sarve samarambhah kamasankalpavarjitah, jnanagnidagdhakarmanam tamahuh panditam budhah.', en: 'Whose every venture is free of selfish craving, whose deeds wisdom’s fire has burnt — the learned call him wise.', hi: 'जिसके सारे आरंभ कामना-संकल्प से रहित हैं, जिसके कर्म ज्ञानाग्नि से दग्ध हैं — उसे ज्ञानी पंडित कहते हैं।'},
  {n: 20, speaker: 'krishna', sa: 'त्यक्त्वा कर्मफलासङ्गं नित्यतृप्तो निराश्रयः। कर्मण्यभिप्रवृत्तोऽपि नैव किञ्चित्करोति सः॥', tr: 'Tyaktva karmaphalasangam nityatripto nirashrayah, karmanyabhipravrittoapi naiva kinchitkaroti sah.', en: 'Dropping clinging to fruits, ever content, leaning on nothing — though busy in work, he does nothing binding.', hi: 'फल की आसक्ति छोड़, सदा तृप्त, निराश्रय रहकर कर्म करता हुआ भी वह कुछ नहीं करता।'},
  {n: 21, speaker: 'krishna', sa: 'निराशीर्यतचित्तात्मा त्यक्तसर्वपरिग्रहः। शारीरं केवलं कर्म कुर्वन्नाप्नोति किल्बिषम्॥', tr: 'Nirashiryatachittatma tyaktasarvaparigrahah, shariram kevalam karma kurvannapnoti kilbisham.', en: 'Wanting nothing, mastered in mind and self, owning nothing — doing mere bodily deeds, he gathers no stain.', hi: 'आशारहित, संयत चित्त, सर्व संग्रह त्यागकर केवल शरीर-निर्वाह हेतु कर्म करता हुआ पाप नहीं पाता।'},
  {n: 22, speaker: 'krishna', sa: 'यदृच्छालाभसन्तुष्टो द्वन्द्वातीतो विमत्सरः। समः सिद्धावसिद्धौ च कृत्वापि न निबध्यते॥', tr: 'Yadrichchhalabhasantushto dvandvatito vimatsarah, samah siddhavasiddhau cha kritvapi na nibadhyate.', en: 'Content with what comes, beyond opposites, free of envy, level in gain and loss — acting, he is not bound.', hi: 'जो मिले उसी में संतुष्ट, द्वंद्वों से परे, ईर्ष्याहीन, सिद्धि-असिद्धि में सम — कर्म करके भी नहीं बँधता।'},
  {n: 23, speaker: 'krishna', sa: 'गतसङ्गस्य मुक्तस्य ज्ञानावस्थितचेतसः। यज्ञायाचरतः कर्म समग्रं प्रविलीयते॥', tr: 'Gatasangasya muktasya jnanavasthitachetasah, yajnayacharatah karma samagram praviliyate.', en: 'For one freed of clinging, steady in wisdom, acting as an offering — all his work melts away.', hi: 'आसक्तिरहित, मुक्त, ज्ञान में स्थित हो यज्ञभाव से कर्म करने वाले के समस्त कर्म विलीन हो जाते हैं।'},
  {n: 24, speaker: 'krishna', sa: 'ब्रह्मार्पणं ब्रह्म हविर्ब्रह्माग्नौ ब्रह्मणा हुतम्। ब्रह्मैव तेन गन्तव्यं ब्रह्मकर्मसमाधिना॥', tr: 'Brahmarpanam Brahma havirBrahmagnau Brahmana hutam, Brahmaiva tena gantavyam Brahmakarmasamadhina.', en: 'The offering is the Whole, the gift is the Whole, poured by the Whole into the Whole’s fire — he who sees this reaches the Whole.', hi: 'अर्पण ब्रह्म, हवि ब्रह्म, अग्नि में आहुति देने वाला ब्रह्म — ब्रह्म-कर्म में स्थिर रहने वाला ब्रह्म को ही पाता है।'},
  {n: 25, speaker: 'krishna', sa: 'दैवमेवापरे यज्ञं योगिनः पर्युपासते। ब्रह्माग्नावपरे यज्ञं यज्ञेनैवोपजुह्वति॥', tr: 'Daivamevapare yajnam yoginah paryupasate, Brahmagnavapare yajnam yajnenaivopajuhvati.', en: 'Some seekers honour the gods in worship, others offer the self as oblation into the fire of the Whole.', hi: 'कोई योगी देवताओं का यज्ञ करते हैं, कोई ब्रह्माग्नि में आत्मा की ही आहुति देते हैं।'},
  {n: 26, speaker: 'krishna', sa: 'श्रोत्रादीनीन्द्रियाण्यन्ये संयमाग्निषु जुह्वति। शब्दादीन्विषयानन्य इन्द्रियाग्निषु जुह्वति॥', tr: 'Shrotradinindriyanyanye samyamaghnishu juhvati, shabdadinvishayananya indriyagnishu juhvati.', en: 'Some pour the senses into the fire of restraint, others pour sense-objects into the fire of the senses.', hi: 'कोई श्रोत्र आदि इंद्रियों को संयमाग्नि में होमते हैं, कोई शब्द आदि विषयों को इंद्रियाग्नि में होमते हैं।'},
  {n: 27, speaker: 'krishna', sa: 'सर्वाणीन्द्रियकर्माणि प्राणकर्माणि चापरे। आत्मसंयमयोगाग्नौ जुह्वति ज्ञानदीपिते॥', tr: 'Sarvanindriyakarmani pranakarmani chapare, atmasamyamayogagnau juhvati jnanadipite.', en: 'Others pour every sense-act and breath-act into the wisdom-lit fire of self-mastery.', hi: 'कोई समस्त इंद्रिय-कर्म और प्राण-कर्म को ज्ञान से प्रज्वलित आत्मसंयम रूपी अग्नि में होमते हैं।'},
  {n: 28, speaker: 'krishna', sa: 'द्रव्ययज्ञास्तपोयज्ञा योगयज्ञास्तथापरे। स्वाध्यायज्ञानयज्ञाश्च यतयः संशितव्रताः॥', tr: 'Dravyayajnastapoyajna yogayajnastathapare, svadhyayajnana yajnashcha yatayah samshitavratah.', en: 'Some give wealth as offering, some austerity, some practice, some study and wisdom — strivers of sharpened vows.', hi: 'कोई द्रव्य-यज्ञ, कोई तप-यज्ञ, कोई योग-यज्ञ, कोई स्वाध्याय-ज्ञान-यज्ञ करते हैं — तीक्ष्ण व्रत वाले यत्नशील।'},
  {n: 29, speaker: 'krishna', sa: 'अपाने जुह्वति प्राणं प्राणेऽपानं तथापरे। प्राणापानगती रुद्ध्वा प्राणायामपरायणाः॥', tr: 'Apane juhvati pranam praneapanam tathapare, pranapanagati ruddhva pranayamaparayanah.', en: 'Some offer the outward breath into the inward, and the inward into the outward — devoted to breath-restraint, checking both flows.', hi: 'कोई अपान में प्राण को, प्राण में अपान को होमते हैं — प्राणायाम में तत्पर होकर दोनों गतियों को रोकते हैं।'},
  {n: 30, speaker: 'krishna', sa: 'अपरे नियताहाराः प्राणान्प्राणेषु जुह्वति। सर्वेऽप्येते यज्ञविदो यज्ञक्षपितकल्मषाः॥', tr: 'Apare niyataharah prananpraneshu juhvati, sarveapyete yajnavido yajnakshapitakalmashah.', en: 'Others, measured in food, offer breath into breath — all these know offering, and offering has worn away their stain.', hi: 'कोई नियमित आहार वाले प्राणों में प्राणों को होमते हैं — ये सभी यज्ञ को जानने वाले, यज्ञ से पाप धो चुके हैं।'},
  {n: 31, speaker: 'krishna', sa: 'यज्ञशिष्टामृतभुजो यान्ति ब्रह्म सनातनम्। नायं लोकोऽस्त्ययज्ञस्य कुतोऽन्यः कुरुसत्तम॥', tr: 'Yajnashishtamritabhujo yanti Brahma sanatanam, nayam lokoastyayajnasya kutoanyah Kurusattama.', en: 'Who taste the nectar left from offering reach the timeless Whole — for the non-giver, best of Kurus, not even this world is sweet, let alone the next.', hi: 'यज्ञ से बचे अमृत को भोगने वाले सनातन ब्रह्म को पाते हैं — यज्ञ न करने वाले को यह लोक भी नहीं, परलोक कहाँ से, कुरुश्रेष्ठ?'},
  {n: 32, speaker: 'krishna', sa: 'एवं बहुविधा यज्ञा वितता ब्रह्मणो मुखे। कर्मजान्विद्धि तान्सर्वानेवं ज्ञात्वा विमोक्ष्यसे॥', tr: 'Evam bahuvidha yajna vitata Brahmano mukhe, karmajanviddhi tansarvan evam jnatva vimokshyase.', en: 'So many offerings lie spread before the Whole — know them all as born of work, and knowing this you shall be free.', hi: 'ऐसे बहुत प्रकार के यज्ञ ब्रह्म के मुख में फैले हैं — सबको कर्म से उत्पन्न जानो; ऐसा जानकर मुक्त होगे।'},
  {n: 33, speaker: 'krishna', sa: 'श्रेयान्द्रव्यमयाद्यज्ञाज्ज्ञानयज्ञः परन्तप। सर्वं कर्माखिलं पार्थ ज्ञाने परिसमाप्यते॥', tr: 'Shreyandravyamayadyajnajjnanayajnah Parantapa, sarvam karmakhilam Partha jnane parisamapyate.', en: 'Better than gifts of goods is the offering of wisdom, Arjuna — for every deed finds its end in wisdom.', hi: 'हे परंतप! द्रव्य-यज्ञ से ज्ञान-यज्ञ श्रेष्ठ है — पार्थ! समस्त कर्म ज्ञान में समाप्त होते हैं।'},
  {n: 34, speaker: 'krishna', sa: 'तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया। उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः॥', tr: 'Tadviddhi pranipatena pariprashnena sevaya, upadekshyanti te jnanam jnaninastattvadarshinah.', en: 'Learn it by bowing low, by questioning, by serving — the seers of truth will teach you that wisdom.', hi: 'उसे प्रणाम, प्रश्न और सेवा से जानो — तत्त्वदर्शी ज्ञानी तुम्हें वह ज्ञान उपदेश करेंगे।'},
  {n: 35, speaker: 'krishna', sa: 'यज्ज्ञात्वा न पुनर्मोहमेवं यास्यसि पाण्डव। येन भूतान्यशेषेण द्रक्ष्यस्यात्मन्यथो मयि॥', tr: 'Yajjnatva na punarmohamevam yasyasi Pandava, yena bhutanyasheshena drakshyasyatmanyatho mayi.', en: 'Knowing it, Pandava, you shall not fall into delusion again — by it you shall see all beings in your self, and then in me.', hi: 'उसे जानकर, पांडव, फिर मोह में नहीं पड़ोगे — उससे समस्त भूतों को आत्मा में और फिर मुझमें देखोगे।'},
  {n: 36, speaker: 'krishna', sa: 'अपि चेदसि पापेभ्यः सर्वेभ्यः पापकृत्तमः। सर्वं ज्ञानप्लवेनैव वृजिनं सन्तरिष्यसि॥', tr: 'Api chedasi papebhyah sarvebhyah papakrittamah, sarvam jnanaplavenaiva vrijinam santarishyasi.', en: 'Even if you were the worst of wrongdoers, you would cross all evil on wisdom’s raft alone.', hi: 'यदि तुम सब पापियों से भी बड़े पापी हो, तो भी ज्ञान रूपी नाव से समस्त पाप तर जाओगे।'},
  {n: 37, speaker: 'krishna', sa: 'यथैधांसि समिद्धोऽग्निर्भस्मसात्कुरुतेऽर्जुन। ज्ञानाग्निः सर्वकर्माणि भस्मसात्कुरुते तथा॥', tr: 'Yathaidhamsi samiddhoagnirbhasmasatkuruteArjuna, jnanagnih sarvakarmani bhasmasatkurute tatha.', en: 'As kindled fire turns logs to ash, Arjuna, so wisdom’s fire turns all deeds to ash.', hi: 'जैसे प्रज्वलित अग्नि ईंधन को भस्म कर देती है, अर्जुन, वैसे ही ज्ञानाग्नि समस्त कर्मों को भस्म कर देती है।'},
  {n: 38, speaker: 'krishna', sa: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते। तत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति॥', tr: 'Na hi jnanena sadrisham pavitramiha vidyate, tatsvayam yogasamsiddhah kalenatmani vindati.', en: 'Nothing here cleanses like wisdom — the one ripened in practice finds it within himself in time.', hi: 'ज्ञान के समान पवित्र कुछ नहीं — योग में सिद्ध पुरुष समय पर उसे अपने भीतर ही पाता है।'},
  {n: 39, speaker: 'krishna', sa: 'श्रद्धावाँल्लभते ज्ञानं तत्परः संयतेन्द्रियः। ज्ञानं लब्ध्वा परां शान्तिमचिरेणाधिगच्छति॥', tr: 'Shraddhavanllabhate jnanam tatparah samyatendriyah, jnanam labdhva param shantimachirenadhigachchhati.', en: 'The trusting, the devoted, the sense-mastered gain wisdom — and with wisdom, swift supreme peace.', hi: 'श्रद्धावान, तत्पर, जितेंद्रिय ज्ञान पाता है — ज्ञान पाकर शीघ्र परम शांति पाता है।'},
  {n: 40, speaker: 'krishna', sa: 'अज्ञश्चाश्रद्दधानश्च संशयात्मा विनश्यति। नायं लोकोऽस्ति न परो न सुखं संशयात्मनः॥', tr: 'Ajnashchashraddadhanashcha samshayatma vinashyati, nayam lokoasti na paro na sukham samshayatmanah.', en: 'The ignorant, the faithless, the doubting perish — for the doubter there is neither this world nor the next, nor joy.', hi: 'अज्ञानी, श्रद्धाहीन, संशयी नष्ट होता है — संशयी के लिए न यह लोक है, न परलोक, न सुख।'},
  {n: 41, speaker: 'krishna', sa: 'योगसंन्यस्तकर्माणं ज्ञानसञ्छिन्नसंशयम्। आत्मवन्तं न कर्माणि निबध्नन्ति धनञ्जय॥', tr: 'Yogasannyastakarmanam jnanasanchhinnasamshayam, atmavantam na karmani nibadhnanti Dhananjaya.', en: 'Deeds bind not the self-mastered, Dhananjaya, whose works are laid down in practice and whose doubts wisdom has cut.', hi: 'योग से कर्मों का संन्यास करने वाले, ज्ञान से संशय काटने वाले आत्मवान को कर्म नहीं बाँधते, धनंजय।'},
  {n: 42, speaker: 'krishna', sa: 'तस्मादज्ञानसम्भूतं हृत्स्थं ज्ञानासिनात्मनः। छित्त्वैनं संशयं योगमातिष्ठोत्तिष्ठ भारत॥', tr: 'Tasmadajnanasambhutam hritstham jnanasinatmanah, chhittvainam samshayam yogamatishthottishtha Bharata.', en: 'So cut with wisdom’s sword the doubt in your heart born of ignorance, take up practice, and rise, Bharata.', hi: 'इसलिए अज्ञान से उपजे हृदयस्थ संशय को ज्ञान-खड्ग से काटकर योग में स्थित होओ और उठो, भारत।'}
];
