import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter9Meta: GitaChapterDetail = {
  n: 9,
  title: {en: 'Chapter 9 · Raja Vidya Raja Guhya Yoga', hi: 'अध्याय 9 · राज विद्या राज गुह्य योग'},
  summary: {
    en: 'The royal knowledge — devotion that carries the devotee across. 34 verses.',
    hi: 'राजविद्या — भक्त को पार लगाने वाली भक्ति। 34 श्लोक।'
  }
};

export const chapter9Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'इदं तु ते गुह्यतमं प्रवक्ष्याम्यनसूयवे। ज्ञानं विज्ञानसहितं यज्ज्ञात्वा मोक्ष्यसेऽशुभात्॥', tr: 'Idam tu te guhyatamam pravakshyamyanasuyave, jnanam vijnanasahitam yajjnatva mokshyaseashubhat.', en: 'To you who do not cavil I will speak this deepest secret — knowledge with realisation, freeing you from sorrow.', hi: 'हे अनसूय! तुम्हें यह गुह्यतम ज्ञान विज्ञानसहित बताऊँगा, जिसे जानकर तुम अशुभ से मुक्त होगे।'},
  {n: 2, speaker: 'krishna', sa: 'राजविद्या राजगुह्यं पवित्रमिदमुत्तमम्। प्रत्यक्षावगमं धर्म्यं सुसुखं कर्तुमव्ययम्॥', tr: 'Rajavidya rajaguhyam pavitramidamuttamam, pratyakshavagamam dharmyam susukham kartumavyayam.', en: 'This is royal knowledge, the royal secret, pure and supreme — seen directly, righteous, joyful to practise, imperishable.', hi: 'यह राजविद्या, राजगुह्य, पवित्र और उत्तम है — प्रत्यक्ष अनुभव देने वाली, धर्ममय, सुख से साध्य और अव्यय।'},
  {n: 3, speaker: 'krishna', sa: 'अश्रद्दधानाः पुरुषा धर्मस्यास्य परन्तप। अप्राप्य मां निवर्तन्ते मृत्युसंसारवर्त्मनि॥', tr: 'Ashraddadhanah purusha dharmasyasya parantapa, aprapya mam nivartante mrityusamsaravartmani.', en: 'Those without faith in this path miss me, scorcher of foes, and wander the road of death and rebirth.', hi: 'हे परंतप! इस धर्म में श्रद्धा न रखने वाले मुझे पाए बिना मृत्यु-संसार के मार्ग में लौट आते हैं।'},
  {n: 4, speaker: 'krishna', sa: 'मया ततमिदं सर्वं जगदव्यक्तमूर्तिना। मत्स्थानि सर्वभूतानि न चाहं तेष्ववस्थितः॥', tr: 'Maya tatamidam sarvam jagadavyaktamurtina, matsthani sarvabhutani na chaham teshvavasthitah.', en: 'By me, unseen, all this world is pervaded — all beings rest in me, yet I rest not in them.', hi: 'मुझ अव्यक्तमूर्ति से यह समस्त जगत व्याप्त है — सभी भूत मुझमें स्थित हैं, पर मैं उनमें स्थित नहीं।'},
  {n: 5, speaker: 'krishna', sa: 'न च मत्स्थानि भूतानि पश्य मे योगमैश्वरम्। भूतभृन्न च भूतस्थो ममात्मा भूतभावनः॥', tr: 'Na cha matsthani bhutani pashya me yogamaishvaram, bhutabhrinna cha bhutastho mamatma bhutabhavanah.', en: 'And yet beings dwell not in me — behold my sovereign mystery: I bear all beings, yet stand apart, their source.', hi: 'और भूत मुझमें स्थित भी नहीं — मेरे ईश्वरीय योग को देखो; भूतों का भरण करने वाला मेरा आत्मा उनमें स्थित नहीं।'},
  {n: 6, speaker: 'krishna', sa: 'यथाकाशस्थितो नित्यं वायुः सर्वत्रगो महान्। तथा सर्वाणि भूतानि मत्स्थानीत्युपधारय॥', tr: 'Yathakashasthito nityam vayuh sarvatrago mahan, tatha sarvani bhutani matsthanityupadharaya.', en: 'As the mighty wind ever moves within space, so all beings abide in me — know this.', hi: 'जैसे सर्वत्र बहने वाली महान वायु सदा आकाश में स्थित है, वैसे ही समस्त भूत मुझमें स्थित जानो।'},
  {n: 7, speaker: 'krishna', sa: 'सर्वभूतानि कौन्तेय प्रकृतिं यान्ति मामिकाम्। कल्पक्षये पुनस्तानि कल्पादौ विसृजाम्यहम्॥', tr: 'Sarvabhutani Kaunteya prakritim yanti mamikam, kalpakshaye punastani kalpatau visrijamyaham.', en: 'All beings merge into my nature at the age’s end, Kaunteya, and I send them forth again at its dawn.', hi: 'हे कौन्तेय! कल्पक्षय में सभी भूत मेरी प्रकृति में लीन होते हैं, और कल्पारंभ में मैं उन्हें पुनः रचता हूँ।'},
  {n: 8, speaker: 'krishna', sa: 'प्रकृतिं स्वामवष्टभ्य विसृजामि पुनः पुनः। भूतग्राममिमं कृत्स्नमवशं प्रकृतेर्वशात्॥', tr: 'Prakritim svamavashtabhya visrijami punah punah, bhutagramamimam kritsnamavasham prakritervashat.', en: 'Leaning on my nature, I send forth again and again this helpless host, bound by its own nature.', hi: 'अपनी प्रकृति का आश्रय लेकर इस समस्त परवश भूतसमूह को प्रकृति के वश से बार-बार रचता हूँ।'},
  {n: 9, speaker: 'krishna', sa: 'न च मां तानि कर्माणि निबध्नन्ति धनञ्जय। उदासीनवदासीनमसक्तं तेषु कर्मसु॥', tr: 'Na cha mam tani karmani nibadhnanti Dhananjaya, udasinavadasinamasaktam teshu karmasu.', en: 'These acts do not bind me, Dhananjaya — I sit apart, as it were, unattached to them.', hi: 'हे धनंजय! वे कर्म मुझे नहीं बाँधते — मैं उदासीन की भाँति उन कर्मों में अनासक्त रहता हूँ।'},
  {n: 10, speaker: 'krishna', sa: 'मयाध्यक्षेण प्रकृतिः सूयते सचराचरम्। हेतुनानेन कौन्तेय जगद्विपरिवर्तते॥', tr: 'Mayadhyakshena prakritih suyate sacharacharam, hetunanena Kaunteya jagadviparivartate.', en: 'Under my gaze nature brings forth the moving and unmoving — for this reason the world turns, Kaunteya.', hi: 'मेरी अध्यक्षता में प्रकृति चर-अचर को रचती है — हे कौन्तेय! इसी हेतु जगत परिवर्तनशील है।'},
  {n: 11, speaker: 'krishna', sa: 'अवजानन्ति मां मूढा मानुषीं तनुमाश्रितम्। परं भावमजानन्तो मम भूतमहेश्वरम्॥', tr: 'Avajananti mam mudha manushim tanumashritam, param bhavamajananto mama bhutamaheshvaram.', en: 'Fools despise me in human form, blind to my higher being as great lord of all.', hi: 'मूढ लोग मानव देह धारण किए मुझे तुच्छ मानते हैं — समस्त भूतों के महेश्वर मेरे परम भाव को नहीं जानते।'},
  {n: 12, speaker: 'krishna', sa: 'मोघाशा मोघकर्माणो मोघज्ञाना विचेतसः। राक्षसीमासुरीं चैव प्रकृतिं मोहिनीं श्रिताः॥', tr: 'Moghasha moghakarmano moghajnana vichetasah, rakshasimasurim chaiva prakritim mohinim shritah.', en: 'Vain their hopes, vain their deeds and knowledge — senseless, they cling to a bewildering savage nature.', hi: 'व्यर्थ आशा, व्यर्थ कर्म और व्यर्थ ज्ञान वाले विचेतस राक्षसी और आसुरी मोहिनी प्रकृति का आश्रय लेते हैं।'},
  {n: 13, speaker: 'krishna', sa: 'महात्मानस्तु मां पार्थ दैवीं प्रकृतिमाश्रिताः। भजन्त्यनन्यमनसो ज्ञात्वा भूतादिमव्ययम्॥', tr: 'Mahatmanastu mam Partha daivim prakritimashritah, bhajantyananyamanaso jnatva bhutadimavyayam.', en: 'But great souls, Partha, sheltered in divine nature, worship me single-minded, knowing me as changeless source.', hi: 'परंतु हे पार्थ! दैवी प्रकृति वाले महात्मा मुझे भूतों का आदि और अव्यय जानकर अनन्य मन से भजते हैं।'},
  {n: 14, speaker: 'krishna', sa: 'सततं कीर्तयन्तो मां यतन्तश्च दृढव्रताः। नमस्यन्तश्च मां भक्त्या नित्ययुक्ता उपासते॥', tr: 'Satatam kirtayanto mam yatantashcha dridhavratah, namasyantashcha mam bhaktya nityayukta upasate.', en: 'Ever singing my praise, striving with firm vows, bowing in devotion, they worship me in constant union.', hi: 'निरंतर मेरा कीर्तन करते, दृढ व्रत से यत्न करते, भक्ति से नमन करते हुए नित्ययुक्त होकर उपासना करते हैं।'},
  {n: 15, speaker: 'krishna', sa: 'ज्ञानयज्ञेन चाप्यन्ये यजन्तो मामुपासते। एकत्वेन पृथक्त्वेन बहुधा विश्वतोमुखम्॥', tr: 'Jnanayajnena chapyanye yajanto mamupasate, ekatvena prithaktvena bahudha vishvatomukham.', en: 'Others worship me through wisdom’s sacrifice — as one, as many, as the many-faced all.', hi: 'अन्य लोग ज्ञानयज्ञ से मेरा यजन करते हुए उपासना करते हैं — एकत्व, पृथक्त्व और बहुधा रूप वाले विश्वतोमुख की।'},
  {n: 16, speaker: 'krishna', sa: 'अहं क्रतुरहं यज्ञः स्वधाहमहमौषधम्। मन्त्रोऽहमहमेवाज्यमहमग्निरहं हुतम्॥', tr: 'Aham kraturaham yajnah svadhahamahamaushadham, mantroahamahamevajyamahamagniraham hutam.', en: 'I am the rite and the sacrifice, the offering to forebears and the healing herb — mantra, ghee, fire, and oblation.', hi: 'क्रतु मैं हूँ, यज्ञ मैं हूँ, स्वधा मैं हूँ, औषधि मैं हूँ — मंत्र, घृत, अग्नि और हवन भी मैं ही हूँ।'},
  {n: 17, speaker: 'krishna', sa: 'पिताहमस्य जगतो माता धाता पितामहः। वेद्यं पवित्रमोङ्कार ऋक्साम यजुरेव च॥', tr: 'Pitahamasya jagato mata dhata pitamahah, vedyam pavitramonkara riksama yajureva cha.', en: 'I am this world’s father, mother, ordainer, grandsire — the knowable, the pure, the syllable Om, and the three Vedas.', hi: 'इस जगत का पिता, माता, धाता और पितामह मैं हूँ — ज्ञेय, पवित्र, ओंकार तथा ऋक्, साम और यजुर्वेद भी मैं हूँ।'},
  {n: 18, speaker: 'krishna', sa: 'गतिर्भर्ता प्रभुः साक्षी निवासः शरणं सुहृत्। प्रभवः प्रलयः स्थानं निधानं बीजमव्ययम्॥', tr: 'Gatirbharta prabhuh sakshi nivasah sharanam suhrit, prabhavah pralayah sthanam nidhanam bijamavyayam.', en: 'I am the goal, sustainer, master, witness, home, refuge, and friend — origin, dissolution, ground, treasure, and imperishable seed.', hi: 'गति, भर्ता, प्रभु, साक्षी, निवास, शरण और सुहृद मैं हूँ — उत्पत्ति, प्रलय, स्थान, निधान और अव्यय बीज भी मैं हूँ।'},
  {n: 19, speaker: 'krishna', sa: 'तपाम्यहमहं वर्षं निगृह्णाम्युत्सृजामि च। अमृतं चैव मृत्युश्च सदसच्चाहमर्जुन॥', tr: 'Tapamyahamaham varsham nigrihnamyutsrijami cha, amritam chaiva mrityushcha sadasachchahamarjuna.', en: 'I give heat, I hold back and send forth the rain — I am deathlessness and death, being and non-being, Arjuna.', hi: 'मैं ही तपता हूँ, वर्षा को रोकता और बरसाता हूँ — हे अर्जुन! अमृत और मृत्यु, सत् और असत् भी मैं ही हूँ।'},
  {n: 20, speaker: 'krishna', sa: 'त्रैविद्या मां सोमपाः पूतपापा यज्ञैरिष्ट्वा स्वर्गतिं प्रार्थयन्ते। ते पुण्यमासाद्य सुरेन्द्रलोकमश्नन्ति दिव्यान्दिवि देवभोगान्॥', tr: 'Traividya mam somapah putapapa yajnairishtva svargatim prarthayante, te punyamasadya surendralokamashnanti divyandivi devabhog an.', en: 'Versed in the three Vedas, cleansed of sin, they honour me with rites and pray for heaven — and enjoy its shining delights.', hi: 'तीनों वेदों के ज्ञाता, सोमपान से पापमुक्त होकर यज्ञों से मेरा पूजन कर स्वर्ग माँगते हैं — और दिव्य देवभोग भोगते हैं।'},
  {n: 21, speaker: 'krishna', sa: 'ते तं भुक्त्वा स्वर्गलोकं विशालं क्षीणे पुण्ये मर्त्यलोकं विशन्ति। एवं त्रयीधर्ममनुप्रपन्ना गतागतं कामकामा लभन्ते॥', tr: 'Te tam bhuktva svargalokam vishalam kshine punye martyalokam vishanti, evam trayidharmamanuprapanna gatagatam kamakama labhante.', en: 'Having tasted vast heaven, when merit fades they return to earth — followers of Vedic rites, craving, come and go.', hi: 'उस विशाल स्वर्ग को भोगकर पुण्य क्षीण होने पर वे मृत्युलोक में आते हैं — कामनाशील त्रयीधर्मी आवागमन पाते हैं।'},
  {n: 22, speaker: 'krishna', sa: 'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते। तेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥', tr: 'Ananyashchintayanto mam ye janah paryupasate, tesham nityabhiyuktanam yogakshemam vahamyaham.', en: 'To those who worship me with single thought, ever devoted, I bear the burden of their welfare.', hi: 'अनन्य भाव से मेरा चिंतन करते हुए जो उपासना करते हैं, उन नित्ययुक्तों का योगक्षेम मैं वहन करता हूँ।'},
  {n: 23, speaker: 'krishna', sa: 'येऽप्यन्यदेवता भक्ता यजन्ते श्रद्धयान्विताः। तेऽपि मामेव कौन्तेय यजन्त्यविधिपूर्वकम्॥', tr: 'Yeap yanyadevata bhakta yajante shraddhayanvitah, teapi mameva Kaunteya yajantyavidhipurvakam.', en: 'Even devotees of other gods, worshipping in faith, Kaunteya, worship me alone — though not by the true rule.', hi: 'हे कौन्तेय! अन्य देवताओं के श्रद्धावान भक्त भी मुझे ही पूजते हैं — किंतु अविधिपूर्वक।'},
  {n: 24, speaker: 'krishna', sa: 'अहं हि सर्वयज्ञानां भोक्ता च प्रभुरेव च। न तु मामभिजानन्ति तत्त्वेनातश्च्यवन्ति ते॥', tr: 'Aham hi sarvayajnanam bhokta cha prabhureva cha, na tu mamabhijananti tattvenatashchyavanti te.', en: 'For I am the enjoyer and lord of all sacrifices — not knowing me in truth, they fall away.', hi: 'मैं ही समस्त यज्ञों का भोक्ता और प्रभु हूँ — पर मुझे तत्त्व से न जानने के कारण वे च्युत हो जाते हैं।'},
  {n: 25, speaker: 'krishna', sa: 'यान्ति देवव्रता देवान्पितॄन्यान्ति पितृव्रताः। भूतानि यान्ति भूतेज्या यान्ति मद्याजिनोऽपि माम्॥', tr: 'Yanti devavrata devanpitrinyanti pitrivratah, bhutani yanti bhutejya yanti madyajinoapi mam.', en: 'God-vowed reach the gods, ancestor-vowed the ancestors, spirit-worshippers the spirits — my worshippers reach me.', hi: 'देवव्रती देवों को, पितृव्रती पितरों को, भूतपूजक भूतों को पाते हैं — मेरे पूजक मुझे पाते हैं।'},
  {n: 26, speaker: 'krishna', sa: 'पत्रं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति। तदहं भक्त्युपहृतमश्नामि प्रयतात्मनः॥', tr: 'Patram pushpam phalam toyam yo me bhaktya prayachchhati, tadaham bhaktyupahritamashnami prayatatmanah.', en: 'Leaf, flower, fruit, or water offered with love — I gladly accept that loving gift of the pure-hearted.', hi: 'पत्र, पुष्प, फल या जल जो मुझे भक्ति से अर्पित करता है, उस शुद्धचित्त की भक्तिभेंट मैं स्वीकार करता हूँ।'},
  {n: 27, speaker: 'krishna', sa: 'यत्करोषि यदश्नासि यज्जुहोषि ददासि यत्। यत्तपस्यसि कौन्तेय तत्कुरुष्व मदर्पणम्॥', tr: 'Yatkaroshi yadashnasi yajjuhoshi dadasi yat, yattapasyasi Kaunteya tatkurushva madarpanam.', en: 'Whatever you do, eat, offer, give, or practise — do it as an offering to me, Kaunteya.', hi: 'हे कौन्तेय! जो करते हो, खाते हो, हवन करते हो, देते हो, तप करते हो — वह सब मुझे अर्पित करो।'},
  {n: 28, speaker: 'krishna', sa: 'शुभाशुभफलैरेवं मोक्ष्यसे कर्मबन्धनैः। संन्यासयोगयुक्तात्मा विमुक्तो मामुपैष्यसि॥', tr: 'Shubhashubhaphalairevam mokshyase karmabandhanaih, sannyasayogayuktatma vimukto mamupaishyasi.', en: 'Thus freed from the bonds of good and ill fruit, set in renunciation’s yoga, you shall reach me liberated.', hi: 'इस प्रकार शुभाशुभ फल वाले कर्मबंधनों से मुक्त होकर, संन्यासयोग में स्थित तुम मुझे पाओगे।'},
  {n: 29, speaker: 'krishna', sa: 'समोऽहं सर्वभूतेषु न मे द्वेष्योऽस्ति न प्रियः। ये भजन्ति तु मां भक्त्या मयि ते तेषु चाप्यहम्॥', tr: 'Samoaham sarvabhuteshu na me dveshyoasti na priyah, ye bhajanti tu mam bhaktya mayi te teshu chapyaham.', en: 'I am the same to all beings — none hateful, none dear — yet those who love me dwell in me, and I in them.', hi: 'मैं सभी भूतों में सम हूँ — न कोई द्वेष्य, न प्रिय; पर जो भक्ति से भजते हैं, वे मुझमें हैं और मैं उनमें।'},
  {n: 30, speaker: 'krishna', sa: 'अपि चेत्सुदुराचारो भजते मामनन्यभाक्। साधुरेव स मन्तव्यः सम्यग्व्यवसितो हि सः॥', tr: 'Api chetsuduracharo bhajate mamananyabhak, sadhureva sa mantavyah samyagvyavasito hi sah.', en: 'Even a grievous wrongdoer who turns to me alone is deemed righteous — his resolve is right.', hi: 'अति दुराचारी भी यदि अनन्य भाव से मुझे भजता है, तो साधु ही मानने योग्य है — उसका निश्चय सम्यक है।'},
  {n: 31, speaker: 'krishna', sa: 'क्षिप्रं भवति धर्मात्मा शश्वच्छान्तिं निगच्छति। कौन्तेय प्रतिजानीहि न मे भक्तः प्रणश्यति॥', tr: 'Kshipram bhavati dharmatma shashvachchhantim nigachchhati, Kaunteya pratijanihi na me bhaktah pranashyati.', en: 'Swiftly he turns righteous and finds lasting peace — declare it boldly, Kaunteya: my devotee never perishes.', hi: 'वह शीघ्र धर्मात्मा होकर शाश्वत शांति पाता है — हे कौन्तेय! प्रतिज्ञा करो, मेरा भक्त नष्ट नहीं होता।'},
  {n: 32, speaker: 'krishna', sa: 'मां हि पार्थ व्यपाश्रित्य येऽपि स्युः पापयोनयः। स्त्रियो वैश्यास्तथा शूद्रास्तेऽपि यान्ति परां गतिम्॥', tr: 'Mam hi Partha vyapashritya yeapi syuh papayonayah, striyo vaishyastatha shudrasteapi yanti param gatim.', en: 'Taking refuge in me, Partha, even the low-born — women, traders, labourers — reach the highest goal.', hi: 'हे पार्थ! मेरी शरण लेकर पापयोनि वाले भी — स्त्री, वैश्य और शूद्र — परम गति पाते हैं।'},
  {n: 33, speaker: 'krishna', sa: 'किं पुनर्ब्राह्मणाः पुण्याः भक्ताः राजर्षयस्तथा। अनित्यमसुखं लोकमिमं प्राप्य भजस्व माम्॥', tr: 'Kim punarbrahmanah punyah bhaktah rajarshayastatha, anityamasukham lokamimam prapya bhajasva mam.', en: 'How much more the holy sages and royal seers — having reached this fleeting joyless world, worship me.', hi: 'फिर पुण्य ब्राह्मण और राजर्षि भक्तों की तो बात ही क्या — इस अनित्य दुःखमय लोक को पाकर मुझे भजो।'},
  {n: 34, speaker: 'krishna', sa: 'मन्मना भव मद्भक्तो मद्याजी मां नमस्कुरु। मामेवैष्यसि युक्त्वैवमात्मानं मत्परायणः॥', tr: 'Manmana bhava madbhakto madyaji mam namaskuru, mamevaishyasi yuktvaivamatmanam matparayanah.', en: 'Set your heart on me, love me, sacrifice to me, bow to me — thus yoked, you shall reach me alone.', hi: 'मुझमें मन लगाओ, मेरे भक्त बनो, मेरा पूजन करो, मुझे नमस्कार करो — इस प्रकार मुझमें लगकर मुझे ही पाओगे।'}
];
