import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter1Meta: GitaChapterDetail = {
  n: 1,
  title: {en: 'Chapter 1 · Arjuna Vishada Yoga', hi: 'अध्याय 1 · अर्जुन विषाद योग'},
  summary: {
    en: 'On the field of Kurukshetra, Arjuna surveys friends and elders standing on both sides, is overcome with grief, and lays down his bow. 47 verses.',
    hi: 'कुरुक्षेत्र में दोनों ओर खड़े स्वजन और गुरुजन देखकर अर्जुन शोक से भर उठते हैं और गांडीव रख देते हैं। 47 श्लोक।'
  }
};

export const chapter1Verses: GitaVerse[] = [
  {n: 1, speaker: 'dhritarashtra', sa: 'धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः। मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय॥', tr: 'Dharmakshetre Kurukshetre samaveta yuyutsavah, mamakah Pandavashchaiva kimakurvata Sanjaya.', en: 'Gathered on the holy field of Kurukshetra, eager to fight — what did my sons and the sons of Pandu do, Sanjaya?', hi: 'धर्मक्षेत्र कुरुक्षेत्र में युद्ध की इच्छा से जुटे मेरे और पाण्डु के पुत्रों ने क्या किया, संजय?'},
  {n: 2, speaker: 'sanjaya', sa: 'दृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्योधनस्तदा। आचार्यमुपसङ्गम्य राजा वचनमब्रवीत्॥', tr: 'Drishtva tu Pandavanikam vyudham Duryodhanastada, acharyamupasangamya raja vachanamabravit.', en: 'Seeing the Pandava army drawn up in formation, Prince Duryodhana approached his teacher Drona and spoke.', hi: 'पाण्डवों की व्यूहबद्ध सेना देखकर राजा दुर्योधन आचार्य द्रोण के पास जाकर बोले।'},
  {n: 3, speaker: 'sanjaya', sa: 'पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम्। व्यूढां द्रुपदपुत्रेण तव शिष्येण धीमता॥', tr: 'Pashyaitam Panduputranamacharya mahatim chamum, vyudham Drupadaputrena tava shishyena dhimata.', en: 'Behold, teacher, this mighty Pandava army, arrayed by your wise disciple, the son of Drupada.', hi: 'आचार्य! आपके बुद्धिमान शिष्य द्रुपदपुत्र धृष्टद्युम्न द्वारा रची पाण्डवों की विशाल सेना देखिए।'},
  {n: 4, speaker: 'sanjaya', sa: 'अत्र शूरा महेष्वासा भीमार्जुनसमा युधि। युयुधानो विराटश्च द्रुपदश्च महारथः॥', tr: 'Atra shura maheshvasa Bhimarjunasama yudhi, Yuyudhano Viratashcha Drupadashcha maharathah.', en: 'Here stand heroes, great archers equal to Bhima and Arjuna in battle — Yuyudhana, Virata, and the great warrior Drupada.', hi: 'यहाँ युद्ध में भीम-अर्जुन के समान पराक्रमी शूरवीर, महाधनुर्धर हैं — युयुधान, विराट और महारथी द्रुपद।'},
  {n: 5, speaker: 'sanjaya', sa: 'धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान्। पुरुजित्कुन्तिभोजश्च शैब्यश्च नरपुङ्गवः॥', tr: 'Dhrishtaketushchekitanah Kashirajashcha viryavan, Purujit Kuntibhojashcha Shaibyashcha narapungavah.', en: 'Dhrishtaketu, Chekitana, the valiant king of Kashi, Purujit, Kuntibhoja, and Shaibya, noblest of men.', hi: 'धृष्टकेतु, चेकितान, पराक्रमी काशिराज, पुरुजित्, कुंतिभोज और नरों में श्रेष्ठ शैब्य।'},
  {n: 6, speaker: 'sanjaya', sa: 'युधामन्युश्च विक्रान्त उत्तमौजाश्च वीर्यवान्। सौभद्रो द्रौपदेयाश्च सर्व एव महारथाः॥', tr: 'Yudhamanyushcha vikranta Uttamaujashcha viryavan, Saubhadro Draupadeyashcha sarva eva maharathah.', en: 'Mighty Yudhamanyu, valiant Uttamaujas, Abhimanyu, and the five sons of Draupadi — all of them great warriors.', hi: 'पराक्रमी युधामन्यु, वीर्यवान उत्तमौजा, सुभद्रापुत्र अभिमन्यु और द्रौपदी के पाँचों पुत्र — सभी महारथी हैं।'},
  {n: 7, speaker: 'sanjaya', sa: 'अस्माकं तु विशिष्टा ये तान्निबोध द्विजोत्तम। नायका मम सैन्यस्य संज्ञार्थं तान्ब्रवीमि ते॥', tr: 'Asmakam tu vishishta ye tannibodha dvijottama, nayaka mama sainyasya samjnartham tanbravimi te.', en: 'Now hear, noblest of Brahmanas, of the captains of my army — I name them to remind you.', hi: 'हे द्विजोत्तम! अब हमारी सेना के प्रमुख नायकों को जानिए — स्मरण हेतु मैं उन्हें गिनाता हूँ।'},
  {n: 8, speaker: 'sanjaya', sa: 'भवान्भीष्मश्च कर्णश्च कृपश्च समितिञ्जयः। अश्वत्थामा विकर्णश्च सौमदत्तिस्तथैव च॥', tr: 'Bhavan Bhishmashcha Karnashcha Kripashcha samitinjayah, Ashvatthama Vikarnashcha Saumadattistathaiva cha.', en: 'Yourself, Bhishma, Karna, Kripa ever-victorious in battle, Ashvatthama, Vikarna, and Bhurishrava, son of Somadatta.', hi: 'आप, भीष्म, कर्ण, युद्ध में सदा विजयी कृप, अश्वत्थामा, विकर्ण और सोमदत्तपुत्र भूरिश्रवा।'},
  {n: 9, speaker: 'sanjaya', sa: 'अन्ये च बहवः शूरा मदर्थे त्यक्तजीविताः। नानाशस्त्रप्रहरणाः सर्वे युद्धविशारदाः॥', tr: 'Anye cha bahavah shura madarthe tyaktajivitah, nanashastrapraharanah sarve yuddhavisharadah.', en: 'And many other heroes, ready to lay down their lives for my sake, armed with many weapons — all skilled in war.', hi: 'और भी बहुत से शूरवीर मेरे लिए प्राण देने को तत्पर हैं, नाना शस्त्रों से सज्जित — सभी युद्धकुशल।'},
  {n: 10, speaker: 'sanjaya', sa: 'अपर्याप्तं तदस्माकं बलं भीष्माभिरक्षितम्। पर्याप्तं त्विदमेतेषां बलं भीमाभिरक्षितम्॥', tr: 'Aparyaptam tadasmakam balam Bhishmabhirakshitam, paryaptam tvidametesham balam Bhimabhirakshitam.', en: 'Our strength, guarded by Bhishma, is immeasurable; theirs, guarded by Bhima, is measurable.', hi: 'भीष्म द्वारा रक्षित हमारी सेना अपरिमित है; भीम द्वारा रक्षित उनकी सेना परिमित है।'},
  {n: 11, speaker: 'sanjaya', sa: 'अयनेषु च सर्वेषु यथाभागमवस्थिताः। भीष्ममेवाभिरक्षन्तु भवन्तः सर्व एव हि॥', tr: 'Ayaneshu cha sarveshu yathabhagamavasthitah, Bhishmamevabhirakshantu bhavantah sarva eva hi.', en: 'Stationed each at his post, guard Bhishma on every side, all of you.', hi: 'अपने-अपने मोर्चों पर स्थित आप सब हर ओर से भीष्म की रक्षा करें।'},
  {n: 12, speaker: 'sanjaya', sa: 'तस्य सञ्जनयन्हर्षं कुरुवृद्धः पितामहः। सिंहनादं विनद्योच्चैः शङ्खं दध्मौ प्रतापवान्॥', tr: 'Tasya sanjanayanharsham Kuruvriddhah pitamahah, simhanadam vinadyochchaih shankham dadhmau pratapavan.', en: 'To cheer him, the grandsire Bhishma, eldest of the Kurus, roared like a lion and blew his conch.', hi: 'उन्हें हर्षित करने हेतु कुरुवृद्ध पितामह भीष्म ने सिंहनाद कर जोर से शंख बजाया।'},
  {n: 13, speaker: 'sanjaya', sa: 'ततः शङ्खाश्च भेर्यश्च पणवानकगोमुखाः। सहसैवाभ्यहन्यन्त स शब्दस्तुमुलोऽभवत्॥', tr: 'Tatah shankhashcha bheryashcha panavanakagomukhah, sahasaivabhyahanyanta sa shabdastumuloabhavat.', en: 'Then conches, drums, tabors and horns sounded all at once — a tumultuous roar.', hi: 'तब शंख, नगाड़े, ढोल और रणसिंगे एक साथ बज उठे — तुमुल नाद गूँज गया।'},
  {n: 14, speaker: 'sanjaya', sa: 'ततः श्वेतैर्हयैर्युक्ते महति स्यन्दने स्थितौ। माधवः पाण्डवश्चैव दिव्यौ शङ्खौ प्रदध्मतुः॥', tr: 'Tatah shvetairhayairyukte mahati syandane sthitau, Madhavah Pandavashchaiva divyau shankhau pradadhmatuh.', en: 'Then, seated in their great chariot yoked with white horses, Krishna and Arjuna blew their divine conches.', hi: 'तब श्वेत अश्वों वाले विशाल रथ पर आसीन माधव और पाण्डव ने दिव्य शंख बजाए।'},
  {n: 15, speaker: 'sanjaya', sa: 'पाञ्चजन्यं हृषीकेशो देवदत्तं धनञ्जयः। पौण्ड्रं दध्मौ महाशङ्खं भीमकर्मा वृकोदरः॥', tr: 'Panchajanyam Hrishikesho Devadattam Dhananjayah, Paundram dadhmau mahashankham Bhimakarma Vrikodarah.', en: 'Krishna blew Panchajanya, Arjuna blew Devadatta, and Bhima of mighty deeds blew the great conch Paundra.', hi: 'हृषीकेश ने पांचजन्य, धनंजय ने देवदत्त और महाकर्मी वृकोदर भीम ने पौण्ड्र महाशंख बजाया।'},
  {n: 16, speaker: 'sanjaya', sa: 'अनन्तविजयं राजा कुन्तीपुत्रो युधिष्ठिरः। नकुलः सहदेवश्च सुघोषमणिपुष्पकौ॥', tr: 'Anantavijayam raja Kuntiputro Yudhishthirah, Nakulah Sahadevashcha Sughoshamanipushpakau.', en: 'King Yudhishthira blew Anantavijaya; Nakula and Sahadeva blew Sughosha and Manipushpaka.', hi: 'कुंतीपुत्र राजा युधिष्ठिर ने अनंतविजय; नकुल और सहदेव ने सुघोष और मणिपुष्पक बजाए।'},
  {n: 17, speaker: 'sanjaya', sa: 'काश्यश्च परमेष्वासः शिखण्डी च महारथः। धृष्टद्युम्नो विराटश्च सात्यकिश्चापराजितः॥', tr: 'Kashyashcha parameshvasah Shikhandi cha maharathah, Dhrishtadyumno Viratashcha Satyakishchaparajitah.', en: 'The king of Kashi, finest of archers, the great warrior Shikhandi, Dhrishtadyumna, Virata, and invincible Satyaki.', hi: 'महाधनुर्धर काशिराज, महारथी शिखंडी, धृष्टद्युम्न, विराट और अपराजेय सात्यकि।'},
  {n: 18, speaker: 'sanjaya', sa: 'द्रुपदो द्रौपदेयाश्च सर्वशः पृथिवीपते। सौभद्रश्च महाबाहुः शङ्खान्दध्मुः पृथक्पृथक्॥', tr: 'Drupado Draupadeyashcha sarvashah prithivipate, Saubhadrashcha mahabahuh shankhandadhhmuh prithakprithak.', en: 'Drupada and the sons of Draupadi, O king, and mighty-armed Abhimanyu — each blew his own conch.', hi: 'हे पृथ्वीपते! द्रुपद, द्रौपदी के पुत्र और महाबाहु अभिमन्यु — सबने अलग-अलग शंख बजाए।'},
  {n: 19, speaker: 'sanjaya', sa: 'स घोषो धार्तराष्ट्राणां हृदयानि व्यदारयत्। नभश्च पृथिवीं चैव तुमुलोऽभिनुनादयन्॥', tr: 'Sa ghosho Dhartarashtranam hridayani vyadarayat, nabhashcha prithivim chaiva tumuloabhinunadayan.', en: 'That uproar tore the hearts of Dhritarashtra’s sons, echoing through sky and earth.', hi: 'उस तुमुल घोष ने आकाश-पृथ्वी गुँजाते हुए धृतराष्ट्रपुत्रों के हृदय विदीर्ण कर दिए।'},
  {n: 20, speaker: 'sanjaya', sa: 'अथ व्यवस्थितान्दृष्ट्वा धार्तराष्ट्रान्कपिध्वजः। प्रवृत्ते शस्त्रसम्पाते धनुरुद्यम्य पाण्डवः॥', tr: 'Atha vyavasthitandrishtva Dhartarashtran kapidhvajah, pravritte shastrasampate dhanurudyamya Pandavah.', en: 'Then Arjuna, whose banner bears Hanuman, seeing Dhritarashtra’s sons arrayed as weapons were about to fly, raised his bow.', hi: 'तब कपिध्वज अर्जुन ने धृतराष्ट्रपुत्रों को खड़ा देख, शस्त्र चलने की बेला में धनुष उठाया।'},
  {n: 21, speaker: 'arjuna', sa: 'हृषीकेशं तदा वाक्यमिदमाह महीपते। सेनयोरुभयोर्मध्ये रथं स्थापय मेऽच्युत॥', tr: 'Hrishikesham tada vakyamidamaha mahipate, senayorubhayormadhye ratham sthapaya meachyuta.', en: 'And spoke these words to Krishna, O king: “Place my chariot between the two armies, Achyuta.”', hi: 'और हृषीकेश से बोले, हे राजन् — “हे अच्युत! मेरा रथ दोनों सेनाओं के बीच खड़ा कीजिए।”'},
  {n: 22, speaker: 'arjuna', sa: 'यावदेतान्निरीक्षेऽहं योद्धुकामानवस्थितान्। कैर्मया सह योद्धव्यमस्मिन्रणसमुद्यमे॥', tr: 'Yavadetanniriksheaham yoddhukamanavasthitan, kairmaya saha yoddhavyamasminranasamudyame.', en: 'Let me behold those who stand here eager to fight, and know with whom I must contend in this trial of war.', hi: 'युद्ध की इच्छा से खड़े इन योद्धाओं को मैं देख लूँ — इस रण में मुझे किनसे लड़ना है।'},
  {n: 23, speaker: 'arjuna', sa: 'योत्स्यमानानवेक्षेऽहं य एतेऽत्र समागताः। धार्तराष्ट्रस्य दुर्बुद्धेर्युद्धे प्रियचिकीर्षवः॥', tr: 'Yotsyamananaveksheaham ya etetra samagatah, Dhartarashtrasya durbuddheryuddhe priyachikirshavah.', en: 'I would see those gathered here, wishing to please the evil-minded son of Dhritarashtra by fighting.', hi: 'दुर्बुद्धि धृतराष्ट्रपुत्र को युद्ध में प्रसन्न करने आए इन योद्धाओं को मैं देखना चाहता हूँ।'},
  {n: 24, speaker: 'sanjaya', sa: 'एवमुक्तो हृषीकेशो गुडाकेशेन भारत। सेनयोरुभयोर्मध्ये स्थापयित्वा रथोत्तमम्॥', tr: 'Evamukto Hrishikesho Gudakeshena Bharata, senayorubhayormadhye sthapayitva rathamottamam.', en: 'So addressed by Arjuna, O Bharata, Krishna drew up that finest of chariots between the two armies.', hi: 'हे भरतवंशी! अर्जुन के ऐसा कहने पर हृषीकेश ने उत्तम रथ दोनों सेनाओं के बीच खड़ा कर दिया।'},
  {n: 25, speaker: 'sanjaya', sa: 'भीष्मद्रोणप्रमुखतः सर्वेषां च महीक्षिताम्। उवाच पार्थ पश्यैतान्समवेतान्कुरूनिति॥', tr: 'Bhishmadronapramukhatah sarvesham cha mahikshitam, uvacha Partha pashyaitansamavetankuruniti.', en: 'Before Bhishma, Drona and all the kings, he said: “Behold, Partha, the Kurus gathered here.”', hi: 'भीष्म, द्रोण और समस्त राजाओं के सामने बोले — “पार्थ! जुटे हुए इन कुरुओं को देखो।”'},
  {n: 26, speaker: 'sanjaya', sa: 'तत्रापश्यत्स्थितान्पार्थः पितॄनथ पितामहान्। आचार्यान्मातुलान्भ्रातॄन्पुत्रान्पौत्रान्सखींस्तथा॥', tr: 'Tatrapashyatsthitanparthah pitrinatha pitamahan, acharyanmatulanbhratrinputranpautransakhimstatha.', en: 'There Arjuna saw fathers and grandfathers, teachers, uncles, brothers, sons, grandsons and friends standing.', hi: 'वहाँ पार्थ ने पिता, पितामह, आचार्य, मामा, भाई, पुत्र, पौत्र और मित्रों को खड़ा देखा।'},
  {n: 27, speaker: 'sanjaya', sa: 'श्वशुरान्सुहृदश्चैव सेनयोरुभयोरपि। तान्समीक्ष्य स कौन्तेयः सर्वान्बन्धूनवस्थितान्॥', tr: 'Shvashuransuhridashchaiva senayorubhayorapi, tansamikshya sa Kaunteyah sarvanbandhunavasthitan.', en: 'Fathers-in-law and companions too, in both armies — seeing all these kinsmen arrayed, Arjuna…', hi: 'दोनों सेनाओं में श्वसुर और सुहृद भी — इन समस्त बंधुओं को खड़ा देख कुंतीपुत्र…'},
  {n: 28, speaker: 'arjuna', sa: 'कृपया परयाविष्टो विषीदन्निदमब्रवीत्। दृष्ट्वेमं स्वजनं कृष्ण युयुत्सुं समुपस्थितम्॥', tr: 'Kripaya parayavishto vishidannidamabravit, drishtvemam svajanam Krishna yuyutsum samupasthitam.', en: '…overcome with deep pity, spoke in grief: “Seeing my own people arrayed here, eager to fight, Krishna —”', hi: '…गहरी करुणा से भर विषादपूर्वक बोले — “हे कृष्ण! युद्ध को उद्यत इन स्वजनों को देखकर —”'},
  {n: 29, speaker: 'arjuna', sa: 'सीदन्ति मम गात्राणि मुखं च परिशुष्यति। वेपथुश्च शरीरे मे रोमहर्षश्च जायते॥', tr: 'Sidanti mama gatrani mukham cha parishushyati, vepathushcha sharire me romaharshashcha jayate.', en: 'My limbs fail, my mouth dries up, my body trembles, and my hair stands on end.', hi: 'मेरे अंग शिथिल हो रहे हैं, मुख सूख रहा है, शरीर काँप रहा है और रोंगटे खड़े हो रहे हैं।'},
  {n: 30, speaker: 'arjuna', sa: 'गाण्डीवं स्रंसते हस्तात्त्वक्चैव परिदह्यते। न च शक्नोम्यवस्थातुं भ्रमतीव च मे मनः॥', tr: 'Gandivam sramsate hastattvakchaiva paridahyate, na cha shaknomyavasthatum bhramativa cha me manah.', en: 'Gandiva slips from my hand, my skin burns, I cannot stand steady — my mind reels.', hi: 'हाथ से गांडीव छूट रहा है, त्वचा जल रही है, खड़ा नहीं रहा जाता — मन भ्रमित हो रहा है।'},
  {n: 31, speaker: 'arjuna', sa: 'निमित्तानि च पश्यामि विपरीतानि केशव। न च श्रेयोऽनुपश्यामि हत्वा स्वजनमाहवे॥', tr: 'Nimittani cha pashyami viparitani Keshava, na cha shreyoanupashyami hatva svajanamahave.', en: 'I see ill omens, Keshava, and no good in slaying my own kin in battle.', hi: 'हे केशव! विपरीत लक्षण देख रहा हूँ — स्वजनों को मारकर कोई कल्याण नहीं देखता।'},
  {n: 32, speaker: 'arjuna', sa: 'न काङ्क्षे विजयं कृष्ण न च राज्यं सुखानि च। किं नो राज्येन गोविन्द किं भोगैर्जीवितेन वा॥', tr: 'Na kankshe vijayam Krishna na cha rajyam sukhani cha, kim no rajyena Govinda kim bhogairjivitena va.', en: 'I desire no victory, Krishna, nor kingdom, nor pleasures. What use is a kingdom to us, Govinda — or pleasures, or life itself?', hi: 'न विजय चाहता हूँ, न राज्य, न सुख। हे गोविंद! राज्य, भोग या जीवन से हमें क्या प्रयोजन?'},
  {n: 33, speaker: 'arjuna', sa: 'येषामर्थे काङ्क्षितं नो राज्यं भोगाः सुखानि च। त इमेऽवस्थिता युद्धे प्राणांस्त्यक्त्वा धनानि च॥', tr: 'Yeshamarthe kankshitam no rajyam bhogah sukhani cha, ta imeavasthita yuddhe pranamstyaktva dhanani cha.', en: 'Those for whose sake we desire kingdom, pleasures and joys stand here in battle, having staked their lives and riches.', hi: 'जिनके लिए राज्य, भोग और सुख चाहते थे, वे ही प्राण-धन दाँव पर लगाकर युद्ध में खड़े हैं।'},
  {n: 34, speaker: 'arjuna', sa: 'आचार्याः पितरः पुत्रास्तथैव च पितामहाः। मातुलाः श्वशुराः पौत्राः श्यालाः सम्बन्धिनस्तथा॥', tr: 'Acharyah pitarah putrastathaiva cha pitamahah, matulah shvashurah pautrah shyalah sambandhinastatha.', en: 'Teachers, fathers, sons, grandfathers; uncles, fathers-in-law, grandsons, brothers-in-law, and kin.', hi: 'आचार्य, पिता, पुत्र, पितामह; मामा, श्वसुर, पौत्र, साले और संबंधी।'},
  {n: 35, speaker: 'arjuna', sa: 'एतान्न हन्तुमिच्छामि घ्नतोऽपि मधुसूदन। अपि त्रैलोक्यराज्यस्य हेतोः किं नु महीकृते॥', tr: 'Etanna hantumichchhami ghnatoapi Madhusudana, api trailokyarajyasya hetoh kim nu mahikrite.', en: 'I would not slay them, Madhusudana, though they slay me — not even for the kingship of the three worlds, let alone this earth.', hi: 'ये मारें तो भी इन्हें मारना नहीं चाहता, मधुसूदन — तीनों लोकों के राज्य हेतु भी नहीं, पृथ्वी की तो बात ही क्या।'},
  {n: 36, speaker: 'arjuna', sa: 'निहत्य धार्तराष्ट्रान्नः का प्रीतिः स्याज्जनार्दन। पापमेवाश्रयेदस्मान्हत्वैतानाततायिनः॥', tr: 'Nihatya Dhartarashtrannah ka pritih syajJanardana, papamevashrayedasmanhatvaitanat atayinah.', en: 'What joy could killing Dhritarashtra’s sons bring us, Janardana? Slaying these aggressors, sin alone would cling to us.', hi: 'धृतराष्ट्रपुत्रों को मारकर हमें क्या प्रसन्नता होगी, जनार्दन? इन आतताइयों को मारने से पाप ही लगेगा।'},
  {n: 37, speaker: 'arjuna', sa: 'तस्मान्नार्हा वयं हन्तुं धार्तराष्ट्रान्स्वबान्धवान्। स्वजनं हि कथं हत्वा सुखिनः स्याम माधव॥', tr: 'Tasmannarha vayam hantum Dhartarashtransvabandhavan, svajanam hi katham hatva sukhinah syama Madhava.', en: 'So we must not slay our kinsmen, Dhritarashtra’s sons. How could we be happy, Madhava, after killing our own?', hi: 'अतः अपने बंधु धृतराष्ट्रपुत्रों को मारना उचित नहीं। हे माधव! स्वजन मारकर हम सुखी कैसे होंगे?'},
  {n: 38, speaker: 'arjuna', sa: 'यद्यप्येते न पश्यन्ति लोभोपहतचेतसः। कुलक्षयकृतं दोषं मित्रद्रोहे च पातकम्॥', tr: 'Yadyapyete na pashyanti lobhopahatachetasah, kulakshayakritam dosham mitradrohe cha patakam.', en: 'Though these men, blinded by greed, see no evil in destroying the family, no sin in betraying friends —', hi: 'यद्यपि लोभ से भ्रष्टचित्त ये लोग कुलनाश का दोष और मित्रद्रोह का पाप नहीं देखते —'},
  {n: 39, speaker: 'arjuna', sa: 'कथं न ज्ञेयमस्माभिः पापादस्मान्निवर्तितुम्। कुलक्षयकृतं दोषं प्रपश्यद्भिर्जनार्दन॥', tr: 'Katham na jneyamasmabhih papadasmannivartitum, kulakshayakritam dosham prapashyadbhirJanardana.', en: '…should we not, Janardana, who see the evil born of destroying the family, turn back from this sin?', hi: '…तो क्या हम, जो कुलनाश का दोष देख रहे हैं, इस पाप से न बचें, जनार्दन?'},
  {n: 40, speaker: 'arjuna', sa: 'कुलक्षये प्रणश्यन्ति कुलधर्माः सनातनाः। धर्मे नष्टे कुलं कृत्स्नमधर्मोऽभिभवत्युत॥', tr: 'Kulakshaye pranashyanti kuladharmah sanatanah, dharme nashte kulam kritsnamadharmoabhibhavatyuta.', en: 'When the family perishes, its timeless sacred customs perish; when custom is lost, lawlessness overtakes the whole clan.', hi: 'कुलनाश से सनातन कुलधर्म नष्ट होते हैं; धर्म नष्ट होने पर समस्त कुल को अधर्म दबोच लेता है।'},
  {n: 41, speaker: 'arjuna', sa: 'अधर्माभिभवात्कृष्ण प्रदुष्यन्ति कुलस्त्रियः। स्त्रीषु दुष्टासु वार्ष्णेय जायते वर्णसङ्करः॥', tr: 'Adharmabhibhavat Krishna pradushyanti kulastriyah, strishu dushtasu Varshneya jayate varnasankarah.', en: 'When lawlessness prevails, Krishna, the women of the family fall; corrupted, they bring forth the confusion of castes, O Varshneya.', hi: 'अधर्म फैलने से, कृष्ण, कुलस्त्रियाँ दूषित होती हैं; दूषित होने पर, हे वार्ष्णेय, वर्णसंकर उत्पन्न होता है।'},
  {n: 42, speaker: 'arjuna', sa: 'सङ्करो नरकायैव कुलघ्नानां कुलस्य च। पतन्ति पितरो ह्येषां लुप्तपिण्डोदकक्रियाः॥', tr: 'Sankaro narakayaiva kulaghnanam kulasya cha, patanti pitaro hyesham luptapindodakakriyah.', en: 'That confusion drags the clan-slayers and their clan to hell; their ancestors fall, deprived of rice and water offerings.', hi: 'यह संकर कुलघातियों और कुल को नरक ले जाता है; पिंड-जल क्रिया लुप्त होने से इनके पितर पतित होते हैं।'},
  {n: 43, speaker: 'arjuna', sa: 'दोषैरेतैः कुलघ्नानां वर्णसङ्करकारकैः। उत्साद्यन्ते जातिधर्माः कुलधर्माश्च शाश्वताः॥', tr: 'Dosh airetaih kulaghnanam varnasankar akarakaih, utsadyante jatidharmah kuladharmashcha shashvatah.', en: 'By these evils of the clan-slayers, which breed confusion, the timeless duties of caste and clan are destroyed.', hi: 'कुलघातियों के इन वर्णसंकरकारी दोषों से शाश्वत जातिधर्म और कुलधर्म नष्ट हो जाते हैं।'},
  {n: 44, speaker: 'arjuna', sa: 'उत्सन्नकुलधर्माणां मनुष्याणां जनार्दन। नरकेऽनियतं वासो भवतीत्यनुशुश्रुम॥', tr: 'Utsannakuladharmanam manushyanam Janardana, narakeaniyatam vaso bhavatityanushushruma.', en: 'We have heard, Janardana, that those whose clan-duties are destroyed must dwell endlessly in hell.', hi: 'हे जनार्दन! हमने सुना है कि जिनके कुलधर्म नष्ट हो जाते हैं, उन्हें अनंत काल नरक में रहना पड़ता है।'},
  {n: 45, speaker: 'arjuna', sa: 'अहो बत महत्पापं कर्तुं व्यवसिता वयम्। यद्राज्यसुखलोभेन हन्तुं स्वजनमुद्यताः॥', tr: 'Aho bata mahatpapam kartum vyavasita vayam, yadrajyasukhalobhena hantum svajanamudyatah.', en: 'Alas! We resolve to commit a great sin — ready to slay our own people from greed for a kingdom’s joys.', hi: 'अहो! हम महापाप करने पर तुले हैं — राज्यसुख के लोभ से स्वजन मारने को उद्यत हैं।'},
  {n: 46, speaker: 'arjuna', sa: 'यदि मामप्रतीकारमशस्त्रं शस्त्रपाणयः। धार्तराष्ट्रा रणे हन्युस्तन्मे क्षेमतरं भवेत्॥', tr: 'Yadi mamapratikaramashastram shastrapanayah, Dhartarashtra rane hanyustanme kshemataram bhavet.', en: 'If Dhritarashtra’s sons, weapons in hand, should slay me unresisting and unarmed in battle — that would be greater blessing.', hi: 'यदि शस्त्रधारी धृतराष्ट्रपुत्र मुझ निहत्थे और अप्रतिकार करते को रण में मार डालें — वही मेरे लिए श्रेयस्कर होगा।'},
  {n: 47, speaker: 'sanjaya', sa: 'एवमुक्त्वार्जुनः सङ्ख्ये रथोपस्थ उपाविशत्। विसृज्य सशरं चापं शोकसंविग्नमानसः॥', tr: 'Evamuktvarjunah sankhye rathopastha upavishat, visrijya sasharam chapam shokasamvignamanasah.', en: 'So saying, Arjuna sank onto his chariot seat, casting aside bow and arrows — his heart overwhelmed with grief.', hi: 'ऐसा कहकर अर्जुन बाणसहित धनुष रखकर, शोक से व्याकुल मन लिए रथ में बैठ गए।'}
];

