import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter12Meta: GitaChapterDetail = {
  n: 12,
  title: {en: 'Chapter 12 · Bhakti Yoga', hi: 'अध्याय 12 · भक्ति योग'},
  summary: {
    en: 'The yoga of devotion — who is dearest to the Lord. 20 verses.',
    hi: 'भक्ति योग — भगवान को कौन प्रिय है। 20 श्लोक।'
  }
};

export const chapter12Verses: GitaVerse[] = [
  {n: 1, speaker: 'arjuna', sa: 'एवं सततयुक्ता ये भक्तास्त्वां पर्युपासते। ये चाप्यक्षरमव्यक्तं तेषां के योगवित्तमाः॥', tr: 'Evam satatayukta ye bhaktastvam paryupasate, ye chapyaksharamavyaktam tesham ke yogavittamah.', en: 'Those steady devotees who worship you with form, and those who seek the changeless formless — which know yoga best.', hi: 'जो भक्त निरंतर युक्त होकर आपकी उपासना करते हैं, और जो अव्यक्त अक्षर की — उनमें श्रेष्ठ योगी कौन हैं?'},
  {n: 2, speaker: 'krishna', sa: 'मय्यावेश्य मनो ये मां नित्ययुक्ता उपासते। श्रद्धया परयोपेतास्ते मे युक्ततमा मताः॥', tr: 'Mayyaveshya mano ye mam nityayukta upasate, shraddhaya parayopetaste me yuktatama matah.', en: 'Who fix their minds on me, ever steady, and worship me with full faith — these I hold the most joined in yoga.', hi: 'जो मुझमें मन लगाकर नित्य युक्त हो परम श्रद्धा से मेरी उपासना करते हैं — वे मुझे श्रेष्ठ योगी लगते हैं।'},
  {n: 3, speaker: 'krishna', sa: 'ये त्वक्षरमनिर्देश्यमव्यक्तं पर्युपासते। सर्वत्रगमचिन्त्यं च कूटस्थमचलं ध्रुवम्॥', tr: 'Ye tvaksharamanirdeshyamavyaktam paryupasate, sarvatragamachintyam cha kutasthamachalam dhruvam.', en: 'Who seek the changeless, unseen, all-pervading, unthinkable, firm, fixed and eternal —', hi: 'जो अवर्णनीय, अव्यक्त, सर्वव्यापी, अचिंत्य, कूटस्थ, अचल, ध्रुव अक्षर की उपासना करते हैं —'},
  {n: 4, speaker: 'krishna', sa: 'सन्नियम्येन्द्रियग्रामं सर्वत्र समबुद्धयः। ते प्राप्नुवन्ति मामेव सर्वभूतहिते रताः॥', tr: 'Sanniyamyendriyagramam sarvatra samabuddhayah, te prapnuvanti mameva sarvabhutahite ratah.', en: 'Restraining the senses, even-minded everywhere, delighting in the welfare of all beings — they too reach me alone.', hi: 'इंद्रियसमूह वश में कर, सर्वत्र समबुद्धि रह, समस्त प्राणियों के हित में रत वे भी मुझी को पाते हैं।'},
  {n: 5, speaker: 'krishna', sa: 'क्लेशोऽधिकतरस्तेषामव्यक्तासक्तचेतसाम्। अव्यक्ता हि गतिर्दुःखं देहवद्भिरवाप्यते॥', tr: 'Kleshodhikatarasteshamavyaktasaktachetasam, avyakta hi gatirduhkham dehavadbhiravapyate.', en: 'Greater is the strain for minds set on the formless, for the formless goal is hard won by embodied beings.', hi: 'अव्यक्त में लगे चित्त वालों को अधिक क्लेश होता है, क्योंकि देहधारियों को अव्यक्त गति कठिनता से मिलती है।'},
  {n: 6, speaker: 'krishna', sa: 'ये तु सर्वाणि कर्माणि मयि सन्न्यस्य मत्पराः। अनन्येनैव योगेन मां ध्यायन्त उपासते॥', tr: 'Ye tu sarvani karmani mayi sannyasya matparah, ananyenaiva yogena mam dhyayanta upasate.', en: 'Who lay all their deeds on me, hold me highest, and worship me with single yoga, meditating on me —', hi: 'जो समस्त कर्म मुझमें अर्पित कर मुझे परम मान अनन्य योग से मेरा ध्यान करते हुए उपासना करते हैं —'},
  {n: 7, speaker: 'krishna', sa: 'तेषामहं समुद्धर्ता मृत्युसंसारसागरात्। भवामि नचिरात्पार्थ मय्यावेशितचेतसाम्॥', tr: 'Teshamaham samuddharta mrityusamsarasagarat, bhavami nachiratPartha mayyaveshitachetasam.', en: 'For them, minds absorbed in me, I swiftly become the lifter from the sea of death-bound wandering, O Partha.', hi: 'हे पार्थ! मुझमें लगे चित्त वालों का मैं शीघ्र ही मृत्यु रूपी संसार सागर से उद्धार करता हूँ।'},
  {n: 8, speaker: 'krishna', sa: 'मय्येव मन आधत्स्व मयि बुद्धिं निवेशय। निवसिष्यसि मय्येव अत ऊर्ध्वं न संशयः॥', tr: 'Mayyeva mana adhatsva mayi buddhim niveshaya, nivasisyasi mayyeva ata urdhvam na samshayah.', en: 'Set your mind on me alone, rest your reason in me — then you shall dwell in me alone, no doubt.', hi: 'मुझमें ही मन लगाओ, मुझमें बुद्धि स्थिर करो — तभी तुम मुझमें ही निवास करोगे, इसमें संशय नहीं।'},
  {n: 9, speaker: 'krishna', sa: 'अथ चित्तं समाधातुं न शक्नोषि मयि स्थिरम्। अभ्यासयोगेन ततो मामिच्छाप्तुं धनञ्जय॥', tr: 'Atha chittam samadhatum na shaknoshi mayi sthiram, abhyasayogena tato mamichchhaptum Dhananjaya.', en: 'If you cannot hold your thought steady on me, then seek to reach me by steady practice, Dhananjaya.', hi: 'हे धनंजय! यदि चित्त मुझमें स्थिर नहीं कर सकते, तो अभ्यास योग से मुझे पाने की इच्छा करो।'},
  {n: 10, speaker: 'krishna', sa: 'अभ्यासेऽप्यसमर्थोऽसि मत्कर्मपरमो भव। मदर्थमपि कर्माणि कुर्वन्सिद्धिमवाप्स्यसि॥', tr: 'Abhyaseapyasamarthoasi matkarmaparamo bhava, madarthamapi karmani kurvansiddhimavapsyasi.', en: 'If even practice is beyond you, devote yourself to work for me — doing deeds for my sake, you shall gain perfection.', hi: 'यदि अभ्यास में भी असमर्थ हो, तो मेरे लिए कर्म करने में लगो — मेरे निमित्त कर्म करते हुए सिद्धि पाओगे।'},
  {n: 11, speaker: 'krishna', sa: 'अथैतदप्यशक्तोऽसि कर्तुं मद्योगमाश्रितः। सर्वकर्मफलत्यागं ततः कुरु यतात्मवान्॥', tr: 'Athaitadapyashaktoasi kartum madyogamashritah, sarvakarmaphalatyagam tatah kuru yatatmavan.', en: 'If even this you cannot do, then rest on my yoga with self-control and give up the fruit of all your deeds.', hi: 'यदि यह भी न कर सको, तो मेरे योग का आश्रय लेकर संयत होकर समस्त कर्मों के फल का त्याग करो।'},
  {n: 12, speaker: 'krishna', sa: 'श्रेयो हि ज्ञानमभ्यासाज्ज्ञानाद्ध्यानं विशिष्यते। ध्यानात्कर्मफलत्यागस्त्यागाच्छान्तिरनन्तरम्॥', tr: 'Shreyo hi jnanamabhyasajjnanaddhyanam vishishyate, dhyanatkarmaphalatyagastyagachchhantiranantaram.', en: 'Wisdom beats mere practice, meditation beats wisdom, giving up fruits beats meditation — from such giving comes peace at once.', hi: 'अभ्यास से ज्ञान श्रेष्ठ है, ज्ञान से ध्यान श्रेष्ठ है, ध्यान से कर्मफल त्याग श्रेष्ठ है — त्याग से तुरंत शांति मिलती है।'},
  {n: 13, speaker: 'krishna', sa: 'अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च। निर्ममो निरहङ्कारः समदुःखसुखः क्षमी॥', tr: 'Adveshta sarvabhutanam maitrah karuna eva cha, nirmamo nirahankarah samaduhkhasukhah kshami.', en: 'Who hates no being, is friendly and kind, free of mine and pride, same in pain and joy, patient —', hi: 'जो किसी प्राणी से द्वेष न करे, मित्र और दयालु हो, ममता-अहंकार रहित हो, सुख-दुःख में सम और क्षमाशील हो —'},
  {n: 14, speaker: 'krishna', sa: 'सन्तुष्टः सततं योगी यतात्मा दृढनिश्चयः। मय्यर्पितमनोबुद्धिर्यो मद्भक्तः स मे प्रियः॥', tr: 'Santushtah satatam yogi yatatma dridhanishchayah, mayyarpitamanobuddhiryo madbhaktah sa me priyah.', en: 'Ever content, steady, self-ruled, firm in resolve, with mind and reason laid on me — such a devotee of mine is dear to me.', hi: 'सदा संतुष्ट, संयमी, दृढ़ निश्चयी, मुझमें मन-बुद्धि अर्पित करने वाला जो मेरा भक्त है — वह मुझे प्रिय है।'},
  {n: 15, speaker: 'krishna', sa: 'यस्मान्नोद्विजते लोको लोकान्नोद्विजते च यः। हर्षामर्षभयोद्वेगैर्मुक्तो यः स च मे प्रियः॥', tr: 'Yasmannodvijate loko lokannodvijate cha yah, harshamarshabhayodvegairmukto yah sa cha me priyah.', en: 'From whom the world feels no fear, who feels no fear from the world, free of thrill, anger, dread and stir — that one is dear to me.', hi: 'जिससे लोक उद्विग्न न हो, जो लोक से उद्विग्न न हो, जो हर्ष-ईर्ष्या-भय-उद्वेग से मुक्त हो — वह भी मुझे प्रिय है।'},
  {n: 16, speaker: 'krishna', sa: 'अनपेक्षः शुचिर्दक्ष उदासीनो गतव्यथः। सर्वारम्भपरित्यागी यो मद्भक्तः स मे प्रियः॥', tr: 'Anapekshah shuchirdaksha udasino gatavyathah, sarvarambhaparityagi yo madbhaktah sa me priyah.', en: 'Wanting nothing, pure, skilled, aloof, free of torment, giving up all restless ventures — such a devotee is dear to me.', hi: 'जो अपेक्षा रहित, पवित्र, कुशल, उदासीन, व्यथा रहित हो, समस्त आरंभों का त्यागी हो — वह भक्त मुझे प्रिय है।'},
  {n: 17, speaker: 'krishna', sa: 'यो न हृष्यति न द्वेष्टि न शोचति न काङ्क्षति। शुभाशुभपरित्यागी भक्तिमान्यः स मे प्रियः॥', tr: 'Yo na hrishyati na dveshti na shochati na kankshati, shubhashubhaparityagi bhaktimanyah sa me priyah.', en: 'Who neither thrills nor hates, neither grieves nor craves, who leaves both good and ill behind and holds devotion — that one is dear to me.', hi: 'जो न हर्षित हो, न द्वेष करे, न शोक करे, न चाह रखे, शुभ-अशुभ दोनों का त्यागी भक्तिमान हो — वह मुझे प्रिय है।'},
  {n: 18, speaker: 'krishna', sa: 'समः शत्रौ च मित्रे च तथा मानापमानयोः। शीतोष्णसुखदुःखेषु समः सङ्गविवर्जितः॥', tr: 'Samah shatrau cha mitre cha tatha manapamanayoh, shitoshnasukhaduhkheshu samah sangavivarjitah.', en: 'Same toward foe and friend, in honor and slight, in cold and heat, joy and pain — free of clinging —', hi: 'जो शत्रु-मित्र में सम हो, मान-अपमान में समान हो, शीत-उष्ण, सुख-दुःख में सम हो, आसक्ति रहित हो —'},
  {n: 19, speaker: 'krishna', sa: 'तुल्यनिन्दास्तुतिर्मौनी सन्तुष्टो येन केनचित्। अनिकेतः स्थिरमतिर्भक्तिमान्मे प्रियो नरः॥', tr: 'Tulyanindastutirmauni santushto yena kenachit, aniketah sthiramatirbhaktimanme priyo narah.', en: 'Same in blame and praise, quiet within, content with whatever comes, homeless, steady-minded, full of devotion — such a person is dear to me.', hi: 'जो निंदा-स्तुति में समान, मौनी, जो मिले उसी में संतुष्ट, घर-आसक्ति रहित, स्थिर बुद्धि, भक्तिमान हो — वह मुझे प्रिय है।'},
  {n: 20, speaker: 'krishna', sa: 'ये तु धर्म्यामृतमिदं यथोक्तं पर्युपासते। श्रद्दधाना मत्परमा भक्तास्तेऽतीव मे प्रियाः॥', tr: 'Ye tu dharmyamritamidam yathoktam paryupasate, shraddadhana matparama bhaktasteativa me priyah.', en: 'Who follow this deathless path of right, as taught, with faith, holding me highest — those devotees are supremely dear to me.', hi: 'जो इस धर्ममय अमृत का श्रद्धा से यथोक्त सेवन करते हैं, मुझे परम मानने वाले वे भक्त मुझे अत्यंत प्रिय हैं।'}
];
