import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter17Meta: GitaChapterDetail = {
  n: 17,
  title: {en: 'Chapter 17 · Shraddhatraya Vibhaga Yoga', hi: 'अध्याय 17 · श्रद्धात्रय विभाग योग'},
  summary: {
    en: 'Three kinds of faith — in food, worship, charity, and Om Tat Sat. 28 verses.',
    hi: 'तीन प्रकार की श्रद्धा — आहार, पूजा, दान और ॐ तत् सत् में। 28 श्लोक।'
  }
};

export const chapter17Verses: GitaVerse[] = [
  {n: 1, speaker: 'arjuna', sa: 'ये शास्त्रविधिमुत्सृज्य यजन्ते श्रद्धयान्विताः। तेषां निष्ठा तु का कृष्ण सत्त्वमाहो रजस्तमः॥', tr: 'Ye shastravidhimutsrijya yajante shraddhayanvitahan, tesham nishtha tu ka Krishna sattvamaho rajastamah.', en: 'Those who worship with faith yet set aside the rule — is their stand sattvic, rajasic or tamasic, Krishna?', hi: 'जो शास्त्रविधि छोड़कर श्रद्धा से पूजते हैं, उनकी निष्ठा क्या है — सत्त्व, रज या तम, कृष्ण?'},
  {n: 2, speaker: 'krishna', sa: 'त्रिविधा भवति श्रद्धा देहिनां सा स्वभावजा। सात्त्विकी राजसी चैव तामसी चेति तां शृणु॥', tr: 'Trividha bhavati shraddha dehinam sa svabhavaja, sattviki rajasi chaiva tamasi cheti tam shrinu.', en: 'Faith in the embodied is threefold, born of their nature — sattvic, rajasic and tamasic — hear of each.', hi: 'देहधारियों की स्वभाव से उत्पन्न श्रद्धा तीन प्रकार की होती है — सात्त्विकी, राजसी और तामसी; उसे सुनो।'},
  {n: 3, speaker: 'krishna', sa: 'सत्त्वानुरूपा सर्वस्य श्रद्धा भवति भारत। श्रद्धामयोऽयं पुरुषो यो यच्छ्रद्धः स एव सः॥', tr: 'Sattvanurupa sarvasya shraddha bhavati Bharata, shraddhamayoayam purusho yo yachchraddhah sa eva sah.', en: 'Each one’s faith follows their inner make, Bharata — a person is made of faith, and becomes what they trust.', hi: 'सबकी श्रद्धा अपने अंतःकरण के अनुसार होती है, भारत — मनुष्य श्रद्धामय है, जैसी श्रद्धा वैसा ही वह।'},
  {n: 4, speaker: 'krishna', sa: 'यजन्ते सात्त्विका देवान्यक्षरक्षांसि राजसाः। प्रेतान्भूतगणांश्चान्ये यजन्ते तामसा जनाः॥', tr: 'Yajante sattvika devanyaksharakshamsi rajasahan, pretanbhutaganamshchanye yajante tamasa janahan.', en: 'The sattvic worship the bright gods, the rajasic worship powers of hunger, and the tamasic worship ghosts and spirits.', hi: 'सात्त्विक देवों को पूजते हैं, राजस यक्ष-राक्षसों को, और तामस प्रेत-भूतगणों को पूजते हैं।'},
  {n: 5, speaker: 'krishna', sa: 'अशास्त्रविहितं घोरं तप्यन्ते ये तपो जनाः। दम्भाहङ्कारसंयुक्ताः कामरागबलान्विताः॥', tr: 'Ashastravihitam ghoram tapyante ye tapo janahan, dambahankarasamyuktah kamaragabalanvitahan.', en: 'Those who practise harsh rites against the rule, full of show, ego, craving and force.', hi: 'जो शास्त्र विरुद्ध घोर तप तपते हैं, दम्भ-अहंकार से युक्त, काम-राग-बल से भरे।'},
  {n: 6, speaker: 'krishna', sa: 'कर्षयन्तः शरीरस्थं भूतग्राममचेतसः। मां चैवान्तःशरीरस्थं तान्विद्ध्यासुरनिश्चयान्॥', tr: 'Karshayantah sharirastham bhutagramamachetasah, mam chaivantahsharirastham tanviddhyasuranishchayan.', en: 'They torment the body’s elements and me within — know such senseless ones as demonic in resolve.', hi: 'वे शरीर के भूतसमूह को और अंतःस्थित मुझको कष्ट देते हैं — उन्हें आसुरी निश्चय वाला जानो।'},
  {n: 7, speaker: 'krishna', sa: 'आहारस्त्वपि सर्वस्य त्रिविधो भवति प्रियः। यज्ञस्तपस्तथा दानं तेषां भेदमिमं शृणु॥', tr: 'Aharastvapi sarvasya trividho bhavati priyah, yajnastapastatha danam tesham bhedamimam shrinu.', en: 'Even food, worship, austerity and giving please each in three ways — hear their divisions.', hi: 'आहार भी सबको तीन प्रकार का प्रिय होता है, वैसे ही यज्ञ, तप और दान — उनका भेद सुनो।'},
  {n: 8, speaker: 'krishna', sa: 'आयुःसत्त्वबलारोग्यसुखप्रीतिविवर्धनाः। रस्याः स्निग्धाः स्थिरा हृद्या आहाराः सात्त्विकप्रियाः॥', tr: 'Ayuhsattvabalarogyasukhapritivivardhanahan, rasyah snigdhah sthira hridya aharah sattvikapriyahan.', en: 'Juicy, gentle, steady and heart-gladdening foods that build life, clarity, strength and health please the sattvic.', hi: 'आयु, सत्त्व, बल, आरोग्य, सुख और प्रीति बढ़ाने वाले रसीले, स्निग्ध, स्थिर, हृदयप्रिय आहार सात्त्विकों को प्रिय हैं।'},
  {n: 9, speaker: 'krishna', sa: 'कट्वम्ललवणात्युष्णतीक्ष्णरूक्षविदाहिनः। आहारा राजसस्येष्टा दुःखशोकामयप्रदाः॥', tr: 'Katvamlalavanatyushnatikshnarukshavidahinah, ahara rajasasyeshta duhkhashokamayapradahan.', en: 'Bitter, sour, salty, over-hot, sharp, dry and burning foods please the rajasic and bring pain and sickness.', hi: 'कड़वे, खट्टे, नमकीन, अति गरम, तीखे, रूखे और दाहकारी आहार राजस को प्रिय हैं, जो दुःख-शोक-रोग देते हैं।'},
  {n: 10, speaker: 'krishna', sa: 'यातयामं गतरसं पूति पर्युषितं च यत्। उच्छिष्टमपि चामेध्यं भोजनं तामसप्रियम्॥', tr: 'Yatayamam gatarasam puti paryushitam cha yat, uchchhishtamapi chamedhyam bhojanam tamasapriyam.', en: 'Stale, tasteless, rotten, leftover and impure food pleases the tamasic.', hi: 'बासी, रसहीन, दुर्गंधित, रखा हुआ, जूठा और अपवित्र भोजन तामस को प्रिय है।'},
  {n: 11, speaker: 'krishna', sa: 'अफलाकाङ्क्षिभिर्यज्ञो विधिदृष्टो य इज्यते। यष्टव्यमेवेति मनः समाधाय स सात्त्विकः॥', tr: 'Aphalakankshibhiryajno vidhidrishto ya ijyate, yashtavyameveti manah samadhaya sa sattvikah.', en: 'Worship done by the rule, as duty alone, with no hunger for fruit — that is sattvic.', hi: 'फल की इच्छा बिना, विधिपूर्वक, कर्तव्य भाव से मन लगाकर जो यज्ञ किया जाए, वह सात्त्विक है।'},
  {n: 12, speaker: 'krishna', sa: 'अभिसन्धाय तु फलं दम्भार्थमपि चैव यत्। इज्यते भरतश्रेष्ठ तं यज्ञं विद्धि राजसम्॥', tr: 'Abhisandhaya tu phalam dambharthamapi chaiva yat, ijyate Bharatas reshtha tam yajnam viddhi rajasam.', en: 'Worship done eyeing reward or for mere show, best of Bharatas — know that as rajasic.', hi: 'फल को लक्ष्य कर या दिखावे हेतु जो यज्ञ किया जाए, भरतश्रेष्ठ, उसे राजस जानो।'},
  {n: 13, speaker: 'krishna', sa: 'विधिहीनमसृष्टान्नं मन्त्रहीनमदक्षिणम्। श्रद्धाविरहितं यज्ञं तामसं परिचक्षते॥', tr: 'Vidhihinamasrishtannam mantrahinamadakshinam, shraddhavirahitam yajnam tamasam parichakshate.', en: 'Worship against the rule, with no food shared, no chant, no gift and no faith — that is tamasic.', hi: 'विधिहीन, अन्नदान रहित, मंत्रहीन, दक्षिणाहीन और श्रद्धाहीन यज्ञ तामस कहा जाता है।'},
  {n: 14, speaker: 'krishna', sa: 'देवद्विजगुरुप्राज्ञपूजनं शौचमार्जवम्। ब्रह्मचर्यमहिंसा च शारीरं तप उच्यते॥', tr: 'Devadvijaguruprajnapujanam shauchamarjavam, brahmacharyamahimsa cha shariram tapa uchyate.', en: 'Honouring gods, the wise, teachers and elders, with purity, honesty, chastity and non-harming — this is bodily discipline.', hi: 'देव, ब्राह्मण, गुरु और ज्ञानी का पूजन, पवित्रता, सरलता, ब्रह्मचर्य और अहिंसा — यह शारीरिक तप है।'},
  {n: 15, speaker: 'krishna', sa: 'अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत्। स्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते॥', tr: 'Anudvegakaram vakyam satyam priyahitam cha yat, svadhyayabhyasanam chaiva vanmayam tapa uchyate.', en: 'Speech that calms, is true, kind and helpful, along with steady study — this is discipline of words.', hi: 'उद्वेग न करने वाला, सत्य, प्रिय और हितकारी वचन तथा स्वाध्याय का अभ्यास — यह वाणी का तप है।'},
  {n: 16, speaker: 'krishna', sa: 'मनःप्रसादः सौम्यत्वं मौनमात्मविनिग्रहः। भावसंशुद्धिरित्येतत्तपो मानसमुच्यते॥', tr: 'Manahprasadah saumyatvam maunamatmavinigrahah, bhavasamshuddhirityetattapo manasamuchyate.', en: 'A calm clear mind, gentleness, quiet, self-control and a pure heart — this is discipline of mind.', hi: 'मन की प्रसन्नता, सौम्यता, मौन, आत्मसंयम और भावशुद्धि — यह मानसिक तप कहा जाता है।'},
  {n: 17, speaker: 'krishna', sa: 'श्रद्धया परया तप्तं तपस्तत्त्रिविधं नरैः। अफलाकाङ्क्षिभिर्युक्तैः सात्त्विकं परिचक्षते॥', tr: 'Shraddhaya paraya taptam tapastattrividham naraih, aphalakankshibhiryuktaih sattvikam parichakshate.', en: 'This threefold discipline, practised with deep faith and no hunger for fruit, is called sattvic.', hi: 'परम श्रद्धा से, फल की इच्छा बिना, योगियों द्वारा तपा यह त्रिविध तप सात्त्विक कहा जाता है।'},
  {n: 18, speaker: 'krishna', sa: 'सत्कारमानपूजार्थं तपो दम्भेन चैव यत्। क्रियते तदिह प्रोक्तं राजसं चलमध्रुवम्॥', tr: 'Satkaramanapujartham tapo dambhena chaiva yat, kriyate tadiha proktam rajasam chalamadhruvam.', en: 'Discipline done for honour, praise or show is rajasic here — shaky and short-lived.', hi: 'सत्कार, मान और पूजा हेतु दम्भ से जो तप किया जाए, वह राजस, चंचल और अनिश्चित कहा गया है।'},
  {n: 19, speaker: 'krishna', sa: 'मूढग्राहेणात्मनो यत्पीडया क्रियते तपः। परस्योत्सादनार्थं वा तत्तामसमुदाहृतम्॥', tr: 'Mudhagrahenatmano yatpidaya kriyate tapah, parasyotsadanartham va tattamasamudahritam.', en: 'Discipline done from folly, tormenting oneself or meant to harm another, is tamasic.', hi: 'मूढ़ हठ से स्वयं को पीड़ा देकर या पराये के नाश हेतु जो तप किया जाए, वह तामस कहा गया है।'},
  {n: 20, speaker: 'krishna', sa: 'दातव्यमिति यद्दानं दीयतेऽनुपकारिणे। देशे काले च पात्रे च तद्दानं सात्त्विकं स्मृतम्॥', tr: 'Datavyamiti yaddanam diyateanupakarine, deshe kale cha patre cha taddanam sattvikam smritam.', en: 'Giving as duty to one who cannot repay, in the right place, time and to the worthy — that is sattvic.', hi: 'देना कर्तव्य है मानकर, प्रत्युपकार न करने वाले को, उचित देश-काल-पात्र में जो दान दिया जाए, वह सात्त्विक है।'},
  {n: 21, speaker: 'krishna', sa: 'यत्तु प्रत्युपकारार्थं फलमुद्दिश्य वा पुनः। दीयते च परिक्लिष्टं तद्दानं राजसं स्मृतम्॥', tr: 'Yattu pratyupakarartham phalamuddishya va punah, diyate cha pariklishtam taddanam rajasam smritam.', en: 'Giving that eyes a return or reward, or is given grudgingly — that is rajasic.', hi: 'जो प्रत्युपकार हेतु या फल पाने के लिए, या क्लेश से दिया जाए, वह दान राजस कहा गया है।'},
  {n: 22, speaker: 'krishna', sa: 'अदेशकाले यद्दानमपात्रेभ्यश्च दीयते। असत्कृतमवज्ञातं तत्तामसमुदाहृतम्॥', tr: 'Adeshakale yaddanamapatrebhyashcha diyate, asatkritamavajnatam tattamasamudahritam.', en: 'Giving at the wrong place or time, to the unworthy, with scorn and no respect — that is tamasic.', hi: 'अनुचित देश-काल में, अपात्रों को, बिना सत्कार और तिरस्कार से जो दान दिया जाए, वह तामस कहा गया है।'},
  {n: 23, speaker: 'krishna', sa: 'ॐ तत्सदिति निर्देशो ब्रह्मणस्त्रिविधः स्मृतः। ब्राह्मणास्तेन वेदाश्च यज्ञाश्च विहिताः पुरा॥', tr: 'Om tatsaditi nirdesho brahmanastrividhah smritah, brahmanastena vedashcha yajnashcha vihitah pura.', en: 'Om Tat Sat is the threefold name of Brahman, from which priests, Vedas and rites arose of old.', hi: 'ॐ तत् सत् — यह ब्रह्म का त्रिविध निर्देश है, जिससे प्राचीन काल में ब्राह्मण, वेद और यज्ञ बने।'},
  {n: 24, speaker: 'krishna', sa: 'तस्मादोमित्युदाहृत्य यज्ञदानतपःक्रियाः। प्रवर्तन्ते विधानोक्ताः सततं ब्रह्मवादिनाम्॥', tr: 'Tasmadomityudahritya yajnadanatapahkriyah, pravartante vidhanoktah satatam brahmavadinam.', en: 'So knowers of Brahman ever begin rites of worship, giving and discipline with Om, as laid down.', hi: 'अतः ब्रह्मवादी विधिपूर्वक ॐ कहकर यज्ञ, दान और तप की क्रियाएँ सदा आरंभ करते हैं।'},
  {n: 25, speaker: 'krishna', sa: 'तदित्यनभिसन्धाय फलं यज्ञतपःक्रियाः। दानक्रियाश्च विविधाः क्रियन्ते मोक्षकाङ्क्षिभिः॥', tr: 'Tadityanabhisandhaya phalam yajnatapahkriyah, danakriyashcha vividhah kriyante mokshakankshibhih.', en: 'With the word Tat, seekers of freedom do varied rites of worship, discipline and giving, seeking no fruit.', hi: 'तत् कहकर, फल की इच्छा बिना, मोक्ष चाहने वाले नाना यज्ञ-तप-दान क्रियाएँ करते हैं।'},
  {n: 26, speaker: 'krishna', sa: 'सद्भावे साधुभावे च सदित्येतत्प्रयुज्यते। प्रशस्ते कर्मणि तथा सच्छब्दः पार्थ युज्यते॥', tr: 'Sadbhave sadhubhave cha sadityetatprayujyate, prashaste karmani tatha sachchhabdah Partha yujyate.', en: 'Sat marks what is real and good, Partha, and lends its name to every noble deed.', hi: 'सत् शब्द सत्ता और श्रेष्ठ भाव में प्रयुक्त होता है, पार्थ, तथा उत्तम कर्म में भी सत् शब्द लगता है।'},
  {n: 27, speaker: 'krishna', sa: 'यज्ञे तपसि दाने च स्थितिः सदिति चोच्यते। कर्म चैव तदर्थीयं सदित्येवाभिधीयते॥', tr: 'Yajne tapasi dane cha sthitih saditi chochyate, karma chaiva tadarthiyam sadityevabhidhiyate.', en: 'Steadiness in worship, discipline and giving is called Sat, and every deed done for that goal is Sat.', hi: 'यज्ञ, तप और दान में स्थिरता भी सत् कही जाती है, और उसके निमित्त कर्म भी सत् ही कहलाता है।'},
  {n: 28, speaker: 'krishna', sa: 'अश्रद्धया हुतं दत्तं तपस्तप्तं कृतं च यत्। असदित्युच्यते पार्थ न च तत्प्रेत्य नो इह॥', tr: 'Ashraddhaya hutam dattam tapastaptam kritam cha yat, asadityuchyate Partha na cha tatpretya no iha.', en: 'Whatever is offered, given or practised without faith is called asat, Partha — void here and hereafter.', hi: 'श्रद्धा बिना हवन, दान, तप या कर्म असत् कहलाता है, पार्थ — वह न यहाँ फलता है न परलोक में।'}
];
