import type {GitaChapterDetail, GitaVerse} from './chapters';

export const chapter15Meta: GitaChapterDetail = {
  n: 15,
  title: {en: 'Chapter 15 · Purushottama Yoga', hi: 'अध्याय 15 · पुरुषोत्तम योग'},
  summary: {
    en: 'The supreme Person beyond the imperishable and perishable. 20 verses.',
    hi: 'क्षर-अक्षर से परे पुरुषोत्तम। 20 श्लोक।'
  }
};

export const chapter15Verses: GitaVerse[] = [
  {n: 1, speaker: 'krishna', sa: 'ऊर्ध्वमूलमधःशाखमश्वत्थं प्राहुरव्ययम्। छन्दांसि यस्य पर्णानि यस्तं वेद स वेदवित्॥', tr: 'Urdhvamulamadhashakhamashvattham prahuravyayam, chhandamsi yasya parnani yastam veda sa vedavit.', en: 'They speak of an undying pipal tree with roots above and branches below, whose leaves are hymns — knowing it is knowing the Veda.', hi: 'ऊपर मूल और नीचे शाखा वाला अविनाशी अश्वत्थ कहा गया, जिसके पत्ते छंद हैं — उसे जानने वाला वेदज्ञ है।'},
  {n: 2, speaker: 'krishna', sa: 'अधश्चोर्ध्वं प्रसृतास्तस्य शाखा गुणप्रवृद्धा विषयप्रवालाः। अधश्च मूलान्यनुसन्ततानि कर्मानुबन्धीनि मनुष्यलोके॥', tr: 'Adhashchordhvam prasritastasya shakha gunapravriddha vishayapravalahan, adhashcha mulanyanusantatani karmanubandhini manushyaloke.', en: 'Its branches spread below and above, fed by the gunas, with sense-pleasures as shoots, and roots of karma binding humans below.', hi: 'गुणों से बढ़ी, विषय रूपी कोंपलों वाली इसकी शाखाएँ ऊपर-नीचे फैली हैं, और कर्म बाँधने वाली जड़ें मनुष्यलोक में नीचे फैली हैं।'},
  {n: 3, speaker: 'krishna', sa: 'न रूपमस्येह तथोपलभ्यते नान्तो न चादिर्न च सम्प्रतिष्ठा। अश्वत्थमेनं सुविरूढमूलमसङ्गशस्त्रेण दृढेन छित्त्वा॥', tr: 'Na rupamasyeha tathopalabhyate nanto na chadirna cha sampratishtha, ashvatthamenam suvirudhamulam asangashastrena dridhena chhittva.', en: 'Its true shape, end, beginning and foundation are unseen here — so cut this deep-rooted tree with the strong sword of detachment.', hi: 'इसका रूप, आदि, अंत और स्थिति यहाँ नहीं दिखते — इस दृढ़मूल अश्वत्थ को वैराग्य रूपी दृढ़ शस्त्र से काटकर।'},
  {n: 4, speaker: 'krishna', sa: 'ततः पदं तत्परिमार्गितव्यं यस्मिन्गता न निवर्तन्ति भूयः। तमेव चाद्यं पुरुषं प्रपद्ये यतः प्रवृत्तिः प्रसृता पुराणी॥', tr: 'Tatah padam tatparimargitavyam yasmingata na nivartanti bhuyah, tameva chadyam purusham prapadye yatah pravrittih prasrita purani.', en: 'Then seek the place of no return, surrendering to the first Person from whom this ancient world streams forth.', hi: 'फिर उस पद को खोजना चाहिए जहाँ जाकर लौटना नहीं होता — उसी आदि पुरुष की शरण लेता हूँ जिनसे पुरातन प्रवृत्ति निकली है।'},
  {n: 5, speaker: 'krishna', sa: 'निर्मानमोहा जितसङ्गदोषा अध्यात्मनित्या विनिवृत्तकामाः। द्वन्द्वैर्विमुक्ताः सुखदुःखसंज्ञैर्गच्छन्त्यमूढाः पदमव्ययं तत्॥', tr: 'Nirmanamoha jitasangadosha adhyatmanitya vinivrittakamahan, dvandvairvimuktah sukhaduhkhasamjnairgachchhantyamudhah padamavyayam tat.', en: 'Free of pride and delusion, beyond clinging and craving, beyond joy-sorrow pairs, the undeluded reach that deathless home.', hi: 'मान-मोह से रहित, आसक्ति दोष जीते, आत्मज्ञान में स्थित, कामना से मुक्त और सुख-दुःख द्वंद्वों से छूटे ज्ञानी उस अव्यय पद को पाते हैं।'},
  {n: 6, speaker: 'krishna', sa: 'न तद्भासयते सूर्यो न शशाङ्को न पावकः। यद्गत्वा न निवर्तन्ते तद्धाम परमं मम॥', tr: 'Na tadbhasayate suryo na shashanko na pavakah, yadgatva na nivartante taddhama paramam mama.', en: 'No sun, moon or fire lights it — reaching my supreme home, none return.', hi: 'उसे न सूर्य, न चंद्र, न अग्नि प्रकाशित करते हैं — जहाँ जाकर लौटना नहीं होता, वही मेरा परम धाम है।'},
  {n: 7, speaker: 'krishna', sa: 'ममैवांशो जीवलोके जीवभूतः सनातनः। मनःषष्ठानीन्द्रियाणि प्रकृतिस्थानि कर्षति॥', tr: 'Mamaivamsho jivaloke jivabhutah sanatanah, manahshashthanindriyani prakritisthani karshati.', en: 'A timeless spark of me lives as the soul here, pulling the mind and five senses rooted in nature.', hi: 'जीवलोक में मेरा ही सनातन अंश जीव बना है, जो प्रकृति में स्थित मन सहित छह इंद्रियों को खींचता है।'},
  {n: 8, speaker: 'krishna', sa: 'शरीरं यदवाप्नोति यच्चाप्युत्क्रामतीश्वरः। गृहीत्वैतानि संयाति वायुर्गन्धानिवाशयात्॥', tr: 'Shariram yadavapnoti yachchapyutkramatishvarah, grihitvaitani samyati vayurgandhanivashayat.', en: 'When the lord of the body leaves or enters a form, he carries the senses along like wind carrying scent.', hi: 'जैसे वायु गंध को ले जाती है, वैसे ही देह का स्वामी शरीर छोड़ते या पाते समय इन इंद्रियों को साथ ले जाता है।'},
  {n: 9, speaker: 'krishna', sa: 'श्रोत्रं चक्षुः स्पर्शनं च रसनं घ्राणमेव च। अधिष्ठाय मनश्चायं विषयानुपसेवते॥', tr: 'Shrotram chakshuh sparshanam cha rasanam ghranameva cha, adhishthaya manashchayam vishayanupasevate.', en: 'Dwelling in ear, eye, touch, taste, smell and mind, the soul tastes sense-pleasures.', hi: 'कान, आँख, त्वचा, जीभ, नाक और मन का आश्रय लेकर यह जीव विषयों का सेवन करता है।'},
  {n: 10, speaker: 'krishna', sa: 'उत्क्रामन्तं स्थितं वापि भुञ्जानं वा गुणान्वितम्। विमूढा नानुपश्यन्ति पश्यन्ति ज्ञानचक्षुषः॥', tr: 'Utkramantam sthitam vapi bhunjanam va gunanvitam, vimudha nanupashyanti pashyanti jnanachakshushah.', en: 'The deluded miss the soul leaving, dwelling or enjoying through the gunas, but the eyes of wisdom see.', hi: 'गुणों से युक्त जीव के जाने, रहने या भोगने को मूढ़ नहीं देखते, ज्ञाननेत्र वाले देखते हैं।'},
  {n: 11, speaker: 'krishna', sa: 'यतन्तो योगिनश्चैनं पश्यन्त्यात्मन्यवस्थितम्। यतन्तोऽप्यकृतात्मानो नैनं पश्यन्त्यचेतसः॥', tr: 'Yatanto yoginashchainam pashyantyatmanyavasthitam, yatantoapyakritatmano nainam pashyantyachetasah.', en: 'Striving yogis see the Self within, while the unready striving still cannot see.', hi: 'यत्नशील योगी आत्मा में स्थित इसे देखते हैं, पर अशुद्धचित्त यत्न करने पर भी इसे नहीं देख पाते।'},
  {n: 12, speaker: 'krishna', sa: 'यदादित्यगतं तेजो जगद्भासयतेऽखिलम्। यच्चन्द्रमसि यच्चाग्नौ तत्तेजो विद्धि मामकम्॥', tr: 'Yadadityagatam tejo jagadbhasayateakhilam, yachchandramasi yachchagnau tattejo viddhi mamakam.', en: 'The light in the sun that wakes the whole world, in the moon and in fire — know that radiance as mine.', hi: 'सूर्य में जो तेज समस्त जगत को प्रकाशित करता है, और जो चंद्र व अग्नि में है — वह तेज मेरा ही जानो।'},
  {n: 13, speaker: 'krishna', sa: 'गामाविश्य च भूतानि धारयाम्यहमोजसा। पुष्णामि चौषधीः सर्वाः सोमो भूत्वा रसात्मकः॥', tr: 'Gamavishya cha bhutani dharayam yahamojasa, pushnami chaushadhih sarvah somo bhutva rasatmakah.', en: 'Entering the earth, I hold all beings by strength, and as the watery moon I feed every plant.', hi: 'पृथ्वी में प्रवेश कर मैं प्राणियों को धारण करता हूँ, और रसमय सोम बनकर सब औषधियों का पोषण करता हूँ।'},
  {n: 14, speaker: 'krishna', sa: 'अहं वैश्वानरो भूत्वा प्राणिनां देहमाश्रितः। प्राणापानसमायुक्तः पचाम्यन्नं चतुर्विधम्॥', tr: 'Aham vaishvanaro bhutva praninam dehamashritah, pranapanasamayuktah pachamyannam chaturvidham.', en: 'As the fire of digestion in every body, joined with in-breath and out-breath, I cook the four kinds of food.', hi: 'प्राणियों के देह में वैश्वानर अग्नि बनकर, प्राण-अपान से युक्त हो, चार प्रकार के अन्न को मैं पचाता हूँ।'},
  {n: 15, speaker: 'krishna', sa: 'सर्वस्य चाहं हृदि सन्निविष्टो मत्तः स्मृतिर्ज्ञानमपोहनं च। वेदैश्च सर्वैरहमेव वेद्यो वेदान्तकृद्वेदविदेव चाहम्॥', tr: 'Sarvasya chaham hridi sannivishto mattah smritirjnanamapohanam cha, vedaishcha sarvairahameva vedyo vedantakridvedavideva chaham.', en: 'I dwell in every heart, giving memory, knowing and forgetting — I am what all Vedas point to, their maker and knower.', hi: 'मैं सबके हृदय में स्थित हूँ, मुझसे ही स्मृति, ज्ञान और विस्मृति होती है — सब वेदों से जानने योग्य मैं ही हूँ, वेदांत का कर्ता और ज्ञाता भी।'},
  {n: 16, speaker: 'krishna', sa: 'द्वाविमौ पुरुषौ लोके क्षरश्चाक्षर एव च। क्षरः सर्वाणि भूतानि कूटस्थोऽक्षर उच्यते॥', tr: 'Dvavimau purushau loke ksharashchakshara eva cha, ksharah sarvani bhutani kutasthoakshara uchyate.', en: 'Two persons live in this world — the perishable, which is all beings, and the imperishable, the changeless ground.', hi: 'लोक में दो पुरुष हैं — क्षर और अक्षर; सब प्राणी क्षर हैं और कूटस्थ अक्षर कहा जाता है।'},
  {n: 17, speaker: 'krishna', sa: 'उत्तमः पुरुषस्त्वन्यः परमात्मेत्युदाहृतः। यो लोकत्रयमाविश्य बिभर्त्यव्यय ईश्वरः॥', tr: 'Uttamah purushastvanyah paramatmetyudahritah, yo lokatrayamavishya bibhartyavyaya ishvarah.', en: 'Beyond both stands the highest Person, called the supreme Self, the deathless Lord holding all three worlds.', hi: 'इनसे अन्य उत्तम पुरुष परमात्मा कहा गया है, जो तीनों लोकों में प्रवेश कर सबका भरण करता अविनाशी ईश्वर है।'},
  {n: 18, speaker: 'krishna', sa: 'यस्मात्क्षरमतीतोऽहमक्षरादपि चोत्तमः। अतोऽस्मि लोके वेदे च प्रथितः पुरुषोत्तमः॥', tr: 'Yasmatksharamatitoahamaksharadapi chottamah, atoasmi loke vede cha prathitah purushottamah.', en: 'Since I surpass the perishable and outshine even the imperishable, the world and Veda hail me as Purushottama.', hi: 'क्षर से अतीत और अक्षर से भी उत्तम होने से मैं लोक और वेद में पुरुषोत्तम नाम से प्रसिद्ध हूँ।'},
  {n: 19, speaker: 'krishna', sa: 'यो मामेवमसम्मूढो जानाति पुरुषोत्तमम्। स सर्वविद्भजति मां सर्वभावेन भारत॥', tr: 'Yo mamevamasammudho janati purushottamam, sa sarvavidbhajati mam sarvabhavena Bharata.', en: 'Whoever truly knows me as Purushottama worships me with their whole being, Bharata, as the knower of all.', hi: 'जो मोहरहित होकर मुझे पुरुषोत्तम जानता है, वह सर्वज्ञ होकर सब भाव से मुझे भजता है, भारत।'},
  {n: 20, speaker: 'krishna', sa: 'इति गुह्यतमं शास्त्रमिदमुक्तं मयानघ। एतद्बुद्ध्वा बुद्धिमान्स्यात्कृतकृत्यश्च भारत॥', tr: 'Iti guhyatamam shastramidamuktam mayanagha, etadbuddhva buddhimansyatkritakrityashcha Bharata.', en: 'Thus I have spoken the most hidden teaching, sinless one — grasping it brings wisdom and fulfilment, Bharata.', hi: 'हे निष्पाप! यह गुह्यतम शास्त्र मैंने कहा — इसे जानकर मनुष्य बुद्धिमान और कृतकृत्य होता है, भारत।'}
];
